document.addEventListener("DOMContentLoaded",()=>{const c=window.crowSupabase,msg=document.getElementById("msg");if(!c)return;
const setMsg=t=>{if(msg)msg.textContent=String(t||"")};
const redirectTo=new URL("profile.html",location.href).href; const verifyTo=new URL("verify-email.html",location.href).href;
const showError=error=>{if(!error)return false;setMsg(error.message||String(error));return true};
const oauthError=()=>{const h=new URLSearchParams(location.hash.replace(/^#/,"")),q=new URLSearchParams(location.search),code=h.get("error_code")||q.get("error_code"),desc=h.get("error_description")||q.get("error_description");if(code||desc){let text=desc||code||"Google sign-in failed";try{text=decodeURIComponent(text)}catch{}setMsg(text.replace(/\+/g," "));history.replaceState({},document.title,location.pathname+location.search.replace(/([?&])(error|error_code|error_description)=[^&]*/g,"").replace(/[?&]$/,""));return true}return false};
oauthError();
const profileFor=async u=>{if(!u)return null;const m=u.user_metadata||{},email=u.email||"",base=(email.split("@")[0]||"crowmember").toLowerCase().replace(/[^a-z0-9_]+/g,"").slice(0,30)||"crowmember";const display_name=m.display_name||m.full_name||m.name||email.split("@")[0]||"CrowSpace Member",avatar_url=m.avatar_url||m.picture||"",wanted=(m.username||base).toLowerCase().replace(/[^a-z0-9_]+/g,"").slice(0,30)||"crowmember";
const {data:existing}=await c.from("membership_profiles").select("id,display_name,username,bio,avatar_url").eq("id",u.id).maybeSingle();if(existing)return existing;
let username=wanted;let {data,error}=await c.from("membership_profiles").insert({id:u.id,display_name,username,bio:"",avatar_url,updated_at:new Date().toISOString()}).select().maybeSingle();
if(error&&error.code==="23505"){username=(wanted.slice(0,23)||"crowmember")+"_"+u.id.replace(/-/g,"").slice(0,6);const retry=await c.from("membership_profiles").insert({id:u.id,display_name,username,bio:"",avatar_url,updated_at:new Date().toISOString()}).select().maybeSingle();data=retry.data;error=retry.error}
if(error)console.warn("CrowSpace profile:",error.message);return data||null};
document.getElementById("signupForm")?.addEventListener("submit",async e=>{e.preventDefault();const display_name=document.getElementById("display_name").value.trim(),username=document.getElementById("username").value.trim().toLowerCase(),email=document.getElementById("email").value.trim(),password=document.getElementById("password").value,terms=document.getElementById("terms")?.checked!==false;if(!terms){setMsg("Please agree to the CrowSpace Terms and Community Rules.");return}if(username.length<3||username.length>30||!/^[A-Za-z0-9_]+$/.test(username)){setMsg("Username must be 3–30 characters using letters, numbers, or underscores.");return}if(password.length<8){setMsg("Password must be at least 8 characters.");return}setMsg("Creating your CrowRules account…");const {data,error}=await c.auth.signUp({email,password,options:{data:{display_name,username},emailRedirectTo:verifyTo}});if(error){setMsg(error.message);return}if(data.user&&data.session)await profileFor(data.user);if(data.session){setMsg("Welcome to CrowSpace!");setTimeout(()=>location.href="profile.html",300)}else{setMsg("Account created. Check your email to verify your CrowSpace account.");const box=document.getElementById("verifyBox"),ve=document.getElementById("verifyEmail");if(box){box.hidden=false;if(ve)ve.textContent=email}localStorage.setItem("crowspace_pending_verification_email",email)}});
document.getElementById("resendVerification")?.addEventListener("click",async()=>{const email=(document.getElementById("email")?.value||localStorage.getItem("crowspace_pending_verification_email")||"").trim();if(!email){setMsg("Enter your email address first.");return}const b=document.getElementById("resendVerification");if(b){b.disabled=true;b.textContent="Sending…"}setMsg("Sending a new verification email…");const {error}=await c.auth.resend({type:"signup",email,options:{emailRedirectTo:verifyTo}});setMsg(error?error.message:"A new verification email has been sent.");setTimeout(()=>{if(b){b.disabled=false;b.textContent="Resend verification email"}},5000)});document.getElementById("loginForm")?.addEventListener("submit",async e=>{e.preventDefault();const email=document.getElementById("email").value.trim();setMsg("Signing in…");const {data,error}=await c.auth.signInWithPassword({email,password:document.getElementById("password").value});if(error){setMsg(error.message);if(/confirm|verified|not confirmed/i.test(error.message)&&email){const box=document.getElementById("msg");if(box&&!document.getElementById("loginResendVerification")){const b=document.createElement("button");b.id="loginResendVerification";b.className="btn";b.type="button";b.textContent="Resend verification email";box.appendChild(document.createTextNode(" "));box.appendChild(b);b.onclick=async()=>{b.disabled=true;b.textContent="Sending…";const r=await c.auth.resend({type:"signup",email,options:{emailRedirectTo:verifyTo}});b.textContent=r.error?"Try again":"Verification email sent";if(r.error)setMsg(r.error.message);setTimeout(()=>{b.disabled=false;b.textContent="Resend verification email"},5000)}}}return}if(data.user)await profileFor(data.user);if(data.session){location.href=redirectTo}else{setMsg("Check your email to confirm your CrowSpace account.")}});
document.getElementById("password")?.addEventListener("input",e=>{const el=document.getElementById("passwordStrength");if(!el)return;const v=e.target.value,s=(v.length>=8?1:0)+( /[A-Z]/.test(v)?1:0)+(/[0-9]/.test(v)?1:0)+(/[^A-Za-z0-9]/.test(v)?1:0);el.textContent=s>=4?"Strong password":s>=2?"Good password — add more variety for extra strength":"Use 8+ characters with a mix of letters and numbers.";});document.getElementById("google")?.addEventListener("click",async()=>{setMsg("Connecting to Google…");const {error}=await c.auth.signInWithOAuth({provider:"google",options:{redirectTo,queryParams:{prompt:"select_account"}}});if(error)setMsg(error.message)});
c.auth.onAuthStateChange((event,session)=>{if(!session?.user){if(event==="SIGNED_OUT")setMsg("Signed out.");return}setTimeout(()=>{profileFor(session.user).catch(err=>console.warn("CrowSpace auth profile:",err));if(event==="SIGNED_IN"&&(location.pathname.endsWith("login.html")||location.pathname.endsWith("signup.html")))location.href=redirectTo},0)});
});