(()=>{const KEY="crowspace_local_v4",seed=window.CROWSPACE_DATA;
const fresh=()=>({user:JSON.parse(JSON.stringify(seed.user)),groups:JSON.parse(JSON.stringify(seed.groups)),spaces:JSON.parse(JSON.stringify(seed.spaces)),posts:JSON.parse(JSON.stringify(seed.posts)),rooms:JSON.parse(JSON.stringify(seed.rooms)),events:JSON.parse(JSON.stringify(seed.events)),friends:JSON.parse(JSON.stringify(seed.friends)),friendRequests:JSON.parse(JSON.stringify(seed.friendRequests)),conversations:JSON.parse(JSON.stringify(seed.conversations)),notifications:JSON.parse(JSON.stringify(seed.notifications)),media:JSON.parse(JSON.stringify(seed.media))});
let s=JSON.parse(localStorage.getItem(KEY)||"null")||fresh();
const save=()=>localStorage.setItem(KEY,JSON.stringify(s));
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const q=k=>new URLSearchParams(location.search).get(k);
const card=x=>'<article class="card">'+x+"</article>";
const btn=(t,a,cls="")=>'<button class="btn '+cls+'" data-action="'+esc(a)+'">'+esc(t)+"</button>";
const input=(n,p,v="")=>'<input class="search" name="'+n+'" placeholder="'+esc(p)+'" value="'+esc(v)+'">';
const empty=(t)=>'<div class="notice">'+esc(t)+"</div>";
const sig=p=>'<div class="signal">'+["❤️","🔥","😂","💡","🤝","⭐"].map(r=>'<button class="signal-btn" data-action="react:'+p.id+":"+r+'">'+r+" "+((p.reactions||{})[r]||0)+"</button>").join("")+"</div>";
const post=p=>card('<div class="post-head"><div class="mini-avatar">'+esc((p.author||"?").slice(0,2).toUpperCase())+'</div><div><b>'+esc(p.author)+'</b><div class="muted">CrowBoard · just now</div></div></div><p class="post-copy">'+esc(p.text)+'</p>'+sig(p)+'<div class="comments">'+(p.comments||[]).map(c=>'<div class="wall"><b>'+esc(c.author)+'</b><p>'+esc(c.text)+'</p></div>').join("")+'</div><form data-form="comment" data-id="'+p.id+'">'+input("text","Write a comment…")+'<button class="btn">Comment</button></form>');
const avatar=(name,img)=>img?'<img class="avatar-img" src="'+esc(img)+'" alt="">':'<div class="avatar">'+esc((name||"YOU").slice(0,2).toUpperCase())+"</div>";
function render(){const p=location.pathname.split("/").pop()||"index.html";let body="";
if(p==="index.html")body='<section class="hero"><span class="eyebrow">CROWSPACE 2.0</span><h1>Your Space.<br>Your People.<br>Your Universe.</h1><p>MySpace personality meets modern community tools — profiles, groups, conversations, media and community all in one local-first social experience.</p></section><div class="layout"><main>'+card('<span class="kicker">CROWBOARD</span><form data-form="post">'+input("text","What’s happening in your space?")+'<button class="btn">＋ Post</button></form>')+'<h2>YOUR CROWFEED</h2>'+s.posts.map(post).join("")+'</main><aside>'+profileMini()+card('<span class="kicker">QUICK ACTIONS</span><div class="stack">'+btn("Edit My Space","goto:customize.html")+btn("Create Post","goto:create-post.html")+btn("Find People","goto:discover.html")+btn("View Notifications","goto:notifications.html")+'</div>')+card('<span class="kicker">LOCAL MODE</span><p>Your CrowSpace activity is saved in this browser. Supabase is intentionally disconnected.</p>')+'</aside></div>';
else if(p==="profile.html")body=profilePage();
else if(p==="customize.html")body=customizePage();
else if(p==="groups.html")body=groupsPage();
else if(p==="group.html")body=groupPage();
else if(p==="spaces.html")body=spacesPage();
else if(p==="space.html")body=spacePage();
else if(p==="rooms.html")body=roomsPage();
else if(p==="room.html")body=roomPage();
else if(p==="friends.html")body=friendsPage();
else if(p==="discover.html")body=discoverPage();
else if(p==="messages.html"||p==="crowmail.html")body=mailPage();
else if(p==="events.html")body=eventsPage();
else if(p==="event.html")body=eventPage();
else if(p==="media.html"||p==="photos.html"||p==="videos.html")body=mediaPage(p);
else if(p==="notifications.html")body=notificationsPage();
else if(p==="create-post.html")body=createPostPage();
else if(p==="create-group.html")body=createGroupPage();
else if(p==="create-space.html")body=createSpacePage();
else if(p==="create-event.html")body=createEventPage();
else if(p==="circles.html")body=circlesPage();
else if(p==="settings.html")body=settingsPage();
else if(p==="crowcast.html")body=card('<section class="hero"><span class="eyebrow">COMING NEXT</span><h1>CrowCast</h1><p>Live text, audio and video community rooms are part of the CrowSpace roadmap.</p></section>');
document.getElementById("app").innerHTML='<div class="wrap">'+body+'<footer class="footer">CROWSPACE · Your Space. Your People. Your Universe.<br>Local-first prototype · No Supabase</footer></div>';
if(p==="discover.html")discover();
}
function profileMini(){return card('<span class="kicker">MY SPACE</span>'+avatar(s.user.name,s.user.avatar)+'<h2>'+esc(s.user.name)+'</h2><p class="muted">'+esc(s.user.handle)+" · "+esc(s.user.mood)+'</p><p>'+esc(s.user.bio)+'</p>'+btn("View Profile","goto:profile.html"));};
function profilePage(){const u=s.user;return '<section class="profile-cover" style="background-image:url('+esc(u.cover||"")+')"><div class="profile-overlay">'+avatar(u.name,u.avatar)+'<div><span class="eyebrow">MY SPACE</span><h1>'+esc(u.name)+'</h1><p>'+esc(u.handle)+' · '+esc(u.mood)+'</p><p class="muted">'+esc(u.location)+'</p></div></div></section><div class="profile-actions">'+btn("Edit My Space","goto:customize.html")+btn("My Media","goto:media.html")+btn("CrowMail","goto:messages.html")+'</div><div class="layout profile-layout"><main>'+card('<span class="kicker">ABOUT ME</span><h2>'+esc(u.sections?.[0]?.title||"About My World")+'</h2><p>'+esc(u.sections?.[0]?.text||u.bio)+'</p><div>'+u.interests.map(x=>'<span class="tag">'+esc(x)+'</span>').join("")+'</div>')+card('<span class="kicker">CURRENT SOUNDTRACK</span><h2>'+esc(u.musicTitle||"My Music")+'</h2><p class="muted">'+esc(u.music||"Add a music link from Customize My Space.")+'</p>')+card('<span class="kicker">CROWWALL</span><h2>Leave something for me</h2><form data-form="wall">'+input("text","Write a CrowWall message…")+'<button class="btn">Post to CrowWall</button></form>')+'</main><aside>'+card('<span class="kicker">FEATURED FRIENDS</span>'+s.friends.map(f=>'<div class="person-row">'+avatar(f.name,f.avatar)+'<div><b>'+esc(f.name)+'</b><p class="muted">'+esc(f.status)+'</p></div></div>').join(""))+card('<span class="kicker">MY GROUPS</span>'+s.groups.filter(g=>g.joined).map(g=>'<p>◈ <a href="group.html?id='+g.id+'">'+esc(g.name)+'</a></p>').join("")||empty("No groups joined yet."))+'</aside></div>';};
function customizePage(){const u=s.user;return '<section class="hero"><span class="eyebrow">PROFILE STUDIO</span><h1>Customize My Space</h1><p>Make your profile feel like your own website. Everything below is saved locally.</p></section><div class="layout"><main>'+card('<form data-form="profile"><label>Display name</label>'+input("name","Your display name",u.name)+'<label>@Username</label>'+input("handle","@username",u.handle)+'<label>Mood / status</label>'+input("mood","What are you feeling?",u.mood)+'<label>Location</label>'+input("location","City, State",u.location)+'<label>Bio</label><textarea class="search" name="bio" rows="4">'+esc(u.bio)+'</textarea><label>Cover artwork URL</label>'+input("cover","https://…",u.cover)+'<label>Avatar image URL</label>'+input("avatar","https://…",u.avatar)+'<label>Music / soundtrack URL</label>'+input("music","https://…",u.music)+'<label>Music title</label>'+input("musicTitle","Current soundtrack",u.musicTitle)+'<label>Interests (comma separated)</label>'+input("interests","Film, Music, Tacoma",u.interests.join(", "))+'<label>Featured section title</label>'+input("sectionTitle","About My World",u.sections?.[0]?.title||"About My World")+'<label>Featured section text</label><textarea class="search" name="sectionText" rows="4">'+esc(u.sections?.[0]?.text||"")+'</textarea><button class="btn">Save My Space</button></form>')+'</main><aside>'+card('<span class="kicker">PERSONALITY</span>'+btn("Cyber Neon","theme:neon")+btn("Midnight","theme:midnight")+btn("Retro Web","theme:retro")+btn("Reset Local Data","reset:all","danger"))+card('<span class="kicker">PROFILE FEATURES</span><p>Cover artwork · Avatar · Music · Featured friends · Interests · Custom sections · CrowWall · Media galleries</p>')+'</aside></div>';};
function groupsPage(){return '<section class="hero"><span class="eyebrow">COMMUNITY</span><h1>Groups</h1><p>Facebook-style communities with their own discussions, members, rules, media and events.</p>'+btn("＋ Create Group","goto:create-group.html")+'</section><div class="grid">'+s.groups.map(g=>card('<span class="kicker">GROUP</span><h2>'+esc(g.name)+'</h2><p>'+esc(g.desc)+'</p><div class="count">'+g.members+'</div><span class="muted"> members</span><p class="muted">'+esc(g.rules)+'</p>'+btn(g.joined?"✓ Joined":"＋ Join Group","join:"+g.id)+" "+btn("Open Group","group:"+g.id))).join("")+'</div>';};
function groupPage(){const g=s.groups.find(x=>x.id===q("id"))||s.groups[0];const gp=s.posts.filter(x=>x.groupId===g.id);return '<section class="group-banner"><span class="eyebrow">GROUP</span><h1>'+esc(g.name)+'</h1><p>'+esc(g.desc)+'</p><div class="count">'+g.members+'</div> members · '+(g.joined?"You are a member":"You are not a member")+'</section><div class="layout"><main>'+card('<span class="kicker">GROUP DISCUSSION</span><form data-form="group-post" data-group="'+g.id+'">'+input("text","Start a discussion in "+g.name+"…")+'<button class="btn">Post Discussion</button></form>')+(gp.length?gp.map(post).join(""):empty("No local discussions yet. Start the first one."))+'</main><aside>'+card('<span class="kicker">ABOUT</span><p>'+esc(g.desc)+'</p><hr><b>GROUP RULES</b><p class="muted">'+esc(g.rules)+'</p>'+btn(g.joined?"Leave Group":"Join Group","join:"+g.id))+card('<span class="kicker">GROUP TOOLS</span>'+btn("Group Media","goto:media.html")+btn("Group Events","goto:events.html")+btn("Back to Groups","goto:groups.html"))+'</aside></div>';};
function spacesPage(){return '<section class="hero"><span class="eyebrow">COMMUNITY HUBS</span><h1>CrowSpaces</h1><p>Larger universes containing Groups, CrowRooms and events.</p>'+btn("＋ Create CrowSpace","goto:create-space.html")+'</section><div class="grid">'+s.spaces.map(x=>card('<span class="kicker">CROWSPACE HUB</span><h2>'+esc(x.name)+'</h2><p>'+esc(x.desc)+'</p><p class="muted">'+x.groups+' groups · '+x.rooms+' rooms</p>'+btn("Explore","space:"+x.id))).join("")+'</div>';};
function spacePage(){const x=s.spaces.find(z=>z.id===q("id"))||s.spaces[0];return '<section class="hero"><span class="eyebrow">CROWSPACE HUB</span><h1>'+esc(x.name)+'</h1><p>'+esc(x.desc)+'</p></section><div class="grid">'+card('<h2>Groups</h2><p>'+x.groups+' communities live here.</p>'+btn("Browse Groups","goto:groups.html"))+card('<h2>CrowRooms</h2><p>'+x.rooms+' persistent conversations.</p>'+btn("Open Rooms","goto:rooms.html"))+card('<h2>Events</h2><p>Discover meetups and community activities.</p>'+btn("View Events","goto:events.html"))+'</div>';};
function roomsPage(){return '<section class="hero"><span class="eyebrow">PERSISTENT CONVERSATIONS</span><h1>CrowRooms</h1><p>Topic conversations that stay alive beyond one post.</p></section><div class="grid">'+s.rooms.map(x=>card('<span class="kicker">CROWROOM</span><h2>'+esc(x.name)+'</h2><p>'+esc(x.topic)+'</p><div class="count">'+x.members+'</div><span class="muted"> people talking</span><br><br>'+btn("Enter Room","room:"+x.id))).join("")+'</div>';};
function roomPage(){const x=s.rooms.find(z=>z.id===q("id"))||s.rooms[0];const msgs=(s.roomMessages?.[x.id]||[]);return '<section class="hero"><span class="eyebrow">CROWROOM</span><h1>'+esc(x.name)+'</h1><p>'+esc(x.topic)+' · '+x.members+' members</p></section>'+card('<div class="chat-list">'+msgs.map(m=>'<div class="wall"><b>'+esc(m.from)+'</b><p>'+esc(m.text)+'</p></div>').join("")+'</div><form data-form="room" data-room="'+x.id+'">'+input("text","Say something to the room…")+'<button class="btn">Send to Room</button></form>')};
function friendsPage(){return '<section class="hero"><span class="eyebrow">YOUR PEOPLE</span><h1>Friends & Circles</h1><p>Friends, requests and smaller communities.</p></section>'+card('<span class="kicker">FRIEND REQUESTS</span>'+ (s.friendRequests.filter(x=>x.status==="pending").map(x=>'<div class="request-row"><b>'+esc(x.from)+'</b>'+btn("Accept","friend:accept:"+x.id)+btn("Decline","friend:decline:"+x.id)+'</div>').join("")||empty("No pending requests.")))+'<h2>FRIENDS</h2><div class="grid">'+s.friends.map(f=>card(avatar(f.name,f.avatar)+'<h2>'+esc(f.name)+'</h2><p class="muted">'+esc(f.status)+'</p>'+btn("Message","conversation:"+f.id))).join("")+'</div><h2>CIRCLES</h2>'+circlesPage(true);};
function circlesPage(embed=false){const arr=[["Creators","People building original work"],["Tacoma","Local friends and community"],["Music","Artists, listeners and collaborators"],["Gaming","Players and game-night people"]];const body=arr.map(x=>card('<span class="kicker">CIRCLE</span><h2>'+x[0]+'</h2><p>'+x[1]+'</p>'+btn("Explore","goto:discover.html"))).join("");return embed?'<div class="grid">'+body+"</div>":'<section class="hero"><span class="eyebrow">SMALLER COMMUNITIES</span><h1>CrowCircles</h1></section><div class="grid">'+body+"</div>";};
function discoverPage(){return '<section class="hero"><span class="eyebrow">FIND YOUR PEOPLE</span><h1>Discover</h1><p>Search people, groups, spaces and conversations.</p></section>'+card(input("search","Search CrowSpace…"))+'<div id="discoverResults" class="grid"></div>';};
function discover(qv=""){const el=document.getElementById("discoverResults");if(!el)return;const all=s.groups.map(x=>({n:x.name,d:x.desc,t:"GROUP",url:"group.html?id="+x.id})).concat(s.spaces.map(x=>({n:x.name,d:x.desc,t:"SPACE",url:"space.html?id="+x.id}),s.friends.map(x=>({n:x.name,d:x.status,t:"PERSON",url:"messages.html"})));const rows=all.filter(x=>(x.n+" "+x.d).toLowerCase().includes(qv.toLowerCase()));el.innerHTML=rows.map(x=>card('<span class="kicker">'+x.t+'</span><h2>'+esc(x.n)+'</h2><p>'+esc(x.d)+'</p><a class="btn" href="'+x.url+'">Open</a>')).join("")||empty("No matches.");}
function mailPage(){let active=q("conversation")||"c0",c=s.conversations.find(x=>x.id===active)||s.conversations[0];return '<section class="hero"><span class="eyebrow">CROWMAIL</span><h1>Messages</h1><p>Private, multi-conversation messaging — local demo mode.</p></section><div class="mail-grid"><aside>'+s.conversations.map(x=>'<a class="conversation '+(x.id===c.id?"selected":"")+'" href="messages.html?conversation='+x.id+'">'+avatar(x.with,"")+'<div><b>'+esc(x.with)+'</b><p class="muted">'+(x.online?"● Online":"○ Offline")+'</p></div></a>').join("")+'</aside><main>'+card('<div class="chat-title">'+avatar(c.with,"")+'<div><h2>'+esc(c.with)+'</h2><span class="muted">'+(c.online?"Online":"Offline")+'</span></div></div>')+card('<div class="chat-list">'+c.messages.map(m=>'<div class="bubble '+(m.from==="me"?"mine":"")+'"><b>'+esc(m.from==="me"?s.user.name:m.from)+'</b><p>'+esc(m.text)+'</p><small>'+esc(m.time||"now")+'</small></div>').join("")+'</div><form data-form="conversation" data-conversation="'+c.id+'">'+input("text","Write a message…")+'<button class="btn">Send</button></form>')+'</main></div>';};
function eventsPage(){return '<section class="hero"><span class="eyebrow">COMMUNITY CALENDAR</span><h1>Events</h1><p>Meetups, watch parties, live discussions and hangouts.</p>'+btn("＋ Create Event","goto:create-event.html")+'</section><div class="grid">'+s.events.map(x=>card('<span class="kicker">EVENT</span><h2>'+esc(x.name)+'</h2><p class="muted">'+esc(x.date)+' · '+esc(x.place)+'</p>'+btn("I’m Interested","event:"+x.id))).join("")+'</div>';};
function eventPage(){const e=s.events.find(x=>x.id===q("id"))||s.events[0];return '<section class="hero"><span class="eyebrow">EVENT</span><h1>'+esc(e.name)+'</h1><p>'+esc(e.date)+' · '+esc(e.place)+'</p></section>'+card('<h2>Community Event</h2><p>Meet people, share ideas and build something together.</p>'+btn("I’m Interested","event:"+e.id)+" "+btn("Back to Events","goto:events.html"));};
function mediaPage(p){const filter=p==="photos.html"?"image":p==="videos.html"?"video":"";const m=s.media.filter(x=>!filter||x.type===filter);return '<section class="hero"><span class="eyebrow">MY MEDIA</span><h1>Media Gallery</h1><p>Photo and video memories for your CrowSpace.</p></section>'+card('<form data-form="media">'+input("title","Media title…")+input("url","Image or video URL…")+ '<select class="search" name="type"><option value="image">Photo</option><option value="video">Video</option></select><button class="btn">＋ Add Media</button></form>')+'<div class="media-grid">'+m.map(x=>card(x.type==="image"?'<img class="media-thumb" src="'+esc(x.url)+'" alt="'+esc(x.title)+'"><h3>'+esc(x.title)+'</h3>':'<div class="video-tile">▶ VIDEO</div><h3>'+esc(x.title)+'</h3><a class="btn" href="'+esc(x.url)+'" target="_blank" rel="noopener">Open Video</a>')).join("")+'</div>';};
function notificationsPage(){return '<section class="hero"><span class="eyebrow">ACTIVITY</span><h1>Notifications</h1><p>Friend requests, reactions, comments and community updates.</p></section>'+card(s.notifications.map(n=>'<div class="notification"><span class="notify-dot"></span><div><b>'+esc(n.text)+'</b><p class="muted">'+esc(n.time)+'</p></div></div>').join("")||empty("You are all caught up."));};
function createPostPage(){return '<section class="hero"><span class="eyebrow">CROWBOARD</span><h1>Create Post</h1></section>'+card('<form data-form="post">'+input("text","What do you want to share?")+'<textarea class="search" name="longtext" rows="6" placeholder="Tell your community more…"></textarea><button class="btn">Publish Post</button></form>');};
function createGroupPage(){return '<section class="hero"><span class="eyebrow">COMMUNITY BUILDER</span><h1>Create Group</h1></section>'+card('<form data-form="create-group">'+input("name","Group name")+input("desc","What is this group about?")+input("rules","Group rules")+ '<button class="btn">Create Group</button></form>');};
function createSpacePage(){return '<section class="hero"><span class="eyebrow">HUB BUILDER</span><h1>Create CrowSpace</h1></section>'+card('<form data-form="create-space">'+input("name","CrowSpace name")+input("desc","Describe this community hub")+ '<button class="btn">Create CrowSpace</button></form>');};
function createEventPage(){return '<section class="hero"><span class="eyebrow">COMMUNITY CALENDAR</span><h1>Create Event</h1></section>'+card('<form data-form="create-event">'+input("name","Event name")+input("date","Date and time")+input("place","Location or CrowRoom")+ '<button class="btn">Create Event</button></form>');};
function settingsPage(){return '<section class="hero"><span class="eyebrow">ACCOUNT</span><h1>Settings</h1></section>'+card('<p><b>Local-only account prototype</b></p><p class="muted">No login, Supabase, cloud storage or backend is connected yet.</p>'+btn("Reset Local CrowSpace","reset:all","danger"));};
document.addEventListener("click",e=>{const b=e.target.closest("[data-action]");if(!b)return;const a=b.dataset.action;
if(a.startsWith("goto:"))location.href=a.slice(5);
else if(a.startsWith("react:")){const z=a.split(":"),p=s.posts.find(x=>x.id===z[1]);if(p){p.reactions=p.reactions||{};p.reactions[z[2]]=(p.reactions[z[2]]||0)+1;s.notifications.unshift({id:"n"+Date.now(),text:"You reacted to a CrowBoard post.",time:"Just now"});save();render();}}
else if(a.startsWith("join:")){const g=s.groups.find(x=>x.id===a.slice(5));if(g){g.joined=!g.joined;g.members+=g.joined?1:-1;if(g.joined)s.notifications.unshift({id:"n"+Date.now(),text:"You joined "+g.name+".",time:"Just now"});save();render();}}
else if(a.startsWith("theme:")){document.body.dataset.theme=a.slice(6);localStorage.setItem("crowspace_theme",a.slice(6));}
else if(a.startsWith("message:"))location.href="messages.html";
else if(a.startsWith("conversation:"))location.href="messages.html?conversation="+a.slice(13);
else if(a.startsWith("room:"))location.href="room.html?id="+encodeURIComponent(a.slice(5));
else if(a.startsWith("space:"))location.href="space.html?id="+encodeURIComponent(a.slice(6));
else if(a.startsWith("group:"))location.href="group.html?id="+encodeURIComponent(a.slice(6));
else if(a.startsWith("event:")){const id=a.slice(6);const n=s.events.find(x=>x.id===id);if(n){s.notifications.unshift({id:"n"+Date.now(),text:"You are interested in "+n.name+".",time:"Just now"});save();render();}}
else if(a.startsWith("friend:")){const z=a.split(":"),r=s.friendRequests.find(x=>x.id===z[2]);if(r){if(z[1]==="accept"){s.friends.push({id:"f"+Date.now(),name:r.from,status:"New friend",avatar:""});r.status="accepted";s.notifications.unshift({id:"n"+Date.now(),text:"You are now friends with "+r.from+".",time:"Just now"});}else r.status="declined";save();render();}}
else if(a==="reset:all"){localStorage.removeItem(KEY);location.reload();}
});
document.addEventListener("submit",e=>{const f=e.target;if(!f.dataset.form)return;e.preventDefault();const fd=new FormData(f),text=String(fd.get("text")||"").trim(),type=f.dataset.form;
if(type==="post"){const body=text||String(fd.get("longtext")||"").trim();if(body){s.posts.unshift({id:"p"+Date.now(),author:s.user.name,text:body,comments:[],reactions:{}});s.notifications.unshift({id:"n"+Date.now(),text:"Your post was published.",time:"Just now"});save();location.href="index.html";}}
else if(type==="comment"&&text){const p=s.posts.find(x=>x.id===f.dataset.id);if(p){p.comments.push({author:s.user.name,text});s.notifications.unshift({id:"n"+Date.now(),text:"Someone commented on your post.",time:"Just now"});save();render();}}
else if(type==="group-post"&&text){s.posts.unshift({id:"p"+Date.now(),author:s.user.name,text,groupId:f.dataset.group,comments:[],reactions:{}});save();render();}
else if(type==="wall"&&text){s.notifications.unshift({id:"n"+Date.now(),text:"A new CrowWall message was posted.",time:"Just now"});save();f.reset();render();}
else if(type==="profile"){s.user.name=fd.get("name");s.user.handle=fd.get("handle");s.user.mood=fd.get("mood");s.user.location=fd.get("location");s.user.bio=fd.get("bio");s.user.cover=fd.get("cover");s.user.avatar=fd.get("avatar");s.user.music=fd.get("music");s.user.musicTitle=fd.get("musicTitle");s.user.interests=String(fd.get("interests")||"").split(",").map(x=>x.trim()).filter(Boolean);s.user.sections=[{title:fd.get("sectionTitle"),text:fd.get("sectionText")}];save();location.href="profile.html";}
else if(type==="conversation"&&text){const c=s.conversations.find(x=>x.id===f.dataset.conversation);if(c){c.messages.push({from:"me",text,time:"Just now"});save();render();}}
else if(type==="room"&&text){s.roomMessages=s.roomMessages||{};(s.roomMessages[f.dataset.room] ||= []).push({from:s.user.name,text});save();render();}
else if(type==="media"){const title=String(fd.get("title")||"Untitled").trim(),url=String(fd.get("url")||"").trim();if(url){s.media.unshift({id:"m"+Date.now(),title,url,type:fd.get("type")});save();render();}}
else if(type==="create-group"){const name=String(fd.get("name")||"").trim();if(name){s.groups.push({id:"g"+Date.now(),name,members:1,desc:fd.get("desc"),rules:fd.get("rules"),joined:true,banner:""});save();location.href="groups.html";}}
else if(type==="create-space"){const name=String(fd.get("name")||"").trim();if(name){s.spaces.push({id:"s"+Date.now(),name,desc:fd.get("desc"),groups:0,rooms:0});save();location.href="spaces.html";}}
else if(type==="create-event"){const name=String(fd.get("name")||"").trim();if(name){s.events.push({id:"e"+Date.now(),name,date:fd.get("date"),place:fd.get("place")});save();location.href="events.html";}}
});
document.addEventListener("input",e=>{if(e.target.id==="discoverSearch")discover(e.target.value);if(e.target.name==="search")discover(e.target.value);});
document.addEventListener("DOMContentLoaded",()=>{document.body.dataset.theme=localStorage.getItem("crowspace_theme")||"neon";render();const active=location.pathname.split("/").pop()||"index.html";document.querySelectorAll(".nav a").forEach(a=>{if(a.getAttribute("href")===active)a.classList.add("active")});});
})();