const CS={};CS.client=window.crowSupabase;
CS.escape=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
CS.user=async()=>{if(!CS.client)return null;const {data}=await CS.client.auth.getUser();return data.user||null};
CS.profile=async id=>{const {data}=await CS.client.rpc("crowspace_profile_public",{target:id});return Array.isArray(data)?data[0]||null:data||null};
CS.ensureProfile=async user=>{if(!user)return null;const meta=user.user_metadata||{};const {data}=await CS.client.from("membership_profiles").upsert({id:user.id,display_name:meta.display_name||meta.full_name||user.email?.split("@")[0],username:meta.username||user.email?.split("@")[0],bio:"",updated_at:new Date().toISOString()},{onConflict:"id"}).select().single();return data};
CS.refreshHeader=async()=>{const user=await CS.user();const el=document.getElementById("account");if(!el)return;if(user){const p=await CS.profile(user.id);el.innerHTML='<a href="profile.html">'+CS.escape(p?.display_name||user.email)+'</a> · <a href="notifications.html" id="notificationLink">🔔 <span id="notificationBadge"></span></a> · <button class='linkbtn' id='logoutBtn'>Sign Out</button>";CS.refreshNotificationBadge();document.getElementById("logoutBtn").onclick=async()=>{await CS.client.auth.signOut();location.href="index.html"};}else el.innerHTML='<a href="login.html">Sign In</a>'};
CS.homeFeed=async()=>{const box=document.getElementById("feed");if(!box)return;const u=await CS.user();if(!u){box.innerHTML='<div class="card"><h3>Your Nest starts here.</h3><p>Sign in to build a personalized CrowSpace feed.</p><a class="btn primary" href="login.html">Sign In</a></div>';return}const {data,error}=await CS.client.rpc("crowspace_home_activity",{p_limit:40});if(error){box.innerHTML='<div class="card"><h3>Feed unavailable</h3><p>'+CS.escape(error.message)+'</p></div>';return}const items=data||[];box.innerHTML=items.map(x=>{const label=x.activity_type==="post"?"POST":x.activity_type==="caw"?"CAW":"EVENT";const link=x.activity_type==="post"?"profile.html?id="+encodeURIComponent(x.actor_id):x.target_url;return '<article class="post card"><div class="post-head"><a class="avatar sm" href="profile.html?id='+encodeURIComponent(x.actor_id)+'">'+CS.escape((x.actor_name||"C").slice(0,1).toUpperCase())+'</a><div><strong>'+CS.escape(x.actor_name||"CrowSpace Member")+'</strong><small>@'+CS.escape(x.actor_username||"member")+' · '+new Date(x.created_at).toLocaleString()+'</small></div></div><span class="event-tag">'+label+'</span><h3>'+CS.escape(x.title||"")+'</h3><p>'+CS.escape(x.body||"")+'</p>'+(x.media_url&&x.activity_type==="caw"?'<video controls playsinline preload="metadata" src="'+CS.escape(x.media_url)+'"></video>':"")+'<a class="btn" href="'+CS.escape(link)+'">Open →</a>'+(x.activity_type==="post"?'<div class="post-actions"><button onclick="CS.react(\\''+x.target_id+'\\')">♡ Like</button><button onclick="CS.commentPrompt(\\''+x.target_id+'\\')">💬 Comment</button></div>':"")+'</article>'}).join("")||'<div class="card"><h3>Your feed is quiet.</h3><p>Find people, follow creators, join groups and come back as your CrowSpace grows.</p><a class="btn primary" href="people.html">Find People →</a></div>'};
CS.feed=CS.homeFeed;
CS.react=async postId=>{const u=await CS.user();if(!u){location.href="login.html";return}await CS.client.from("crowspace_reactions").upsert({post_id:postId,user_id:u.id,reaction:"like"});};
CS.commentPrompt=async postId=>{const u=await CS.user();if(!u){location.href="login.html";return}const body=prompt("Comment");if(body)await CS.client.from("crowspace_comments").insert({post_id:postId,user_id:u.id,body});};
CS.follow=async target=>{const u=await CS.user();if(!u){location.href="login.html";return}if(u.id===target)return;const {data}=await CS.client.from("crowspace_follows").select("*").eq("follower_id",u.id).eq("followed_user_id",target).maybeSingle();if(data)await CS.client.from("crowspace_follows").delete().eq("follower_id",u.id).eq("followed_user_id",target);else{await CS.client.from("crowspace_follows").insert({follower_id:u.id,followed_user_id:target});await CS.client.from("crowspace_notifications").insert({user_id:target,actor_id:u.id,type:"follow",body:"Someone followed your Nest."});}};

CS.personCard=(p,extra="")=>'<article class="card"><a class="avatar sm" href="profile.html?id='+encodeURIComponent(p.id)+'">'+CS.escape((p.display_name||p.username||"C").slice(0,1).toUpperCase())+'</a><h3><a href="profile.html?id='+encodeURIComponent(p.id)+'">'+CS.escape(p.display_name||"CrowSpace Member")+'</a></h3><p class="muted">@'+CS.escape(p.username||"member")+'</p>'+extra+'</article>';
CS.discovery=async()=>{const el=document.getElementById("discover");if(!el)return;const u=await CS.user();if(!u){el.innerHTML="";return}const {data,error}=await CS.client.rpc("crowspace_mutual_candidates",{p_limit:6});if(error){el.innerHTML="";return}el.innerHTML=(data||[]).map(p=>CS.personCard(p,'<a class="btn" href="profile.html?id='+encodeURIComponent(p.id)+'">Visit Nest →</a>')).join("")||'<p class="muted">No new people to discover yet.</p>'};
CS.unfriend=async target=>{const u=await CS.user();if(!u)return;const {error}=await CS.client.from("crowspace_friendships").delete().or("requester_id.eq."+u.id+",addressee_id.eq."+u.id).or("requester_id.eq."+target+",addressee_id.eq."+target);if(error)alert(error.message);else location.reload()};
CS.refreshNotificationBadge=async()=>{const user=await CS.user();const b=document.getElementById("notificationBadge");if(!b||!user)return;const {count}=await CS.client.from("crowspace_notifications").select("id",{count:"exact",head:true}).eq("user_id",user.id).is("read_at",null);b.textContent=count?String(count):"";};
CS.startNotificationBadge=()=>{CS.refreshNotificationBadge();if(!CS._badgeTimer)CS._badgeTimer=setInterval(CS.refreshNotificationBadge,30000)};
