/* CrowSpace Live OS — realtime notifications, presence, activity, dashboard, and live message refresh. */
(()=>{const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));let live=null;
function box(){if(document.getElementById('cs-live-os'))return document.getElementById('cs-live-os');const d=document.createElement('aside');d.id='cs-live-os';d.className='cs-live-os';d.innerHTML='<div class="cs-live-head"><b>CROWSPACE LIVE</b><span id="cs-live-dot">● CONNECTING</span></div><div id="cs-live-presence"></div><div id="cs-live-notices"></div>';document.body.appendChild(d);return d}
async function init(){if(!window.cs?.client||!cs.user)return;const b=box();const c=cs.client;
const [{data:notices},{data:activity}]=await Promise.all([c.from('crowspace_notifications').select('*').eq('user_id',cs.user.id).order('created_at',{ascending:false}).limit(5),c.from('crowspace_activity').select('*').eq('user_id',cs.user.id).order('created_at',{ascending:false}).limit(6)]);
renderNotices(notices||[]);renderActivity(activity||[]);
live=c.channel('crowspace-live-'+cs.user.id,{config:{presence:{key:cs.user.id}}});
live.on('presence',{event:'sync'},()=>{const state=live.presenceState();const n=Object.keys(state).length;document.getElementById('cs-live-presence').innerHTML='<span class="live-chip">● '+n+' LIVE IN CROWSPACE</span>'})
.on('postgres_changes',{event:'INSERT',schema:'public',table:'crowspace_notifications',filter:'user_id=eq.'+cs.user.id},p=>{prependNotice(p.new);})
.on('postgres_changes',{event:'INSERT',schema:'public',table:'crowspace_activity',filter:'user_id=eq.'+cs.user.id},p=>{prependActivity(p.new);})
.on('postgres_changes',{event:'INSERT',schema:'public',table:'crowspace_messages',filter:'recipient_id=eq.'+cs.user.id},p=>{window.dispatchEvent(new CustomEvent('crowspace:new-message',{detail:p.new}));toast('NEW MESSAGE',p.new.content||'New CrowSpace message');})
.subscribe(async status=>{const dot=document.getElementById('cs-live-dot');if(dot){dot.textContent=status==='SUBSCRIBED'?'● LIVE':'● '+status;dot.className=status==='SUBSCRIBED'?'live-ok':'live-warn'}if(status==='SUBSCRIBED')await live.track({user_id:cs.user.id,username:cs.profile?.username||'',online_at:new Date().toISOString()})});
if(document.body.dataset.page==='home')await dashboard();
}
function renderNotices(rows){const el=document.getElementById('cs-live-notices');if(!el)return;el.innerHTML='<div class="cs-live-title">NOTIFICATIONS</div>'+(rows.length?rows.map(n=>'<div class="cs-live-item"><b>'+esc(n.type||'SIGNAL')+'</b><span>'+esc(n.message)+'</span></div>').join(''):'<div class="cs-live-empty">No new signals.</div>')}
function prependNotice(n){const el=document.getElementById('cs-live-notices');if(!el)return;const x=document.createElement('div');x.className='cs-live-item is-new';x.innerHTML='<b>'+esc(n.type||'SIGNAL')+'</b><span>'+esc(n.message)+'</span>';el.insertBefore(x,el.children[1]||null);toast('CROWSPACE SIGNAL',n.message)}
function renderActivity(rows){const host=document.querySelector('main.shell');if(!host||document.getElementById('cs-activity-panel'))return;const sec=document.createElement('section');sec.id='cs-activity-panel';sec.className='cs-live-panel';sec.innerHTML='<div class="cs-live-title">MY ACTIVITY STREAM</div><div id="cs-activity-list">'+rows.map(a=>'<div class="cs-activity"><span class="activity-type">'+esc(a.type)+'</span><span>'+esc(a.message)+'</span><time>'+new Date(a.created_at).toLocaleString()+'</time></div>').join('')+'</div>';host.appendChild(sec)}
function prependActivity(a){const list=document.getElementById('cs-activity-list');if(!list)return;const x=document.createElement('div');x.className='cs-activity is-new';x.innerHTML='<span class="activity-type">'+esc(a.type)+'</span><span>'+esc(a.message)+'</span><time>'+new Date(a.created_at).toLocaleString()+'</time>';list.prepend(x)}
async function dashboard(){const host=document.querySelector('main.shell');if(!host||document.getElementById('cs-dashboard'))return;const c=cs.client,u=cs.user.id;const [p,f,r,m]=await Promise.all([c.from('crowspace_posts').select('id',{count:'exact',head:true}).eq('author_id',u),c.from('crowspace_friends').select('requester_id,recipient_id',{count:'exact',head:true}).eq('status','accepted').or('requester_id.eq.'+u+',recipient_id.eq.'+u),c.from('crowspace_reels').select('id,views_count',{count:'exact'}).eq('user_id',u),c.from('crowspace_messages').select('id',{count:'exact',head:true}).eq('recipient_id',u).eq('is_read',false)]);const sec=document.createElement('section');sec.id='cs-dashboard';sec.className='cs-live-dashboard';sec.innerHTML='<div><span>CONTROL CENTER</span><b>UNIFIED CROWSPACE DASHBOARD</b></div><div class="cs-dash-grid"><a href="profile.html"><strong>'+esc(p.count??0)+'</strong><small>POSTS</small></a><a href="friends.html"><strong>'+esc(f.count??0)+'</strong><small>FRIENDS</small></a><a href="reels.html"><strong>'+esc(r.count??0)+'</strong><small>REELS</small></a><a href="messages.html"><strong>'+esc(m.count??0)+'</strong><small>UNREAD</small></a></div></section>';host.insertBefore(sec,host.firstChild)}
function toast(t,m){let x=document.getElementById('cs-toast');if(!x){x=document.createElement('div');x.id='cs-toast';x.className='cs-toast';document.body.appendChild(x)}x.innerHTML='<b>'+esc(t)+'</b><span>'+esc(m)+'</span>';x.classList.add('show');clearTimeout(window.csToastTimer);window.csToastTimer=setTimeout(()=>x.classList.remove('show'),3500)}
window.CrowSpaceLive={init};
window.addEventListener('crowspace:ready',init);if(document.readyState!=='loading')setTimeout(init,0);else document.addEventListener('DOMContentLoaded',()=>setTimeout(init,300));
})();