/* CrowSpace Social Graph 2.0 */
(()=>{let ch;const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));async function init(){if(!window.cs?.client||!cs.user)return;const c=cs.client,u=cs.user.id;
const n=document.createElement('div');n.id='cs-socialbar';n.innerHTML='<a href="dashboard.html">COMMAND</a><a href="members.html">DISCOVER</a><a href="friends.html">FRIENDS</a><a href="messages.html">MESSAGES</a><a href="reels.html">REELS</a><span id="cs-unread">0</span>';document.body.prepend(n);
const {data:notices}=await c.from('crowspace_notifications').select('id,type,message,created_at').eq('user_id',u).eq('is_read',false).order('created_at',{ascending:false}).limit(20);updateUnread(notices?.length||0);
ch=c.channel('cs-social-'+u).on('postgres_changes',{event:'INSERT',schema:'public',table:'crowspace_notifications',filter:'user_id=eq.'+u},p=>{updateUnread((Number(document.getElementById('cs-unread')?.textContent)||0)+1);pulse(p.new.message)}).on('postgres_changes',{event:'INSERT',schema:'public',table:'crowspace_messages',filter:'recipient_id=eq.'+u},p=>{window.dispatchEvent(new CustomEvent('crowspace:new-message',{detail:p.new}));pulse('New message')}).subscribe();
window.CrowSpaceSocial={markAllRead:async()=>{await c.from('crowspace_notifications').update({is_read:true}).eq('user_id',u).eq('is_read',false);updateUnread(0)}};
if(document.body.dataset.page==='messages')messageEnhance(c,u);if(document.body.dataset.page==='profile')profileTimeline(c,u)}
function updateUnread(n){const x=document.getElementById('cs-unread');if(x)x.textContent=n}
function pulse(m){let x=document.getElementById('cs-social-pulse');if(!x){x=document.createElement('div');x.id='cs-social-pulse';document.body.appendChild(x)}x.textContent=esc(m);x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2500)}
async function messageEnhance(c,u){const to=new URLSearchParams(location.search).get('to');if(!to)return;const input=document.querySelector('textarea,input[name="content"]');if(!input)return;const box=document.createElement('div');box.id='cs-typing';box.textContent='';input.parentElement?.appendChild(box);let timer;input.addEventListener('input',()=>{box.textContent='● TYPING…';clearTimeout(timer);timer=setTimeout(()=>box.textContent='',900)});window.addEventListener('crowspace:new-message',e=>{if(e.detail?.sender_id===to)box.textContent='● NEW MESSAGE'});}
async function profileTimeline(c,u){const host=document.querySelector('main.shell');if(!host||document.getElementById('cs-profile-timeline'))return;const {data}=await c.from('crowspace_activity').select('type,message,created_at').eq('user_id',u).order('created_at',{ascending:false}).limit(12);const s=document.createElement('section');s.id='cs-profile-timeline';s.className='cs-live-panel';s.innerHTML='<div class="cs-live-title">PROFILE ACTIVITY TIMELINE</div>'+(data||[]).map(a=>'<div class="cs-activity"><span class="activity-type">'+esc(a.type)+'</span><span>'+esc(a.message)+'</span><time>'+new Date(a.created_at).toLocaleString()+'</time></div>').join('')||'<div class="cs-live-empty">No activity yet.</div>';host.appendChild(s)}
window.addEventListener('crowspace:ready',()=>setTimeout(init,150));document.addEventListener('DOMContentLoaded',()=>setTimeout(init,500));})();