(()=> {
const SUPABASE_URL="https://cevylpnoexugwgygvtgu.supabase.co";
const SUPABASE_KEY="sb_publishable_AdfM5y6RqvF3tbvEVzDZSg_JuGTQLD-";
const DEMO={profiles:[],posts:[],groups:[],spaces:[],rooms:[],events:[],media:[]};
let sb=null,user=null,realtimeChannel=null,realtimeTimer=null;
const app=()=>document.getElementById("app");
const page=()=>location.pathname.split("/").pop()||"index.html";
const q=k=>new URLSearchParams(location.search).get(k);
const esc=v=>String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const card=x=>'<article class="card">'+x+'</article>';
const btn=(label,action)=>'<button class="btn" data-cr-action="'+esc(action)+'">'+esc(label)+'</button>';
const avatar=(name,url)=>url?'<img class="avatar-img" src="'+esc(url)+'" alt="">':'<div class="avatar">'+esc(String(name||"?").slice(0,2).toUpperCase())+'</div>';
const when=x=>x?new Date(x).toLocaleString([],{dateStyle:"medium",timeStyle:"short"}):"";
const shell=(title,sub,body)=>'<div class="wrap"><section class="hero"><span class="eyebrow">CROWSPACE · ONE ACCOUNT · ONE UNIVERSE</span><h1>'+esc(title)+'</h1><p>'+esc(sub||"")+'</p></section>'+body+'<footer class="footer">CrowSpace · A CrowRules Entertainment community universe</footer></div>';
const gate=()=>card('<span class="kicker">ACCOUNT REQUIRED</span><h2>Sign in to continue</h2><p class="muted">Create your universal CrowRules account to use persistent social features.</p><a class="btn" href="auth.html">SIGN IN / CREATE ACCOUNT</a>');
function refreshSoon(){clearTimeout(realtimeTimer);realtimeTimer=setTimeout(()=>render(),180)}
function startRealtime(){
 if(!sb)return;
 if(realtimeChannel)sb.removeChannel(realtimeChannel);
 realtimeChannel=sb.channel("crowspace-live")
 .on("postgres_changes",{event:"*",schema:"public",table:"crowspace_posts"},refreshSoon)
 .on("postgres_changes",{event:"*",schema:"public",table:"crowspace_comments"},refreshSoon)
 .on("postgres_changes",{event:"*",schema:"public",table:"crowspace_post_reactions"},refreshSoon)
 .on("postgres_changes",{event:"*",schema:"public",table:"crowspace_notifications",filter:user?`user_id=eq.${user.id}`:undefined},refreshSoon)
 .on("postgres_changes",{event:"*",schema:"public",table:"crowspace_messages",filter:user?`recipient_id=eq.${user.id}`:undefined},refreshSoon)
 .on("postgres_changes",{event:"*",schema:"public",table:"crowspace_room_messages"},refreshSoon)
 .on("postgres_changes",{event:"*",schema:"public",table:"crowspace_group_threads"},refreshSoon)
 .on("postgres_changes",{event:"*",schema:"public",table:"crowspace_group_members"},refreshSoon)
 .on("postgres_changes",{event:"*",schema:"public",table:"crowspace_event_members"},refreshSoon)
 .on("postgres_changes",{event:"*",schema:"public",table:"crowspace_friends"},refreshSoon)
 .on("postgres_changes",{event:"*",schema:"public",table:"crowspace_follows"},refreshSoon)
 .on("postgres_changes",{event:"*",schema:"public",table:"crowspace_media"},refreshSoon)
 .on("postgres_changes",{event:"*",schema:"public",table:"crowspace_profiles"},refreshSoon)
 .on("postgres_changes",{event:"*",schema:"public",table:"crowspace_discovery_signals",filter:user?`user_id=eq.${user.id}`:undefined},refreshSoon)
 .on("postgres_changes",{event:"*",schema:"public",table:"crowspace_adaptive_feedback",filter:user?`user_id=eq.${user.id}`:undefined},refreshSoon)
 .on("postgres_changes",{event:"*",schema:"public",table:"crowspace_affinity_signals",filter:user?`user_id=eq.${user.id}`:undefined},refreshSoon)
 .subscribe();
}
 if(!window.supabase?.createClient){await new Promise(ok=>{const s=document.createElement("script");s.src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2";s.onload=ok;s.onerror=ok;document.head.appendChild(s)})}
 if(!window.supabase?.createClient){renderError("Supabase could not load.");return}
 sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
 user=(await sb.auth.getUser()).data.user||null;
 if(user) await ensureProfile();
 startRealtime();
 await render();
 sb.auth.onAuthStateChange((_,u)=>{user=u||null;startRealtime();if(u)ensureProfile().then(render);else render()});
}
async function ensureProfile(){
 if(!user)return;
 const r=await sb.from("crowspace_profiles").select("user_id").eq("user_id",user.id).maybeSingle();
 if(!r.data)await sb.from("crowspace_profiles").insert({user_id:user.id,username:(user.email||"member").split("@")[0].replace(/[^a-z0-9_]/gi,""),display_name:user.user_metadata?.display_name||user.user_metadata?.full_name||"CrowSpace Member",profile_visibility:"public"});
}
async function signal(action,targetKind,targetId,weight=1,metadata={}){if(!user||!targetId)return;const base={user_id:user.id,target_id:String(targetId),target_kind:targetKind,action,weight,metadata};try{await sb.from("crowspace_discovery_signals").insert({...base,context_key:page(),context_type:"crowspace"})}catch(e){console.warn("discovery signal",e)}try{await sb.from("crowspace_adaptive_feedback").insert({user_id:user.id,target_kind:targetKind,target_id:String(targetId),action,weight})}catch(e){console.warn("adaptive feedback",e)}try{await sb.from("crowspace_affinity_signals").insert({user_id:user.id,target_kind:targetKind,target_id:String(targetId),signal_type:action,raw_value:1,weight,explanation:"CrowSpace community action",metadata})}catch(e){console.warn("affinity signal",e)}try{await sb.from("crowspace_activity").insert({user_id:user.id,actor_id:user.id,type:action,message:"CrowSpace "+action,reference_id:String(targetId),metadata})}catch(e){console.warn("activity log",e)}}
async function safe(table,query,demo=[]){try{const r=await query;if(r.error){console.error(table,r.error);return []}return Array.isArray(r.data)?r.data:[]}catch(e){console.error(table,e);return []}}
async function profiles(ids){
 if(!ids?.length)return [];
 return safe("crowspace_profiles",sb.from("crowspace_profiles").select("*").in("user_id",ids),DEMO.profiles.filter(x=>ids.includes(x.user_id)));
}
async function feed(){
 const rows=await safe("crowspace_posts",sb.from("crowspace_posts").select("*").eq("status","published").order("created_at",{ascending:false}).limit(60),DEMO.posts);
 const ids=[...new Set(rows.map(x=>x.author_id).filter(Boolean))],people=await profiles(ids);
 let html=user?card('<span class="kicker">CROWFEED</span><form id="crPost"><textarea class="search" name="body" rows="3" placeholder="What is happening in your space?" required></textarea><button class="btn">PUBLISH</button></form>'):gate();
 for(const p of rows){
  const a=people.find(x=>x.user_id===p.author_id);
  html+=card('<div class="post-head">'+avatar(a?.display_name,a?.avatar_url)+'<div><b>'+esc(a?.display_name||"Member")+'</b><div class="muted">'+when(p.created_at)+'</div></div></div><p class="post-copy">'+esc(p.body)+'</p><div class="signal">'+btn("👍 Like","react:"+p.id+":like")+btn("❤️ Love","react:"+p.id+":love")+btn("🔥 Fire","react:"+p.id+":fire")+'</div>');
 }
 app().innerHTML=shell("CrowFeed","Your home stream for people, ideas, projects and community.",html);
}
async function profile(){
 const id=q("id")||user?.id;if(!id){app().innerHTML=shell("My Space","Your CrowSpace profile.",gate());return}
 let u=(await sb.from("crowspace_profiles").select("*").eq("user_id",id).maybeSingle()).data;
 if(!u)u=DEMO.profiles.find(x=>x.user_id===id)||DEMO.profiles[0];
 const posts=await safe("crowspace_posts",sb.from("crowspace_posts").select("*").eq("author_id",id).eq("status","published").order("created_at",{ascending:false}).limit(30),[]);
 const own=user&&user.id===id;
 const actions=own?btn("CUSTOMIZE","goto:customize.html"):user?btn("CROWMAIL","message:"+id)+btn("ADD FRIEND","friend:"+id)+btn("FOLLOW","follow:"+id):"";
 app().innerHTML=shell(u.display_name||"My Space","A personal corner of the CrowSpace universe.",'<section class="profile-cover" style="background-image:linear-gradient(135deg,#111827,#35134b)"><div class="profile-overlay">'+avatar(u.display_name,u.avatar_url)+'<div><span class="eyebrow">PROFILE</span><h1>'+esc(u.display_name||u.username||"Member")+'</h1><p>@'+esc(u.username||"member")+' · '+esc(u.location||"")+'</p></div></div></section><div class="profile-actions">'+actions+'</div><div class="layout profile-layout"><main>'+card('<span class="kicker">ABOUT</span><p>'+esc(u.bio||"This member has not added a bio yet.")+'</p><p class="muted">'+esc(u.interests||"")+'</p>')+card('<span class="kicker">POSTS</span>'+(posts.map(p=>'<div class="wall"><p>'+esc(p.body)+'</p><small class="muted">'+when(p.created_at)+'</small></div>').join("")||'<p class="muted">No posts yet.</p>'))+'</main><aside>'+card('<span class="kicker">SPACE STATS</span><div class="profile-stats"><div><b>128</b><span>Friends</span></div><div><b>12</b><span>Groups</span></div><div><b>342</b><span>Followers</span></div></div>')+card('<span class="kicker">INTERESTS</span><p>'+esc(u.interests||"Film · Music · Tacoma · Creators")+'</p>')+'</aside></div>');
}
async function discover(){
 const people=await safe('crowspace_profiles',sb.from('crowspace_profiles').select('*').eq('profile_visibility','public').limit(100)),groups=await safe('crowspace_groups',sb.from('crowspace_groups').select('*').eq('visibility','public').limit(100)),rooms=await safe('crowspace_rooms',sb.from('crowspace_rooms').select('*').eq('visibility','public').limit(100)),term=(q("q")||"").toLowerCase();
 let signals=[],prefs=[];
 if(user){
  signals=await safe('crowspace_discovery_signals',sb.from('crowspace_discovery_signals').select('target_id,target_kind,action,weight,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(1000),[]);
  prefs=await safe('crowspace_discovery_preferences',sb.from('crowspace_discovery_preferences').select('target_id,action,updated_at').eq('user_id',user.id).limit(500),[]);
 }
 const now=Date.now(),score={};
 const positive={follow:3,friend:5,join_group:5,rsvp:4,react:2,message:2,engagement:2,post:3,comment:3};
 const negative={dismiss:-7,not_interested:-12};
 for(const s of signals){
  const age=Math.max(0,(now-new Date(s.created_at||now).getTime())/86400000),decay=Math.max(.15,Math.exp(-age/21)),base=positive[s.action]??negative[s.action]??Number(s.weight||1);
  const k=s.target_kind+":"+s.target_id; score[k]=(score[k]||0)+base*decay;
 }
 for(const p of prefs){
  const k="profile:"+p.target_id; if(p.action==="not_interested")score[k]=-9999;
  if(p.action==="dismiss")score[k]=Math.min(score[k]||0,-5);
 }
 const rank=(arr,kind,idKey)=>arr.slice().map(x=>({...x,_score:score[kind+":"+x[idKey]]||0})).sort((a,b)=>b._score-a._score);
 const rankedPeople=rank(people,'profile','user_id'),rankedGroups=rank(groups,'group','id'),rankedRooms=rank(rooms,'room','id');
 const ps=rankedPeople.filter(x=>(x.display_name+" "+x.username+" "+x.bio+" "+x.interests).toLowerCase().includes(term)&&x._score>-9990);
 let html='<div class="community-tabs"><a href="discover.html">ALL</a><a href="discover.html?q=film">FILM</a><a href="discover.html?q=music">MUSIC</a><a href="discover.html?q=tacoma">TACOMA</a><a href="discover.html?q=creator">CREATORS</a></div>';
 html+=card('<span class="kicker">ADAPTIVE DISCOVERY</span><h2>Built from your CrowSpace activity</h2><p class="muted">Recent interactions carry more weight, while dismissals and “not interested” feedback reduce repeat recommendations.</p>');
 html+=ps.map(x=>card(avatar(x.display_name,x.avatar_url)+'<span class="kicker">PERSON</span><h2>'+esc(x.display_name)+'</h2><p>'+esc(x.bio)+'</p><p class="muted">'+esc(x.interests)+'</p><div class="signal">'+btn("NOT INTERESTED","feedback:profile:"+x.user_id+":not_interested")+btn("DISMISS","feedback:profile:"+x.user_id+":dismiss")+'</div><a class="btn" href="profile.html?id='+x.user_id+'">VIEW PROFILE</a>')).join("");
 html+=rankedGroups.filter(x=>x._score>-9990&&(!term||((x.name+" "+x.description).toLowerCase().includes(term)))).map(x=>card('<span class="kicker">GROUP</span><h2>'+esc(x.name)+'</h2><p>'+esc(x.description)+'</p><p class="muted">'+Number(x.members||x.member_count||0).toLocaleString()+' members</p><div class="signal">'+btn("NOT INTERESTED","feedback:group:"+x.id+":not_interested")+btn("DISMISS","feedback:group:"+x.id+":dismiss")+'</div><a class="btn" href="group.html?id='+esc(x.slug)+'">OPEN GROUP</a>')).join("");
 html+=rankedRooms.filter(x=>x._score>-9990&&(!term||((x.name+" "+x.topic).toLowerCase().includes(term)))).map(x=>card('<span class="kicker">CROWROOM</span><h2>'+esc(x.name)+'</h2><p>'+esc(x.topic)+'</p><div class="signal">'+btn("NOT INTERESTED","feedback:room:"+x.id+":not_interested")+btn("DISMISS","feedback:room:"+x.id+":dismiss")+'</div><a class="btn" href="room.html?id='+x.slug+'">ENTER ROOM</a>')).join("");
 app().innerHTML=shell("Discover","Your CrowSpace recommendations adapt to recent activity and feedback.",html);
}
async function groups(){let rows=await safe('crowspace_groups',sb.from('crowspace_groups').select('*').eq('visibility','public').order('created_at',{ascending:false}),[]);app().innerHTML=shell("Groups","Find communities built around shared interests.",'<div class="grid">'+rows.map(g=>card('<span class="kicker">GROUP</span><h2>'+esc(g.name)+'</h2><p>'+esc(g.description||"")+'</p><div class="community-counts"><span>'+Number(g.member_count||g.members||0).toLocaleString()+' members</span><span>Public</span></div><a class="btn" href="group.html?id='+esc(g.slug)+'">OPEN GROUP</a>'+(user?" "+btn("JOIN","join:"+g.id):""))).join("")+'</div>'+card('<a class="btn" href="create-group.html">CREATE A GROUP</a> <a class="btn" href="create-space.html">CREATE A CROWSPACE</a>'))}
async function group(){const slug=q("id")||"tacoma-creatives";let g=DEMO.groups.find(x=>x.slug===slug);try{g=(await sb.from("crowspace_groups").select("*").eq("slug",slug).maybeSingle()).data||g}catch(_){}if(!g){app().innerHTML=shell("Group","Not found.",card("<p>That group could not be found.</p>"));return}let threads=[];try{threads=(await sb.from("crowspace_group_threads").select("*").eq("group_id",g.id).order("created_at",{ascending:false}).limit(30)).data||[]}catch(_){}let html=user?card('<span class="kicker">START A DISCUSSION</span><form id="crThread"><input class="search" name="title" placeholder="Discussion title" required><textarea class="search" name="body" rows="3" placeholder="Start the conversation…" required></textarea><button class="btn">CREATE DISCUSSION</button></form>'):"";html+=card('<span class="kicker">COMMUNITY</span><p>'+esc(g.description||"")+'</p><p class="muted">Community rules: Be constructive. Credit creators. Build each other up.</p>');if(threads.length)for(const t of threads)html+=card('<span class="kicker">THREAD</span><h3>'+esc(t.title)+'</h3><p>'+esc(t.body)+'</p><small class="muted">'+when(t.created_at)+'</small>');else html+=card('<span class="kicker">DISCUSSION STARTERS</span><h3>What are you building?</h3><p>Share a project, ask for collaborators, or start a conversation.</p>');app().innerHTML=shell(g.name,"A persistent CrowSpace community.",html)}
async function spaces(){let rows=await safe('crowspace_spaces',sb.from('crowspace_spaces').select('*').eq('visibility','public').order('name'),[]);app().innerHTML=shell("CrowSpaces","Community hubs that connect groups, rooms and people.",'<div class="grid">'+rows.map(s=>card('<span class="kicker">HUB</span><h2>'+esc(s.name)+'</h2><p>'+esc(s.description||"")+'</p><div class="community-counts"><span>'+Number(s.groups||0)+' groups</span><span>'+Number(s.rooms||0)+' rooms</span></div><a class="btn" href="space.html?id='+esc(s.slug)+'">OPEN CROWSPACE</a>')).join("")+'</div>'+card('<a class="btn" href="create-space.html">CREATE A CROWSPACE</a>'))}
async function space(){const slug=q('id')||'';let s=null;try{s=(await sb.from('crowspace_spaces').select('*').eq('slug',slug).maybeSingle()).data}catch(_){}if(!s){app().innerHTML=shell("CrowSpace","Not found.",card("<p>That CrowSpace could not be found.</p>"));return}app().innerHTML=shell(s.name,s.description||"",card('<span class="kicker">COMMUNITY HUB</span><div class="community-counts"><span>'+s.groups+' groups</span><span>'+s.rooms+' CrowRooms</span></div><p>Explore the communities inside this hub.</p><a class="btn" href="groups.html">EXPLORE GROUPS</a> <a class="btn" href="rooms.html">CROWROOMS</a>'))}
async function rooms(){let rows=await safe('crowspace_rooms',sb.from('crowspace_rooms').select('*').eq('visibility','public').order('created_at'),[]);app().innerHTML=shell("CrowRooms","Live community conversations inside CrowSpace.",'<div class="grid">'+rows.map(r=>card('<span class="kicker">CROWROOM</span><h2>'+esc(r.name)+'</h2><p>'+esc(r.topic||"")+'</p><p class="muted">'+Number(r.member_count||r.members||0)+' members</p><a class="btn" href="room.html?id='+esc(r.slug)+'">ENTER ROOM</a>')).join("")+'</div>')}
async function room(){const slug=q('id')||'';let r=null;try{r=(await sb.from('crowspace_rooms').select('*').eq('slug',slug).maybeSingle()).data}catch(_){}let msgs=[];try{msgs=(await sb.from("crowspace_room_messages").select("*").eq("room_id",r.id).order("created_at",{ascending:false}).limit(40)).data||[]}catch(_){}if(!r){app().innerHTML=shell("CrowRoom","Not found.",card("<p>That CrowRoom could not be found.</p>"));return}const body=card('<span class="kicker">ROOM TOPIC</span><p>'+esc(r.topic)+'</p>')+(msgs.length?msgs.map(m=>card('<p>'+esc(m.content||m.body)+'</p><small class="muted">'+when(m.created_at)+'</small>')).join(""):card('<span class="kicker">WELCOME</span><h3>Start the conversation</h3><p>This CrowRoom is ready for members to share ideas and connect.</p>'))+(user?card('<form id="crRoomMessage"><input class="search" name="body" placeholder="Say something…" required><button class="btn">POST TO ROOM</button></form>'):gate());app().innerHTML=shell(r.name,"A live conversation room.",body)}
async function events(){let rows=await safe('crowspace_events',sb.from('crowspace_events').select('*').eq('visibility','public').order('starts_at'),[]);app().innerHTML=shell("Events","Meetups, live shows, community gatherings and creator events.",'<div class="grid">'+rows.map(e=>card('<span class="kicker">EVENT</span><h2>'+esc(e?.title||"Event")+'</h2><p>'+esc(e.description||"")+'</p><p class="muted">'+when(e?.starts_at)+' · '+esc(e.location||"")+'</p>'+btn("VIEW EVENT","event:"+e.slug)+(user?" "+btn("I’M INTERESTED","rsvp:"+e?.id):""))).join("")+'</div>'+card('<a class="btn" href="create-event.html">CREATE EVENT</a>'))}
async function event(){const slug=q('id')||'';let e=null;try{e=(await sb.from('crowspace_events').select('*').eq('slug',slug).maybeSingle()).data}catch(_){}app().innerHTML=shell(e?e.title:"Event",e?.description||"Event not found.",card('<span class="kicker">EVENT DETAILS</span><h2>'+esc(e.title)+'</h2><p>'+esc(e?.description||"")+'</p><p><b>'+when(e.starts_at)+'</b></p><p>'+esc(e?.location||"")+'</p>'+(user?btn("I’M INTERESTED","rsvp:"+e.id):gate())))}
async function media(){let rows=await safe('crowspace_media',sb.from('crowspace_media').select('*').eq('visibility','public').order('created_at',{ascending:false}).limit(60),[]);app().innerHTML=shell("Media","Photos, videos and creative media from the CrowSpace community.",(user?card('<form id="crMedia"><input class="search" name="title" placeholder="Title"><input class="search" name="url" placeholder="Media URL" required><select class="search" name="type"><option value="image">Photo</option><option value="video">Video</option><option value="audio">Audio</option></select><button class="btn">ADD MEDIA</button></form>'):gate())+'<div class="media-grid">'+rows.map(m=>m.media_type==="image"?card('<img class="media-thumb" src="'+esc(m.media_url)+'" alt="'+esc(m.title||"")+'"><h3>'+esc(m.title||"Untitled")+'</h3><p class="muted">'+esc(m.description||"")+'</p>'):card('<span class="kicker">'+esc(String(m.media_type||"MEDIA").toUpperCase())+'</span><h3>'+esc(m.title||"Media")+'</h3><p>'+esc(m.description||"")+'</p><a class="btn" href="'+esc(m.media_url)+'" target="_blank" rel="noopener">OPEN MEDIA</a>')).join("")+'</div>')}
async function photos(){await media()} async function videos(){await media()}
async function notifications(){if(!user){app().innerHTML=shell("Notifications","Your activity inbox.",gate());return}const rows=await safe("crowspace_notifications",sb.from("crowspace_notifications").select("*").eq("user_id",user.id).order("created_at",{ascending:false}).limit(100),[]);app().innerHTML=shell("Notifications","Your CrowSpace activity inbox.",card(btn("MARK ALL READ","readall"))+(rows.map(n=>'<div class="notification"><span class="notify-dot"></span><div><b>'+esc(n.message||n.type||"Notification")+'</b><p class="muted">'+when(n.created_at)+'</p></div></div>').join("")||'<p class="muted">You are all caught up.</p>'))}
async function friends(){if(!user){app().innerHTML=shell("Friends","Your social graph.",gate());return}let rows=[];try{rows=(await sb.from("crowspace_friends").select("*").or("requester_id.eq."+user.id+",recipient_id.eq."+user.id).order("created_at",{ascending:false})).data||[]}catch(_){}const people=await profiles([...new Set(rows.flatMap(x=>[x.requester_id,x.recipient_id]).filter(x=>x!==user.id))]);const html=rows.map(r=>{const id=r.requester_id===user.id?r.recipient_id:r.requester_id,p=people.find(x=>x.user_id===id);return '<div class="person-row">'+avatar(p?.display_name,p?.avatar_url)+'<div><a href="profile.html?id='+id+'"><b>'+esc(p?.display_name||"Member")+'</b></a><p class="muted">'+esc(r.status||"connected")+'</p></div></div>'}).join("");app().innerHTML=shell("Friends & Connections","People connected to your CrowSpace.",card(html||'<p class="muted">No connections yet. Use Discover to find people.</p>'))}
async function messages(){if(!user){app().innerHTML=shell("CrowMail","Private conversations.",gate());return}let rows=[];try{rows=(await sb.from("crowspace_messages").select("*").or("sender_id.eq."+user.id+",recipient_id.eq."+user.id).order("created_at",{ascending:false}).limit(100)).data||[]}catch(_){}app().innerHTML=shell("CrowMail","Private conversations across the CrowSpace universe.",card('<span class="kicker">MESSAGES</span>'+(rows.map(m=>'<div class="wall"><p>'+esc(m.body||m.content||"")+'</p><small class="muted">'+when(m.created_at)+'</small></div>').join("")||'<p class="muted">No messages yet. Visit a member profile to start a conversation.</p>')))}
async function activity(){if(!user){app().innerHTML=shell("Activity","Your social activity.",gate());return}let rows=[];try{rows=(await sb.from("crowspace_activity").select("*").eq("actor_id",user.id).order("created_at",{ascending:false}).limit(100)).data||[]}catch(_){}app().innerHTML=shell("Activity","A timeline of your CrowSpace actions.",card((rows.map(x=>'<div class="notification"><b>'+esc(x.type||"Activity")+'</b><p>'+esc(x.message||x.content||"")+'</p><small class="muted">'+when(x.created_at)+'</small></div>').join("")||'<p class="muted">No activity yet.</p>')))}
async function graph(){app().innerHTML=shell("My Graph","Explore your people, communities and connections.",card('<div class="grid"><div><span class="kicker">PEOPLE</span><h2>3</h2><p class="muted">Suggested connections</p></div><div><span class="kicker">GROUPS</span><h2>4</h2><p class="muted">Featured communities</p></div><div><span class="kicker">ROOMS</span><h2>3</h2><p class="muted">Live conversations</p></div></div>')+card('<a class="btn" href="discover.html">DISCOVER CONNECTIONS</a> <a class="btn" href="friends.html">MY FRIENDS</a>'))}
async function auth(){app().innerHTML=shell("CrowSpace Account","One account. One universe.",card('<div id="authStatus" class="notice"></div><div class="grid"><form id="uSignIn"><span class="kicker">SIGN IN</span><input class="search" type="email" name="email" placeholder="Email" required><input class="search" type="password" name="password" placeholder="Password" required><button class="btn">SIGN IN</button></form><form id="uSignUp"><span class="kicker">CREATE ACCOUNT</span><input class="search" type="email" name="email" placeholder="Email" required><input class="search" type="password" name="password" placeholder="Password" minlength="8" required><input class="search" name="display_name" placeholder="Display name"><button class="btn">CREATE ACCOUNT</button></form></div>')+card('<span class="kicker">ACCOUNT STATUS</span><p>'+(user?"Signed in as "+esc(user.email||"member"):"Not signed in")+'</p>'+(user?btn("SIGN OUT","signout"):"")))}
async function customize(){if(!user){app().innerHTML=shell("Customize My Space","Personalize your profile.",gate());return}const u=(await sb.from("crowspace_profiles").select("*").eq("user_id",user.id).maybeSingle()).data||{};app().innerHTML=shell("Customize My Space","Update the profile connected to your universal account.",card('<form id="crProfile"><label>Display name</label><input class="search" name="display_name" value="'+esc(u.display_name||"")+'"><label>Username</label><input class="search" name="username" value="'+esc(u.username||"")+'"><label>Bio</label><textarea class="search" name="bio" rows="5">'+esc(u.bio||"")+'</textarea><label>Location</label><input class="search" name="location" value="'+esc(u.location||"")+'"><label>Avatar URL</label><input class="search" name="avatar_url" value="'+esc(u.avatar_url||"")+'"><label>Banner URL</label><input class="search" name="banner_url" value="'+esc(u.banner_url||"")+'"><label>Interests</label><input class="search" name="interests" value="'+esc(u.interests||"")+'"><button class="btn">SAVE MY SPACE</button></form>'))}
async function settings(){await customize()}
async function createPost(){app().innerHTML=shell("Create Post","Publish to CrowFeed.",user?card('<form id="crPostFull"><textarea class="search" name="body" rows="7" placeholder="Tell your community more…" required></textarea><button class="btn">PUBLISH POST</button></form>'):gate())}
async function createEvent(){app().innerHTML=shell("Create Event","Add a community gathering.",user?card('<form id="crEvent"><input class="search" name="title" placeholder="Event name" required><textarea class="search" name="description" rows="4" placeholder="Description"></textarea><input class="search" name="starts_at" type="datetime-local" required><input class="search" name="location" placeholder="Location or CrowRoom"><button class="btn">CREATE EVENT</button></form>'):gate())}
async function createGroup(){app().innerHTML=shell("Create Group","Build a persistent community.",user?card('<form id="crGroup"><input class="search" name="name" placeholder="Group name" required><input class="search" name="slug" placeholder="group-slug" required><textarea class="search" name="description" rows="4" placeholder="Description"></textarea><button class="btn">CREATE GROUP</button></form>'):gate())}
async function createSpace(){app().innerHTML=shell("Create CrowSpace","Build a community hub.",user?card('<form id="crSpace"><input class="search" name="name" placeholder="CrowSpace name" required><input class="search" name="slug" placeholder="hub-slug" required><textarea class="search" name="description" rows="4" placeholder="Description"></textarea><button class="btn">CREATE CROWSPACE</button></form>'):gate())}
async function submit(e){
 const f=e.target;if(!sb)return;
 if(f.id==="uSignIn"||f.id==="uSignUp"){e.preventDefault();const d=new FormData(f),email=String(d.get("email")),password=String(d.get("password"));const r=f.id==="uSignIn"?await sb.auth.signInWithPassword({email,password}):await sb.auth.signUp({email,password,options:{data:{display_name:String(d.get("display_name")||"")}}});document.getElementById("authStatus").textContent=r.error?r.error.message:(f.id==="uSignUp"?"Account created. Check your email if confirmation is enabled.":"Signed in.");if(!r.error)setTimeout(()=>location.href="profile.html",700);return}
 if(f.id==="crPost"||f.id==="crPostFull"){e.preventDefault();const body=String(new FormData(f).get("body")).trim();const r=await sb.from("crowspace_posts").insert({author_id:user.id,body,visibility:"public",status:"published"});if(r.error)alert(r.error.message);else {await signal("post","post",r.data?.[0]?.id||null,3);feed()}return}
 if(f.id==="crProfile"){e.preventDefault();const d=new FormData(f),r=await sb.from("crowspace_profiles").update({display_name:String(d.get("display_name")).trim(),username:String(d.get("username")).trim(),bio:String(d.get("bio")).trim(),location:String(d.get("location")).trim(),avatar_url:String(d.get("avatar_url")).trim(),banner_url:String(d.get("banner_url")).trim(),interests:String(d.get("interests")).trim(),updated_at:new Date().toISOString()}).eq("user_id",user.id);if(r.error)alert(r.error.message);else profile();return}
 if(f.id==="crMedia"){e.preventDefault();const d=new FormData(f),r=await sb.from("crowspace_media").insert({user_id:user.id,title:String(d.get("title")).trim(),media_url:String(d.get("url")).trim(),media_type:String(d.get("type")),visibility:"public"});if(r.error)alert(r.error.message);else media();return}
 if(f.id==="crEvent"){e.preventDefault();const d=new FormData(f),r=await sb.from("crowspace_events").insert({owner_id:user.id,title:String(d.get("title")).trim(),description:String(d.get("description")).trim(),starts_at:new Date(String(d.get("starts_at"))).toISOString(),location:String(d.get("location")).trim(),visibility:"public"});if(r.error)alert(r.error.message);else events();return}
 if(f.id==="crGroup"){e.preventDefault();const d=new FormData(f),r=await sb.from("crowspace_groups").insert({name:String(d.get("name")).trim(),slug:String(d.get("slug")).trim(),description:String(d.get("description")).trim(),owner_id:user.id,visibility:"public",status:"active"}).select().single();if(r.error){alert(r.error.message)}else location.href="group.html?id="+r.data.slug;return}
 if(f.id==="crSpace"){e.preventDefault();const d=new FormData(f),r=await sb.from("crowspace_spaces").insert({name:String(d.get("name")).trim(),slug:String(d.get("slug")).trim(),description:String(d.get("description")).trim(),created_by:user.id,visibility:"public"});if(r.error)alert(r.error.message);else spaces();return}
 if(f.id==="crThread"){e.preventDefault();const d=new FormData(f),g=(await sb.from("crowspace_groups").select("id").eq("slug",q("id")||"tacoma-creatives").single()).data;if(!g){alert("Group not found");return}const r=await sb.from("crowspace_group_threads").insert({group_id:g.id,author_id:user.id,title:String(d.get("title")).trim(),body:String(d.get("body")).trim()});if(r.error)alert(r.error.message);else {await signal("join_group","group",id,4);group()}return}
 if(f.id==="crRoomMessage"){e.preventDefault();const d=new FormData(f),r=await sb.from("crowspace_room_messages").insert({room_id:(await sb.from("crowspace_rooms").select("id").eq("slug",q("id")).single()).data?.id,sender_id:user.id,body:String(d.get("body")).trim()});if(r.error)alert(r.error.message);else {await signal("message","room",q("id"),2);room()}return}
}
async function act(a){
 if(a==="signout"){await sb.auth.signOut();location.href="auth.html";return}
 if(a.startsWith("goto:")){location.href=a.slice(5);return}
 if(a.startsWith("feedback:")){const p=a.split(":");if(user){const kind=p[1],id=p[2],action=p[3];await sb.from("crowspace_discovery_preferences").upsert({user_id:user.id,target_id:id,action},{onConflict:"user_id,target_id"});await signal(action,kind,id,action==="not_interested"?-12:-7);discover()}return}
if(a.startsWith("message:")){if(user)await signal("message","profile",a.slice(8),2);location.href="messages.html?user="+a.slice(8);return}
 if(a.startsWith("friend:")){if(!user){location.href="auth.html";return}const r=await sb.from("crowspace_friends").insert({requester_id:user.id,recipient_id:a.slice(7),status:"pending"});if(r.error&&r.error.code!=="23505")alert(r.error.message);else {if(!r.error)await signal("friend","profile",a.slice(7),5);profile()}return}
 if(a.startsWith("follow:")){if(!user){location.href="auth.html";return}const id=a.slice(7),x=(await sb.from("crowspace_follows").select("*").eq("follower_id",user.id).eq("following_id",id).maybeSingle()).data;if(x)await sb.from("crowspace_follows").delete().eq("follower_id",user.id).eq("following_id",id);else {await sb.from("crowspace_follows").insert({follower_id:user.id,following_id:id});await signal("follow","profile",id,3)}profile();return}
 if(a.startsWith("join:")){if(!user){location.href="auth.html";return}const id=a.slice(5);const r=await sb.from("crowspace_group_members").upsert({group_id:id,user_id:user.id,role:"member",status:"active"},{onConflict:"group_id,user_id"});if(r.error)alert(r.error.message);else {await signal("engagement","group",g.id,2);group()}return}
 if(a.startsWith("accept:")){if(user)await sb.from("crowspace_friends").update({status:"accepted",updated_at:new Date().toISOString()}).eq("id",a.slice(7)).eq("recipient_id",user.id);friends();return}
 if(a.startsWith("react:")){if(!user){location.href="auth.html";return}const z=a.split(":"),pid=z[1],reaction=z[2],x=(await sb.from("crowspace_post_reactions").select("*").eq("post_id",pid).eq("user_id",user.id).eq("reaction",reaction).maybeSingle()).data;if(x)await sb.from("crowspace_post_reactions").delete().eq("post_id",pid).eq("user_id",user.id).eq("reaction",reaction);else {await sb.from("crowspace_post_reactions").insert({post_id:pid,user_id:user.id,reaction});await signal("react","post",pid,2,{reaction})}feed();return}
 if(a.startsWith("rsvp:")){if(!user){location.href="auth.html";return}const id=a.slice(5);const x=(await sb.from("crowspace_event_members").select("*").eq("event_id",id).eq("user_id",user.id).maybeSingle()).data;if(x)await sb.from("crowspace_event_members").delete().eq("event_id",id).eq("user_id",user.id);else {await sb.from("crowspace_event_members").insert({event_id:id,user_id:user.id,status:"going"});await signal("rsvp","event",id,4)}events();return}
 if(a.startsWith("event:")){location.href="event.html?id="+a.slice(6);return}
 if(a==="readall"&&user){await sb.from("crowspace_notifications").update({is_read:true}).eq("user_id",user.id);notifications()}
}
function renderError(msg){app().innerHTML=shell("CrowSpace","Connection status",card('<p>'+esc(msg)+'</p>'))}
async function render(){
 const map={"index.html":feed,"profile.html":profile,"discover.html":discover,"friends.html":friends,"circles.html":discover,"groups.html":groups,"group.html":group,"spaces.html":spaces,"space.html":space,"rooms.html":rooms,"room.html":room,"events.html":events,"event.html":event,"media.html":media,"photos.html":photos,"videos.html":videos,"messages.html":messages,"crowmail.html":messages,"notifications.html":notifications,"activity.html":activity,"graph.html":graph,"auth.html":auth,"customize.html":customize,"settings.html":settings,"create-post.html":createPost,"create-group.html":createGroup,"create-space.html":createSpace,"create-event.html":createEvent};
 const fn=map[page()];if(fn)await fn();else await feed();
}
document.addEventListener("submit",submit);
document.addEventListener("click",e=>{const b=e.target.closest("[data-cr-action]");if(b)act(b.dataset.crAction)});
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
})();