(()=> {
const URL="https://cevylpnoexugwgygvtgu.supabase.co";
const KEY="sb_publishable_AdfM5y6RqvF3tbvEVzDZSg_JuGTQLD-";
let sb=null,user=null,done=false;
const app=()=>document.getElementById("app");
const page=()=>location.pathname.split("/").pop()||"index.html";
const q=k=>new URLSearchParams(location.search).get(k);
const esc=v=>String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const card=x=>'<article class="card">'+x+"</article>";
const btn=(t,a)=>'<button class="btn" data-universal-action="'+esc(a)+'">'+esc(t)+"</button>";
const shell=(title,sub,body)=>'<div class="wrap"><section class="hero"><span class="eyebrow">CROWSPACE · UNIVERSAL LAYER</span><h1>'+esc(title)+'</h1><p>'+esc(sub||"")+'</p></section>'+body+"</div>";
const loadClient=async()=>{if(window.supabase?.createClient)return window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});await new Promise(ok=>{const s=document.createElement("script");s.src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2";s.onload=ok;s.onerror=ok;document.head.appendChild(s)});return window.supabase?.createClient?window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}):null};
const gate=()=>card('<span class="kicker">ACCOUNT</span><h2>Sign in to continue</h2><p class="muted">CrowSpace uses your Supabase account for persistent social features.</p><a class="btn" href="auth.html">SIGN IN / CREATE ACCOUNT</a>');
async function counts(){const names=["crowspace_profiles","crowspace_posts","crowspace_groups","crowspace_rooms","crowspace_events","crowspace_media"];const out={};await Promise.all(names.map(async n=>{try{const r=await sb.from(n).select("id",{count:"exact",head:true});out[n]=r.count||0}catch(_){out[n]=0}}));return out}
async function auth(){let status="";app().innerHTML=shell("CrowSpace Account","One account. One universe.",card('<div id="authStatus" class="notice"></div><div class="grid"><form id="uSignIn"><span class="kicker">SIGN IN</span><input class="search" type="email" name="email" placeholder="Email" required><input class="search" type="password" name="password" placeholder="Password" required><button class="btn">SIGN IN</button></form><form id="uSignUp"><span class="kicker">CREATE ACCOUNT</span><input class="search" type="email" name="email" placeholder="Email" required><input class="search" type="password" name="password" placeholder="Password" minlength="8" required><input class="search" name="display_name" placeholder="Display name"><button class="btn">CREATE ACCOUNT</button></form></div>')+card('<span class="kicker">ACCOUNT STATUS</span><p id="accountState">Checking session…</p>'));
const state=document.getElementById("accountState");const session=(await sb.auth.getSession()).data.session;state.textContent=session?"Signed in as "+(session.user.email||"member"):"Not signed in";if(session)document.getElementById("authStatus").innerHTML=btn("SIGN OUT","signout")+" "+'<a class="btn" href="profile.html">MY SPACE</a>';
}
async function settings(){if(!user){app().innerHTML=shell("Settings","Manage your CrowSpace account.",gate());return}const p=(await sb.from("crowspace_profiles").select("*").eq("user_id",user.id).maybeSingle()).data||{};app().innerHTML=shell("Settings","Your account and profile settings.",card('<form id="uSettings"><input class="search" name="display_name" value="'+esc(p.display_name||"")+'" placeholder="Display name"><input class="search" name="username" value="'+esc(p.username||"")+'" placeholder="Username"><textarea class="search" name="bio" rows="5" placeholder="Bio">'+esc(p.bio||"")+'</textarea><input class="search" name="location" value="'+esc(p.location||"")+'" placeholder="Location"><input class="search" name="avatar_url" value="'+esc(p.avatar_url||"")+'" placeholder="Avatar URL"><input class="search" name="banner_url" value="'+esc(p.banner_url||"")+'" placeholder="Banner URL"><button class="btn">SAVE SETTINGS</button></form>'))}
async function messages(){if(!user){app().innerHTML=shell("CrowMail","Private conversations.",gate());return}const rows=(await sb.from("crowspace_messages").select("*").or("sender_id.eq."+user.id+",recipient_id.eq."+user.id).order("created_at",{ascending:false}).limit(100)).data||[];const ids=[...new Set(rows.flatMap(x=>[x.sender_id,x.recipient_id]).filter(x=>x&&x!==user.id))];const people=ids.length?(await sb.from("crowspace_profiles").select("user_id,display_name,username").in("user_id",ids)).data||[]:[];const html=rows.map(m=>{const id=m.sender_id===user.id?m.recipient_id:m.sender_id,p=people.find(x=>x.user_id===id);return '<div class="wall"><b>'+esc(p?.display_name||p?.username||"Member")+'</b><p>'+esc(m.body||m.content||"")+'</p><small class="muted">'+esc(m.created_at||"")+'</small></div>'}).join("")||'<p class="muted">No messages yet.</p>';app().innerHTML=shell("CrowMail","Private conversations in your CrowSpace.",card(html))}
async function simpleTable(table,title,sub,labelField,bodyField){const r=await sb.from(table).select("*").order("created_at",{ascending:false}).limit(50);const rows=r.data||[];app().innerHTML=shell(title,sub,'<div class="grid">'+(rows.map(x=>card('<span class="kicker">'+esc(title).toUpperCase()+'</span><h2>'+esc(x[labelField]||x.name||x.title||"Untitled")+'</h2><p>'+esc(x[bodyField]||x.description||x.topic||"")+'</p><p class="muted">'+esc(x.slug||x.location||"")+'</p>')).join("")||card('<p class="muted">Nothing here yet.</p>'))+'</div>')}
async function graph(){const c=await counts();app().innerHTML=shell("My Graph","Your CrowSpace relationship and community intelligence workspace.",card('<div class="grid"><div><span class="kicker">PROFILES</span><h2>'+c.crowspace_profiles+'</h2></div><div><span class="kicker">GROUPS</span><h2>'+c.crowspace_groups+'</h2></div><div><span class="kicker">ROOMS</span><h2>'+c.crowspace_rooms+'</h2></div></div>')+card('<span class="kicker">GRAPH WORKSPACE</span><p>Use the live graph tools to explore people, communities, interests and connections.</p><a class="btn" href="discover.html">DISCOVER CONNECTIONS</a> <a class="btn" href="profile.html">MY SPACE</a>'))}
async function activity(){if(!user){app().innerHTML=shell("Activity","Your social activity.",gate());return}const r=await sb.from("crowspace_activity").select("*").eq("actor_id",user.id).order("created_at",{ascending:false}).limit(100);app().innerHTML=shell("Activity","Your recent CrowSpace activity.",card((r.data||[]).map(x=>'<div class="notification"><b>'+esc(x.type||"Activity")+'</b><p>'+esc(x.message||x.content||"")+'</p><small class="muted">'+esc(x.created_at||"")+'</small></div>').join("")||'<p class="muted">No activity yet.</p>'))}
async function space(){const id=q("id");if(!id){return simpleTable("crowspace_spaces","CrowSpaces","Community hubs.","name","description")}const r=await sb.from("crowspace_spaces").select("*").or("slug.eq."+id+",id.eq."+id).maybeSingle();const x=r.data;if(!x){app().innerHTML=shell("CrowSpace","Not found.",card("<p>That CrowSpace could not be found.</p>"));return}app().innerHTML=shell(x.name,x.description||"Community hub.",card('<a class="btn" href="groups.html">EXPLORE GROUPS</a> <a class="btn" href="rooms.html">CROWROOMS</a>'))}
async function room(){const id=q("id");if(!id)return simpleTable("crowspace_rooms","CrowRooms","Live community conversations.","name","topic");const r=await sb.from("crowspace_rooms").select("*").or("slug.eq."+id+",id.eq."+id).maybeSingle();const x=r.data;if(!x){app().innerHTML=shell("CrowRoom","Not found.",card("<p>That room could not be found.</p>"));return}const msgs=(await sb.from("crowspace_room_messages").select("*").eq("room_id",x.id).order("created_at",{ascending:false}).limit(50)).data||[];app().innerHTML=shell(x.name,x.topic||"Live conversation.",card(msgs.map(m=>'<div class="wall"><p>'+esc(m.content||m.body||"")+'</p><small class="muted">'+esc(m.created_at||"")+'</small></div>').join("")||'<p class="muted">No messages yet.</p>'))}
async function event(){const id=q("id");if(!id)return simpleTable("crowspace_events","Events","Community calendar.","title","description");const r=await sb.from("crowspace_events").select("*").or("slug.eq."+id+",id.eq."+id).maybeSingle();const x=r.data;if(!x){app().innerHTML=shell("Event","Not found.",card("<p>That event could not be found.</p>"));return}app().innerHTML=shell(x.title,x.description||"Community event.",card('<p><b>'+esc(x.location||"")+'</b></p><p class="muted">'+esc(x.starts_at||"")+'</p>'+(user?btn("INTERESTED","rsvp:"+x.id):"")))}
async function render(){const p=page();const routes={"auth.html":auth,"settings.html":settings,"messages.html":messages,"crowmail.html":messages,"graph.html":graph,"activity.html":activity,"circles.html":friends,"room.html":room,"space.html":space,"event.html":event,"photos.html":()=>simpleTable("crowspace_media","Photos","Member photo gallery.","title","description"),"videos.html":()=>simpleTable("crowspace_media","Videos","Member video gallery.","title","description")};if(routes[p])await routes[p]();else if(!app().innerHTML.trim())await simpleTable("crowspace_profiles","CrowSpace","Your social universe.","display_name","bio");}
async function action(a){if(a==="signout"){await sb.auth.signOut();location.href="auth.html";return}if(a.startsWith("rsvp:")&&user){const id=a.slice(5);const x=(await sb.from("crowspace_event_members").select("id").eq("event_id",id).eq("user_id",user.id).maybeSingle()).data;if(x)await sb.from("crowspace_event_members").delete().eq("id",x.id);else await sb.from("crowspace_event_members").insert({event_id:id,user_id:user.id,status:"going"});event()}}
document.addEventListener("submit",async e=>{const f=e.target;if(f.id==="uSignIn"||f.id==="uSignUp"){e.preventDefault();const d=new FormData(f),email=String(d.get("email")),password=String(d.get("password"));const result=f.id==="uSignIn"?await sb.auth.signInWithPassword({email,password}):await sb.auth.signUp({email,password,options:{data:{display_name:String(d.get("display_name")||"")}}});const box=document.getElementById("authStatus");if(result.error){box.textContent=result.error.message}else{box.textContent=f.id==="uSignUp"?"Account created. Check your email if confirmation is enabled.":"Signed in.";setTimeout(()=>location.href="profile.html",700)}}if(f.id==="uSettings"){e.preventDefault();const d=new FormData(f);const r=await sb.from("crowspace_profiles").update({display_name:d.get("display_name"),username:d.get("username"),bio:d.get("bio"),location:d.get("location"),avatar_url:d.get("avatar_url"),banner_url:d.get("banner_url"),updated_at:new Date().toISOString()}).eq("user_id",user.id);if(r.error)alert(r.error.message);else settings()}});document.addEventListener("click",e=>{const b=e.target.closest("[data-universal-action]");if(b)action(b.dataset.universalAction)});
async function boot(){sb=await loadClient();if(!sb)return;user=(await sb.auth.getUser()).data.user;setTimeout(async()=>{if(!app())return;if(app().innerHTML.trim())return;await render()},1200)}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
})();