import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { Image } from "https://deno.land/x/imagescript@1.2.15/mod.ts";

const supabase = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
const sizes:any={portfolio:[1280,720],gallery:[1200,900],album:[1000,1000]};
async function hash(parts:unknown[]){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify(parts)));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function claim(worker:string){const {data,error}=await supabase.rpc("crowspace_claim_thumbnail_job",{worker});if(error)throw error;return data?.[0]||null}
function cropBox(w:number,h:number,ratio:number,x:number,y:number,zoom:number){let cw=w,ch=w/ratio;if(ch>h){ch=h;cw=h*ratio}const scale=Math.max(1,100/(zoom||100));cw=Math.min(w,cw*scale);ch=Math.min(h,ch*scale);const cx=w*(x||50)/100,cy=h*(y||50)/100;return {sx:Math.max(0,Math.min(w-cw,cx-cw/2)),sy:Math.max(0,Math.min(h-ch,cy-ch/2)),cw,ch}}
async function process(job:any){const {data:m,error}=await supabase.from("crowspace_hero_media").select("*").eq("id",job.media_id).eq("user_id",job.user_id).single();if(error)throw error;if(!m)throw new Error("Media not found");if(m.media_type==="video")throw new Error("Video media requires a poster thumbnail for server-side cropping");
let sourceUrl=m.public_url||"";const prediction=await supabase.rpc("crowspace_thumbnail_select_v114",{p_media_id:m.id,p_user_id:m.user_id});if(!prediction.error&&prediction.data?.selected&&prediction.data.source_url){sourceUrl=prediction.data.source_url}let res=await fetch(sourceUrl);
if(!res.ok){await supabase.rpc("crowspace_thumbnail_source_failover",{p_media_id:m.id,p_user_id:m.user_id});const {data:fm}=await supabase.from("crowspace_hero_media").select("public_url").eq("id",m.id).single();if(fm?.public_url && fm.public_url!==sourceUrl){sourceUrl=fm.public_url;res=await fetch(sourceUrl)}}
if(!res.ok && m.storage_path){const candidate=supabase.storage.from("crowspace-media").getPublicUrl(m.storage_path).data.publicUrl;const alt=await fetch(candidate);if(alt.ok){await supabase.from("crowspace_hero_media").update({public_url:candidate}).eq("id",m.id).eq("user_id",m.user_id);await supabase.from("crowspace_thumbnail_source_repairs").insert({user_id:m.user_id,media_id:m.id,job_id:job.id,old_source_url:m.public_url,repaired_source_url:candidate,repair_method:"storage_path",status:"repaired"});sourceUrl=candidate;res=alt}else{await supabase.from("crowspace_thumbnail_source_repairs").insert({user_id:m.user_id,media_id:m.id,job_id:job.id,old_source_url:m.public_url,repaired_source_url:candidate,repair_method:"storage_path",status:"failed",error_message:"Alternate storage source failed: "+alt.status})}}
const sourceContentType=res.headers.get("content-type")||"";const sourceBytes=Number(res.headers.get("content-length")||0)||null;const sourceSuccess=res.ok&&sourceContentType.startsWith("image/");await supabase.rpc("crowspace_thumbnail_update_source_health",{p_media_id:m.id,p_user_id:m.user_id,p_source_url:sourceUrl,p_success:sourceSuccess,p_status:res.status});await supabase.from("crowspace_thumbnail_source_validation_history").insert({user_id:m.user_id,media_id:m.id,source_url:sourceUrl,success:sourceSuccess,status:res.status,content_type:sourceContentType,response_bytes:sourceBytes});await supabase.rpc("crowspace_thumbnail_record_prediction_feedback",{p_media_id:m.id,p_user_id:m.user_id,p_source_url:sourceUrl,p_success:sourceSuccess,p_status:res.status,p_error:sourceSuccess?null:"source_validation_failed"});await supabase.rpc("crowspace_thumbnail_evaluate_counterfactual",{p_experiment_id:(await supabase.from("crowspace_thumbnail_source_experiments").select("id").eq("media_id",m.id).eq("source_url",sourceUrl).eq("selection_mode","exploration").is("completed_at",null).order("created_at",{ascending:false}).limit(1).maybeSingle()).data?.id,p_success:sourceSuccess});
if(!res.ok){const e=new Error("Source download failed: "+res.status);(e as any).sourceStatus=res.status;(e as any).sourceContentType=sourceContentType;(e as any).sourceBytes=sourceBytes;throw e}
if(!sourceContentType.startsWith("image/")){const e=new Error("Unsupported source content type: "+sourceContentType);(e as any).sourceStatus=res.status;(e as any).sourceContentType=sourceContentType;(e as any).sourceBytes=sourceBytes;throw e}
const image=await Image.decode(new Uint8Array(await res.arrayBuffer()));const sourceHash=await hash([m.public_url,m.storage_path,m.size_bytes,m.updated_at||""]);const cropHash=await hash([m.thumbnail_crop_portfolio||{},m.thumbnail_crop_gallery||{},m.thumbnail_crop_album||{}]);const out:any={},paths:any={};for(const [idx,k] of ["portfolio","gallery","album"].entries()){const q=m["thumbnail_crop_"+k]||{x:50,y:50,zoom:100},[ow,oh]=sizes[k],b=cropBox(image.width,image.height,ow/oh,q.x,q.y,q.zoom),cropped=image.crop(b.sx,b.sy,b.cw,b.ch).resize(ow,oh),bytes=await cropped.encodeWEBP(92),path=m.user_id+"/portfolio/generated/"+m.id+"-"+k+"-"+Date.now()+".webp",up=await supabase.storage.from("crowspace-media").upload(path,bytes,{upsert:false,contentType:"image/webp"});if(up.error)throw up.error;paths[k]=path;out[k]=supabase.storage.from("crowspace-media").getPublicUrl(path).data.publicUrl}const now=new Date().toISOString(),upd:any={thumbnail_portfolio_url:out.portfolio,thumbnail_gallery_url:out.gallery,thumbnail_album_url:out.album,thumbnail_portfolio_path:paths.portfolio,thumbnail_gallery_path:paths.gallery,thumbnail_album_path:paths.album,thumbnail_source_hash:sourceHash,thumbnail_crop_hash:cropHash,thumbnail_generated_at:now,thumbnail_url:out.portfolio};const {error:ue}=await supabase.from("crowspace_hero_media").update(upd).eq("id",m.id).eq("user_id",m.user_id);if(ue)throw ue;await supabase.from("crowspace_thumbnail_jobs").update({status:"completed",progress:100,completed_at:now,updated_at:now,error_message:"",locked_at:null,locked_by:""}).eq("id",job.id);return upd}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok");try{const body=await req.json().catch(()=>({})),worker=body.worker||"thumbnail-worker",maxJobs=Math.min(Math.max(Number(body.max_jobs)||5,1),10),results:any[]=[];
    // v90: self-healing is also scheduled server-side; this call is idempotent and capped.
    if(body.self_heal!==false){const b=await supabase.rpc("crowspace_thumbnail_bootstrap_sources",{p_limit:250});if(!b.error)results.push({bootstrap:b.data});const d=await supabase.rpc("crowspace_thumbnail_discover_candidates",{p_limit:250});if(!d.error)results.push({candidate_discovery:d.data});const v=await supabase.rpc("crowspace_thumbnail_validate_candidates",{p_limit:100});if(!v.error)results.push({candidate_validation:v.data});const cal=await supabase.rpc("crowspace_thumbnail_calibrate_predictions",{p_limit:250});if(!cal.error)results.push({prediction_calibration:cal.data});const h=await supabase.rpc("crowspace_thumbnail_self_heal_system",{p_limit:25});if(!h.error)results.push({self_heal:h.data});}for(let i=0;i<maxJobs;i++){const job=await claim(worker);if(!job)break;try{const result=await process(job);results.push({job_id:job.id,ok:true,result})}catch(e){const msg=String((e as any)?.message||e),attempts=job.attempts||1,retry=attempts<(job.max_attempts||3);
      const {data:recovery}=await supabase.rpc("crowspace_thumbnail_classify_failure",{p_job_id:job.id,p_media_id:job.media_id,p_user_id:job.user_id,p_error:msg,p_status:(e as any)?.sourceStatus||null,p_content_type:(e as any)?.sourceContentType||null,p_bytes:(e as any)?.sourceBytes||null});
      const quarantined=Boolean(recovery?.quarantined);
      await supabase.from("crowspace_thumbnail_jobs").update({status:quarantined?"failed":(retry?"queued":"failed"),progress:retry?0:job.progress,error_message:msg,updated_at:new Date().toISOString(),locked_at:null,locked_by:""}).eq("id",job.id);
      results.push({job_id:job.id,ok:false,retry:quarantined?false:retry,quarantined,error:msg,recovery})}}return Response.json({ok:true,processed:results.length,results})}catch(e){return Response.json({ok:false,error:String((e as any)?.message||e)},{status:500})}});