import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { Image } from "https://deno.land/x/imagescript@1.2.15/mod.ts";

const supabase = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
const sizes:any={portfolio:[1280,720],gallery:[1200,900],album:[1000,1000]};
async function hash(parts:unknown[]){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify(parts)));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function claim(worker:string){const {data,error}=await supabase.rpc("crowspace_claim_thumbnail_job",{worker});if(error)throw error;return data?.[0]||null}
function cropBox(w:number,h:number,ratio:number,x:number,y:number,zoom:number){let cw=w,ch=w/ratio;if(ch>h){ch=h;cw=h*ratio}const scale=Math.max(1,100/(zoom||100));cw=Math.min(w,cw*scale);ch=Math.min(h,ch*scale);const cx=w*(x||50)/100,cy=h*(y||50)/100;return {sx:Math.max(0,Math.min(w-cw,cx-cw/2)),sy:Math.max(0,Math.min(h-ch,cy-ch/2)),cw,ch}}
async function process(job:any){const {data:m,error}=await supabase.from("crowspace_hero_media").select("*").eq("id",job.media_id).eq("user_id",job.user_id).single();if(error)throw error;if(!m)throw new Error("Media not found");if(m.media_type==="video")throw new Error("Video media requires a poster thumbnail for server-side cropping");const res=await fetch(m.public_url);if(!res.ok)throw new Error("Source download failed: "+res.status);const image=await Image.decode(new Uint8Array(await res.arrayBuffer()));const sourceHash=await hash([m.public_url,m.storage_path,m.size_bytes,m.updated_at||""]);const cropHash=await hash([m.thumbnail_crop_portfolio||{},m.thumbnail_crop_gallery||{},m.thumbnail_crop_album||{}]);const out:any={},paths:any={};for(const [idx,k] of ["portfolio","gallery","album"].entries()){const q=m["thumbnail_crop_"+k]||{x:50,y:50,zoom:100},[ow,oh]=sizes[k],b=cropBox(image.width,image.height,ow/oh,q.x,q.y,q.zoom),cropped=image.crop(b.sx,b.sy,b.cw,b.ch).resize(ow,oh),bytes=await cropped.encodeWEBP(92),path=m.user_id+"/portfolio/generated/"+m.id+"-"+k+"-"+Date.now()+".webp",up=await supabase.storage.from("crowspace-media").upload(path,bytes,{upsert:false,contentType:"image/webp"});if(up.error)throw up.error;paths[k]=path;out[k]=supabase.storage.from("crowspace-media").getPublicUrl(path).data.publicUrl}const now=new Date().toISOString(),upd:any={thumbnail_portfolio_url:out.portfolio,thumbnail_gallery_url:out.gallery,thumbnail_album_url:out.album,thumbnail_portfolio_path:paths.portfolio,thumbnail_gallery_path:paths.gallery,thumbnail_album_path:paths.album,thumbnail_source_hash:sourceHash,thumbnail_crop_hash:cropHash,thumbnail_generated_at:now,thumbnail_url:out.portfolio};const {error:ue}=await supabase.from("crowspace_hero_media").update(upd).eq("id",m.id).eq("user_id",m.user_id);if(ue)throw ue;await supabase.from("crowspace_thumbnail_jobs").update({status:"completed",progress:100,completed_at:now,updated_at:now,error_message:"",locked_at:null,locked_by:""}).eq("id",job.id);return upd}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok");try{const body=await req.json().catch(()=>({})),worker=body.worker||"thumbnail-worker",maxJobs=Math.min(Math.max(Number(body.max_jobs)||5,1),10),results:any[]=[];
    // v90: self-healing is also scheduled server-side; this call is idempotent and capped.\n    if(body.self_heal!==false){const {data:heal,error:healError}=await supabase.rpc("crowspace_thumbnail_self_heal_system",{p_limit:25});if(!healError)results.push({self_heal:heal});}for(let i=0;i<maxJobs;i++){const job=await claim(worker);if(!job)break;try{const result=await process(job);results.push({job_id:job.id,ok:true,result})}catch(e){const msg=String((e as any)?.message||e),attempts=job.attempts||1,retry=attempts<(job.max_attempts||3);await supabase.from("crowspace_thumbnail_jobs").update({status:retry?"queued":"failed",progress:retry?0:job.progress,error_message:msg,updated_at:new Date().toISOString(),locked_at:null,locked_by:""}).eq("id",job.id);results.push({job_id:job.id,ok:false,retry,error:msg})}}return Response.json({ok:true,processed:results.length,results})}catch(e){return Response.json({ok:false,error:String((e as any)?.message||e)},{status:500})}});