const SUPABASE_URL="https://cevylpnoexugwgygvtgu.supabase.co";const SUPABASE_KEY="sb_publishable_AdfM5y6RqvF3tbvEVzDZSg_JuGTQLD-";const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const divisions=[
 {key:"dreamscapes",name:"Dreamscapes",icon:"🌌",desc:"Ideas, creative rooms, projects and production.",path:"https://crowrulesentertainment-oss.github.io/dreamscapes/"},
 {key:"podcasting",name:"Podcasting",icon:"🎙️",desc:"Shows, episodes, clips and creator tools.",path:"https://crowrulesentertainment-oss.github.io/podcasting/"},
 {key:"sports",name:"Sports",icon:"🏟️",desc:"Sports communities, Pick'em and fan experiences."},
 {key:"memorials",name:"Memorials",icon:"🕯️",desc:"Remember. Honor. Celebrate."},
 {key:"tv",name:"CrowRules TV",icon:"📺",desc:"Shows, channels, live and on-demand."}
];
let state={user:null,profile:null,member:null,plan:null,access:{},posts:[],events:[]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function toast(m){const e=$("#status");e.textContent=m;e.classList.add("show");clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.remove("show"),2600)}
function go(page){$$("[data-pageview]").forEach(x=>x.classList.toggle("active-page",x.dataset.pageview===page));$$("#nav a").forEach(x=>x.classList.toggle("active",x.dataset.page===page));location.hash=page;window.scrollTo(0,0)}
function setupNav(){$$("#nav a").forEach(a=>a.onclick=()=>go(a.dataset.page));$$("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));$$("[data-toast]").forEach(b=>b.onclick=()=>toast(b.dataset.toast));$("#menu").onclick=()=>$(".sidebar").classList.toggle("open");$("#logout").onclick=async()=>{await db.auth.signOut();location.reload()};$("#notify").onclick=()=>toast("Notification center is connected to your CrowSpace account.");$("#search").onkeydown=e=>{if(e.key==="Enter"&&e.target.value.trim())toast("Search index ready — connecting full-text search next.")}}
function divisionAccess(key){return !!state.access[key]}
function renderDivisionNav(){const n=$("#divisionNav");n.innerHTML=divisions.map(d=>{const ok=divisionAccess(d.key);return '<a class="division-link" data-division="'+d.key+'">'+d.icon+' <span>'+d.name+'</span><em class="'+(ok?"":"locked")+'">'+(ok?"MEMBER":"JOIN")+'</em></a>'}).join("");$$("[data-division]").forEach(a=>a.onclick=()=>openDivision(a.dataset.division))}
function openDivision(key){const d=divisions.find(x=>x.key===key);if(!divisionAccess(key)){goGate(d);return}const target="division-"+key;go(target)}
function goGate(d){const pages=$("#divisionPages");const id="division-"+d.key;let sec=document.querySelector('[data-pageview="'+id+'"]');if(!sec){sec=document.createElement("section");sec.className="page";sec.dataset.pageview=id;sec.innerHTML='<div class="gate"><span>'+d.icon+'</span><small class="eyebrow">CROWRULES DIVISION</small><h2>'+d.name+' access required</h2><p>Your Universal CrowRules account is active, but this division is not currently active for your account. Division membership controls the division-specific tools and private content.</p><button class="primary" onclick="toast(\'Open Universal CrowRules Membership from your main account flow.\')">View Membership</button></div>';pages.appendChild(sec)}go(id)}
async function loadContext(){
 const {data:{session}}=await db.auth.getSession();state.user=session?.user||null;
 if(!state.user){renderSignedOut();return}
 const uid=state.user.id;
 const [memberR,profileR,spaceR,postR,eventR]=await Promise.all([
  db.from("members").select("id,user_id,display_name,username,membership_type,role,status,points,watch_minutes,bio,avatar_url").eq("user_id",uid).maybeSingle(),
  db.from("crowspace_profiles").select("*").eq("user_id",uid).maybeSingle(),
  db.from("crowspace_memberships").select("membership_plan_id,status,membership_plans(plan_key,name,level)").eq("user_id",uid).eq("status","active").maybeSingle(),
  db.from("crowspace_posts").select("id,author_id,body,media_url,media_type,created_at,like_count,comment_count").eq("status","published").order("created_at",{ascending:false}).limit(20),
  db.from("crowspace_events").select("id,title,description,event_type,starts_at,location,stream_url,visibility").order("starts_at",{ascending:true}).limit(10)
 ]);
 state.member=memberR.data;state.profile=profileR.data;state.plan=spaceR.data?.membership_plans||null;state.posts=postR.data||[];state.events=eventR.data||[];
 const ctx=await db.rpc("crowspace_get_access");state.access={crowspace:true};if(ctx.data?.divisions)ctx.data.divisions.forEach(x=>state.access[x.site_key]=true);
 // Fallback: derive the universal CrowSpace entitlement from the actual membership row.
 state.access.crowspace=!!state.plan||!!state.member;
 render();
}
function renderSignedOut(){document.body.innerHTML='<main style="min-height:100vh;display:grid;place-items:center;padding:30px"><div class="gate"><span>🐦</span><small class="eyebrow">CROWRULES ENTERTAINMENT</small><h2>CrowSpace requires your Universal CrowRules account</h2><p>Sign in through the same account used across CrowRules Entertainment.</p><a href="../login.html"><button class="primary">Sign in</button></a></div></main>'}
function render(){const name=state.profile?.display_name||state.member?.display_name||state.user.email?.split("@")[0]||"Crow Member";const username=state.profile?.username||state.member?.username||"member";const points=state.member?.points||0;const level=Math.max(1,Math.floor(points/1000)+1);
 $("#accountCard").innerHTML='<div class="avatar">'+initials(name)+'</div><div><b>'+esc(name)+'</b><small>@'+esc(username)+' · Level '+level+'</small></div>';$("#topAvatar").textContent=initials(name);
 $("#stats").innerHTML=[["CROWPOINTS",points.toLocaleString()],["LEVEL",level],["FRIENDS","—"],["PROJECTS","—"],["DIVISIONS",Object.keys(state.access).filter(k=>k!=="crowspace").length]].map(x=>'<div><small>'+x[0]+'</small><b>'+x[1]+'</b></div>').join("");
 renderDivisionNav();$("#divisions").innerHTML=divisions.map(d=>{const ok=divisionAccess(d.key);return '<article class="division-card '+(ok?"":"locked")+'"><span>'+d.icon+'</span><div><h3>'+d.name+'</h3><p>'+d.desc+'</p><strong>'+(ok?"● MEMBER ACCESS":"🔒 DIVISION ACCESS REQUIRED")+'</strong></div></article>'}).join("");
 renderFeed(name);renderEvents();renderLeaderboard(name,points);renderPassport(name,username,points,level);renderSpectrum();
}
function renderFeed(name){const demo=[{author:name,body:"Welcome to CrowSpace — one social universe connecting members, creators, communities and CrowRules projects.",media_type:"video",created_at:new Date().toISOString(),like_count:0,comment_count:0}];const posts=state.posts.length?state.posts:demo;$("#feed").innerHTML=posts.map(p=>'<article class="post"><div class="post-head"><div class="avatar">'+initials(p.author||"CR")+'</div><div><b>'+esc(p.author||"Crow Member")+'</b> <span class="verified">✓ CrowSpace</span><small>'+timeAgo(p.created_at)+'</small></div></div><p>'+esc(p.body||"")+'</p>'+(p.media_url?'<div class="media"><video controls playsinline src="'+esc(p.media_url)+'"></video></div>':p.media_type?'<div class="media"><b>'+mediaIcon(p.media_type)+'</b><small>'+esc(p.media_type)+'</small></div>':"")+'<div class="post-actions"><button>❤️ Like</button><button>💬 '+(p.comment_count||0)+' Comment</button><button>↗ Share</button><button>🐦 CrowPoints</button></div></article>').join("")}
function renderEvents(){const list=state.events.length?state.events:[{title:"Back Deck Live",description:"Unscripted Saturday conversation",starts_at:"2026-09-26T22:00:00Z",location:"Online"},{title:"Dreamscapes Creative Room",description:"Collaborative project workshop",starts_at:"2026-09-27T20:00:00Z",location:"CrowSpace · Members"}];$("#eventsList").innerHTML=list.map(e=>{const d=new Date(e.starts_at);return '<article class="event"><div class="date"><b>'+d.getDate()+'</b><small>'+d.toLocaleString(undefined,{month:"short"}).toUpperCase()+'</small></div><div><h3>'+esc(e.title)+'</h3><p>'+esc(e.description||"")+' · '+esc(e.location||"Online")+'</p></div><button data-toast="Event RSVP ready">Interested</button></article>'}).join("")}
function renderLeaderboard(name,points){const rows=[["1","Community Builder","3,840"],["2","Creator Spotlight","3,120"],["3",name,points.toLocaleString()]];$("#leaderboard").innerHTML=rows.map((r,i)=>'<div class="leader-row"><b>'+r[0]+'</b><strong>'+esc(r[1])+'</strong><span>'+((i+1)*12)+' contributions</span><b>'+r[2]+'</b></div>').join("")}
function renderPassport(name,username,points,level){$("#passport").innerHTML='<div class="passport-top"><div class="passport-photo">'+initials(name)+'</div><div><small class="eyebrow">CROWSPACE PASSPORT</small><h2>'+esc(name)+'</h2><p>@'+esc(username)+' · Level '+level+'</p></div><span class="passport-code">CROW-'+String(level).padStart(3,"0")+'</span></div><div class="passport-stats"><div><small>CROWPOINTS</small><b>'+points.toLocaleString()+'</b></div><div><small>MEMBERSHIP</small><b>'+esc(state.plan?.name||state.member?.membership_type||"CROW")+'</b></div><div><small>CREATOR MODE</small><b>'+(state.profile?.creator_mode?"ON":"OFF")+'</b></div><div><small>VERIFICATION</small><b>'+((state.profile?.verification_status==="verified")?"VERIFIED":"STANDARD")+'</b></div></div><div class="stamps"><span class="stamp">🐦 CrowSpace</span>'+divisions.map(d=>'<span class="stamp '+(divisionAccess(d.key)?"":"locked-stamp")+'">'+d.icon+" "+d.name+(divisionAccess(d.key)?"":" · Locked")+"</span>").join("")+'</div>'}
function renderSpectrum(){$("#spectrumData").innerHTML=[["🎬","Independent Production","Original productions and creative work."],["🎙️","Best Podcast","Compelling podcast concepts and episodes."],["🌌","Dream Builder","Ideas moved toward reality."],["🤝","Collaboration","The team behind the work."]].map(x=>'<article>'+x[0]+'<h3>'+x[1]+'</h3><p>'+x[2]+'</p><button data-toast="Spectrum category ready">View entries</button></article>').join("")}
function initials(s){return String(s||"CS").split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase()}function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}function mediaIcon(t){return t==="reel"?"🎞️":t==="picture"?"📸":t==="video"?"🎥":"📝"}function timeAgo(v){const d=Date.now()-new Date(v).getTime(),m=Math.max(1,Math.floor(d/60000));return m<60?m+"m ago":Math.floor(m/60)+"h ago"}
window.addEventListener("hashchange",()=>{const h=location.hash.slice(1);if(h)go(h)});
db.auth.onAuthStateChange((_e,session)=>{if(session?.user)loadContext()});
setupNav();loadContext();