const DB_NAME="crowspace-caws",STORE="videos";let db,videoBlob=null,thumbBlob=null,duration=0,editingId=null,currentTab="all",allItems=[];
const $=id=>document.getElementById(id);
function initDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,2);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:"id"})};r.onsuccess=()=>{db=r.result;resolve()};r.onerror=()=>reject(r.error)})}
function all(){return new Promise((res,rej)=>{const r=db.transaction(STORE,"readonly").objectStore(STORE).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function save(item){return new Promise((res,rej)=>{const t=db.transaction(STORE,"readwrite");t.objectStore(STORE).put(item);t.oncomplete=res;t.onerror=()=>rej(t.error)})}
function remove(id){return new Promise((res,rej)=>{const t=db.transaction(STORE,"readwrite");t.objectStore(STORE).delete(id);t.oncomplete=res;t.onerror=()=>rej(t.error)})}
function format(s){return isFinite(s)?Math.floor(s/60)+":"+String(Math.floor(s%60)).padStart(2,"0"):"—"}
function esc(s){return String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function loadVideo(file){if(!file||!file.type.startsWith("video/"))return;videoBlob=file;$("fileName").textContent=file.name;$("uploadState").textContent="Video selected";const v=$("previewVideo");v.src=URL.createObjectURL(file);v.onloadedmetadata=()=>{duration=v.duration;$("durationLabel").textContent="Duration: "+format(duration);$("thumbTime").max=duration;$("thumbTime").value=Math.min(1,duration);drawThumb()}}
$("videoFile").onchange=e=>loadVideo(e.target.files[0]);
$("previewVideo").ontimeupdate=drawThumb;$("thumbTime").oninput=()=>{$("previewVideo").currentTime=+$("thumbTime").value;drawThumb()};
function drawThumb(){const v=$("previewVideo"),c=$("thumbCanvas"),x=c.getContext("2d");if(!v.videoWidth)return;const ratio=Math.max(c.width/v.videoWidth,c.height/v.videoHeight),w=v.videoWidth*ratio,h=v.videoHeight*ratio;x.fillStyle="#05070c";x.fillRect(0,0,c.width,c.height);x.drawImage(v,(c.width-w)/2,(c.height-h)/2,w,h);c.toBlob(b=>thumbBlob=b,"image/jpeg",.82)}
$("dropZone").ondragover=e=>{e.preventDefault();$("dropZone").classList.add("drag")};$("dropZone").ondragleave=()=>$("dropZone").classList.remove("drag");$("dropZone").ondrop=e=>{e.preventDefault();$("dropZone").classList.remove("drag");loadVideo(e.dataTransfer.files[0])};
function openEditor(item=null){editingId=item?.id||null;$("editorTitle").textContent=item?"Edit your Caw":"Create your Caw";$("creatorName").value=item?.creator||"Jonathan Riehle";$("creatorHandle").value=item?.handle||"@jriehle";$("caption").value=item?.caption||"";videoBlob=item?.video||null;thumbBlob=item?.thumb||null;duration=item?.duration||0;$("fileName").textContent=item?.fileName||"No video selected";$("durationLabel").textContent="Duration: "+format(duration);$("uploadState").textContent=item?"Editing saved Caw":"Ready";if(item?.video){$("previewVideo").src=URL.createObjectURL(item.video);$("previewVideo").onloadedmetadata=()=>{duration=$("previewVideo").duration;$("thumbTime").max=duration;drawThumb()}}else{$("previewVideo").removeAttribute("src");$("previewVideo").load();$("thumbCanvas").getContext("2d").clearRect(0,0,360,640)}$("studioStatus").textContent="";$("editorModal").classList.add("show")}
function closeEditor(){$("editorModal").classList.remove("show");editingId=null;videoBlob=null;thumbBlob=null}
$("createCaw").onclick=()=>openEditor();$("closeEditor").onclick=closeEditor;
async function persist(status){const name=$("creatorName").value.trim()||"Crow Creator",handle=$("creatorHandle").value.trim()||"@creator",caption=$("caption").value.trim();if(!videoBlob){$("studioStatus").textContent="Select a video first.";return}if(!caption){$("studioStatus").textContent="Add a caption first.";return}const old=editingId?allItems.find(x=>x.id===editingId):null;const item={id:editingId||Date.now(),creator:name,handle,avatar:name.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase(),caption,likes:old?.likes||0,comments:old?.comments||0,recasts:old?.recasts||0,duration,video:videoBlob,thumb:thumbBlob||old?.thumb||null,created:old?.created||new Date().toISOString(),status,fileName:videoBlob.name||old?.fileName||"Caw video"};try{$("uploadState").textContent=status==="published"?"Publishing…":"Saving draft…";await save(item);$("studioStatus").textContent=status==="published"?"CAW PUBLISHED • Your Caw is ready.":"DRAFT SAVED • You can finish it later.";setTimeout(()=>{closeEditor();refresh()},500)}catch(e){$("studioStatus").textContent="Could not save this Caw in this browser."}}
$("publishCaw").onclick=()=>persist("published");$("saveDraft").onclick=()=>persist("draft");
function card(x){const thumb=x.thumb?URL.createObjectURL(x.thumb):"";return `<article class="studio-item card"><div class="studio-thumb">${thumb?`<img src="${thumb}" alt="">`:"<span>CAW</span>"}<i>${format(x.duration)}</i></div><div class="studio-item-body"><div class="studio-item-head"><div><b>${esc(x.creator)}</b><small>${esc(x.handle)}</small></div><span class="status-pill ${x.status}">${x.status==="published"?"PUBLISHED":"DRAFT"}</span></div><p>${esc(x.caption)}</p><div class="metric-row"><span>◉ ${x.views||0} views</span><span>♥ ${x.likes||0}</span><span>💬 ${x.comments||0}</span><span>↻ ${x.recasts||0}</span></div><div class="item-actions"><button data-act="edit" data-id="${x.id}">Edit</button><button data-act="view" data-id="${x.id}">View Caw</button><button class="danger" data-act="delete" data-id="${x.id}">Delete</button></div></div></article>`}
async function refresh(){allItems=(await all()).sort((a,b)=>new Date(b.created)-new Date(a.created));$("totalCount").textContent=allItems.length;$("publishedCount").textContent=allItems.filter(x=>x.status==="published").length;$("draftCount").textContent=allItems.filter(x=>x.status==="draft").length;const views=allItems.reduce((n,x)=>n+(x.views||0),0),engagement=views?Math.round((allItems.reduce((n,x)=>n+(x.likes||0)+(x.comments||0)+(x.recasts||0),0)/views)*100):0;$("totalViews").textContent=views;$("totalEngagement").textContent=engagement+"%";$("insightViews").textContent=views;$("insightText").textContent=allItems.length?`Across ${allItems.length} local Caw${allItems.length===1?"":"s"} • ${engagement}% interaction rate`:"Publish a Caw to begin building your local analytics.";renderLibrary()}
function renderLibrary(){const q=$("studioSearch").value.trim().toLowerCase();let list=allItems.filter(x=>currentTab==="all"||x.status===currentTab);if(q)list=list.filter(x=>(x.caption+" "+x.creator+" "+x.handle).toLowerCase().includes(q));$("studioLibrary").innerHTML=list.length?list.map(card).join(""):`<section class="card panel empty-studio"><div class="panel-title">NOTHING HERE YET</div><h3>Create your first Caw.</h3><p>Your drafts and published Caws will appear here.</p><button class="post-button" onclick="document.getElementById('createCaw').click()">＋ Create Caw</button></section>`;document.querySelectorAll(".studio-item button").forEach(b=>b.onclick=async()=>{const x=allItems.find(x=>String(x.id)===b.dataset.id);if(!x)return;if(b.dataset.act==="edit")openEditor(x);if(b.dataset.act==="view"){localStorage.setItem("crowspace:cawFocus",String(x.id));location.href="caws.html#caw-"+x.id}if(b.dataset.act==="delete"&&confirm("Delete this Caw?")){await remove(x.id);refresh()}})}
document.querySelectorAll(".studio-tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".studio-tabs button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");currentTab=b.dataset.tab;renderLibrary()});$("studioSearch").oninput=renderLibrary;
initDB().then(refresh);
