const DB_NAME="crowspace-caws",STORE="videos";let db,videoBlob=null,thumbBlob=null,duration=0,editingId=null,currentTab="all",allItems=[],selected=new Set();
const $=id=>document.getElementById(id);
function initDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,2);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:"id"});document.querySelectorAll(".season-edit").forEach(b=>b.onclick=async()=>{const season=Number(b.dataset.season);const title=prompt("Season label (optional):",`Season ${season}`);if(title===null)return;await updateSeriesMeta(series,season,{seasonLabel:title.trim()||`Season ${season}`});allItems=await getAll();refresh()});document.querySelectorAll("[data-move]").forEach(b=>b.onclick=async()=>{await moveEpisode(b.dataset.id,Number(b.dataset.move));allItems=await getAll();refresh()})};r.onsuccess=()=>{db=r.result;resolve()};r.onerror=()=>reject(r.error)})}
function all(){return new Promise((res,rej)=>{const r=db.transaction(STORE,"readonly").objectStore(STORE).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function save(item){return new Promise((res,rej)=>{const t=db.transaction(STORE,"readwrite");t.objectStore(STORE).put(item);t.oncomplete=res;t.onerror=()=>rej(t.error)})}
function remove(id){return new Promise((res,rej)=>{const t=db.transaction(STORE,"readwrite");t.objectStore(STORE).delete(id);t.oncomplete=res;t.onerror=()=>rej(t.error)})}
function format(s){return isFinite(s)?Math.floor(s/60)+":"+String(Math.floor(s%60)).padStart(2,"0"):"—"}
function esc(s){return String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function loadVideo(file){if(!file||!file.type.startsWith("video/"))return;videoBlob=file;$("fileName").textContent=file.name;$("uploadState").textContent="Video selected";const v=$("previewVideo");v.src=URL.createObjectURL(file);v.onloadedmetadata=()=>{duration=v.duration;$("durationLabel").textContent="Duration: "+format(duration);$("thumbTime").max=duration;$("thumbTime").value=Math.min(1,duration);drawThumb()}}
$("videoFile").onchange=e=>loadVideo(e.target.files[0]);
$("previewVideo").ontimeupdate=drawThumb;$("thumbTime").oninput=()=>{$("previewVideo").currentTime=+$("thumbTime").value;drawThumb()};
function drawThumb(){const v=$("previewVideo"),c=$("thumbCanvas"),x=c.getContext("2d");if(!v.videoWidth)return;const ratio=Math.max(c.width/v.videoWidth,c.height/v.videoHeight),w=v.videoWidth*ratio,h=v.videoHeight*ratio;x.fillStyle="#05070c";x.fillRect(0,0,c.width,c.height);x.drawImage(v,(c.width-w)/2,(c.height-h)/2,w,h);c.toBlob(b=>thumbBlob=b,"image/jpeg",.82)}
$("dropZone").ondragover=e=>{e.preventDefault();$("dropZone").classList.add("drag")};$("dropZone").ondragleave=()=>$("dropZone").classList.remove("drag");$("dropZone").ondrop=e=>{e.preventDefault();$("dropZone").classList.remove("drag");loadVideo(e.dataTransfer.files[0])};
function openEditor(item=null){editingId=item?.id||null;$("editorTitle").textContent=item?"Edit your Caw":"Create your Caw";$("creatorName").value=item?.creator||"Jonathan Riehle";$("creatorHandle").value=item?.handle||"@jriehle";$("caption").value=item?.caption||"";$("cawCategory").value=item?.category||"General";$("cawSeries").value=item?.series||"";$("cawEpisode").value=item?.episode||"";$("cawSeason").value=item?.season||1;$("cawTags").value=(item?.tags||[]).join(", ");$("scheduleAt").value=item?.scheduledAt||"";videoBlob=item?.video||null;thumbBlob=item?.thumb||null;duration=item?.duration||0;$("fileName").textContent=item?.fileName||"No video selected";$("durationLabel").textContent="Duration: "+format(duration);$("uploadState").textContent=item?"Editing saved Caw":"Ready";if(item?.video){$("previewVideo").src=URL.createObjectURL(item.video);$("previewVideo").onloadedmetadata=()=>{duration=$("previewVideo").duration;$("thumbTime").max=duration;drawThumb()}}else{$("previewVideo").removeAttribute("src");$("previewVideo").load();$("thumbCanvas").getContext("2d").clearRect(0,0,360,640)}$("studioStatus").textContent="";$("editorModal").classList.add("show")}
function closeEditor(){$("editorModal").classList.remove("show");editingId=null;videoBlob=null;thumbBlob=null}
$("createCaw").onclick=()=>openEditor();$("closeEditor").onclick=closeEditor;
async function stageUpload(){if(!videoBlob)return;const size=videoBlob.size||0;let loaded=0;const chunk=Math.max(262144,Math.ceil(size/20));$("uploadState").textContent="Preparing 0%";while(loaded<size){const end=Math.min(size,loaded+chunk);await videoBlob.slice(loaded,end).arrayBuffer();loaded=end;$("uploadState").textContent="Preparing "+Math.round(loaded/size*100)+"%";await new Promise(r=>setTimeout(r,0))}$("uploadState").textContent="Ready";}
async function persist(status){const scheduledAt=$("scheduleAt").value;if(status==="published"&&scheduledAt&&new Date(scheduledAt)>new Date())status="scheduled";const name=$("creatorName").value.trim()||"Crow Creator",handle=$("creatorHandle").value.trim()||"@creator",caption=$("caption").value.trim();if(!videoBlob){$("studioStatus").textContent="Select a video first.";return}if(status==="published"&&!caption){$("studioStatus").textContent="Add a caption before publishing.";return}const old=editingId?allItems.find(x=>x.id===editingId):null;const category=$("cawCategory").value||"General",series=$("cawSeries").value.trim();let episode=Math.max(0,parseInt($("cawEpisode").value||"0",10)||0);let season=Math.max(1,parseInt($("cawSeason").value||"1",10)||1);if(series&&!episode){episode=allItems.filter(x=>(x.series||"").trim()===series).reduce((n,x)=>Math.max(n,Number(x.episode)||0),0)+1}const tags=$("cawTags").value.split(",").map(x=>x.trim().replace(/^#/,"")).filter(Boolean).slice(0,10);const item={id:editingId||Date.now(),creator:name,handle,avatar:name.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase(),caption,category,series,season,episode,tags,likes:old?.likes||0,comments:old?.comments||0,recasts:old?.recasts||0,duration,video:videoBlob,thumb:thumbBlob||old?.thumb||null,created:old?.created||new Date().toISOString(),status:status,scheduledAt:scheduledAt||"",fileName:videoBlob.name||old?.fileName||"Caw video"};try{await stageUpload();$("uploadState").textContent=status==="published"?"Publishing…":"Saving draft…";await save(item);$("studioStatus").textContent=status==="published"?"CAW PUBLISHED • Your Caw is ready.":status==="scheduled"?"CAW SCHEDULED • This browser will publish it when Creator Studio is open.":"DRAFT SAVED • You can finish it later.";setTimeout(()=>{closeEditor();refresh()},500)}catch(e){$("studioStatus").textContent="Could not save this Caw in this browser."}}
$("publishCaw").onclick=()=>persist("published");$("saveDraft").onclick=()=>persist("draft");
async function processSchedules(){const now=new Date();let changed=false;for(const x of allItems){if(x.status==="scheduled"&&x.scheduledAt&&new Date(x.scheduledAt)<=now){await save({...x,status:"published",scheduledAt:""});changed=true}}if(changed)await refresh()}
async function quickStatus(id,status){const x=allItems.find(v=>v.id===id);if(!x)return;if(status==="published"&&!String(x.caption||"").trim()){alert("Add a caption before publishing.");return}await save({...x,status});await refresh()}
async function duplicateCaw(id){const x=allItems.find(v=>v.id===id);if(!x)return;const copy={...x,id:Date.now()+Math.floor(Math.random()*999),caption:x.caption+" (Copy)",status:"draft",views:0,likes:0,comments:0,recasts:0,created:new Date().toISOString()};await save(copy);await refresh()}
function showAnalytics(x){const ev=Array.isArray(x.analyticsEvents)?x.analyticsEvents:[],now=Date.now(),d7=ev.filter(e=>now-new Date(e.at).getTime()<=6048e5),d30=ev.filter(e=>now-new Date(e.at).getTime()<=2592e6),count=t=>ev.filter(e=>e.type===t).length;$("analyticsTitle").textContent=x.caption||"Untitled Caw";$("analyticsViews").textContent=x.views||0;$("analyticsLikes").textContent=x.likes||0;$("analyticsComments").textContent=x.comments||0;$("analyticsRecaws").textContent=x.recasts||0;const v=x.views||0,e=v?Math.round(((x.likes||0)+(x.comments||0)+(x.recasts||0))/v*100):0;$("analyticsSummary").innerHTML=`<strong>${x.status==="published"?"Published":"Draft"}</strong> • ${e}% interaction rate • Created ${new Date(x.created).toLocaleString()}<br><span class="analytics-period">Last 7 days: ${d7.length} events • Last 30 days: ${d30.length} events • Event history: ${ev.length}</span>`;$("analyticsModal").classList.add("show")}
function card(x){const thumb=x.thumb?URL.createObjectURL(x.thumb):"";return `<article class="studio-item card"><div class="studio-select"><input type="checkbox" data-select-id="${x.id}" ${selected.has(x.id)?"checked":""} aria-label="Select Caw"></div><div class="studio-thumb">${thumb?`<img src="${thumb}" alt="">`:"<span>CAW</span>"}<i>${format(x.duration)}</i></div><div class="studio-item-body"><div class="studio-item-head"><div><b>${esc(x.creator)}</b><small>${esc(x.handle)}</small></div><span class="status-pill ${x.status}">${x.status==="published"?"PUBLISHED":x.status==="scheduled"?"SCHEDULED":"DRAFT"}</span></div><p>${x.series?`<span class="caw-series">${esc(x.series)}${x.episode?` • EP ${x.episode}`:""}</span> `:""}${esc(x.caption)}</p><div class="caw-taxonomy"><span>${esc(x.category||"General")}</span>${(x.tags||[]).map(t=>`<i>#${esc(t)}</i>`).join("")}</div><div class="metric-row"><span>◉ ${x.views||0} views</span><span>♥ ${x.likes||0}</span><span>💬 ${x.comments||0}</span><span>↻ ${x.recasts||0}</span></div><div class="item-actions"><button data-act="edit" data-id="${x.id}">Edit</button><button data-act="duplicate" data-id="${x.id}">Duplicate</button>${x.status==="draft"?`<button data-act="publish" data-id="${x.id}">Publish</button>`:`<button data-act="unpublish" data-id="${x.id}">Unpublish</button>`}<button data-act="analytics" data-id="${x.id}">Analytics</button><button data-act="view" data-id="${x.id}">View</button><button class="danger" data-act="delete" data-id="${x.id}">Delete</button></div></div></article>`}
async function refresh(){allItems=(await all()).sort((a,b)=>new Date(b.created)-new Date(a.created));$("totalCount").textContent=allItems.length;$("publishedCount").textContent=allItems.filter(x=>x.status==="published").length;$("draftCount").textContent=allItems.filter(x=>x.status==="draft").length;const views=allItems.reduce((n,x)=>n+(x.views||0),0),engagement=views?Math.round((allItems.reduce((n,x)=>n+(x.likes||0)+(x.comments||0)+(x.recasts||0),0)/views)*100):0;$("totalViews").textContent=views;$("totalEngagement").textContent=engagement+"%";$("insightViews").textContent=views;$("insightText").textContent=allItems.length?`Across ${allItems.length} local Caw${allItems.length===1?"":"s"} • ${engagement}% interaction rate`:"Publish a Caw to begin building your local analytics.";refreshSeriesFilter();renderSeriesHub();renderLibrary();renderSeriesTimeline();renderCalendar();processSchedules()}
function renderSeriesHub(){const map={};allItems.forEach(x=>{const s=(x.series||"").trim();if(!s)return;if(!map[s])map[s]={count:0,views:0,published:0};map[s].count++;map[s].views+=x.views||0;if(x.status==="published")map[s].published++});const names=Object.keys(map).sort((a,b)=>map[b].count-map[a].count);$("seriesSummary").textContent=names.length?`${names.length} series • ${allItems.length} total Caws`:"No series yet";$("seriesStructure").textContent=names.length?names.map(s=>{const seasons=[...new Set(allItems.filter(x=>(x.series||"").trim()===s).map(x=>Number(x.season)||1)].sort((a,b)=>a-b);return `${s}: ${seasons.length} season${seasons.length===1?"":"s"}`}).join(" • "):"Series → Seasons → Episodes";$("seriesList").innerHTML=names.slice(0,6).map(s=>`<button class="series-card" data-series="${esc(s)}"><b>${esc(s)}</b><span>${map[s].count} Caw${map[s].count===1?"":"s"} • ${map[s].views} views</span></button>`).join("");document.querySelectorAll(".series-card").forEach(b=>b.onclick=()=>{$("studioSeries").value=b.dataset.series;currentTab="all";document.querySelectorAll(".studio-tabs button").forEach(x=>x.classList.toggle("selected",x.dataset.tab==="all"));renderLibrary()})}
function reorderSeason(series,season,orderedIds){const seasonItems=allItems.filter(x=>(x.series||"")===series&&(Number(x.season)||1)===season);orderedIds.forEach((id,index)=>{const x=seasonItems.find(v=>String(v.id)===String(id));if(x)x.episode=index+1});return Promise.all(seasonItems.map(x=>put(x)))}
function renumberSeriesSeason(series,season){const items=allItems.filter(x=>(x.series||"")===series&&(Number(x.season)||1)===season).sort((a,b)=>(Number(a.episode)||9999)-(Number(b.episode)||9999)||String(a.createdAt||"").localeCompare(String(b.createdAt||"")));items.forEach((x,i)=>x.episode=i+1);return Promise.all(items.map(x=>put(x))}
function updateSeriesMeta(series,season,patch){const items=allItems.filter(x=>(x.series||"")===series&&(Number(x.season)||1)===season);return Promise.all(items.map(x=>put({...x,...patch})))}
function moveEpisode(id,direction){const item=allItems.find(x=>String(x.id)===String(id));if(!item||!item.series)return Promise.resolve();const season=Number(item.season)||1;const siblings=allItems.filter(x=>(x.series||"")===item.series&&(Number(x.season)||1)===season).sort((a,b)=>(Number(a.episode)||9999)-(Number(b.episode)||9999));const i=siblings.findIndex(x=>String(x.id)===String(id));const target=siblings[i+direction];if(!target)return Promise.resolve();const e=item.episode||i+1;item.episode=target.episode||i+2;target.episode=e;return Promise.all([put(item),put(target)])}
function renderSeriesTimeline(){const series=$("studioSeries").value;if(series==="all"){$("timelineTitle").textContent="Select a series";$("timelineTracks").innerHTML="<span class=\"timeline-empty\">Choose a series above to view its episode timeline.</span>";$("renumberSeasonBtn").hidden=true;return}const items=allItems.filter(x=>(x.series||"")===series).sort((a,b)=>(Number(a.season)||1)-(Number(b.season)||1)||(Number(a.episode)||9999)-(Number(b.episode)||9999));$("timelineTitle").textContent=series;const seasons=[...new Set(items.map(x=>Number(x.season)||1))];$("renumberSeasonBtn").hidden=!seasons.length;$("renumberSeasonBtn").onclick=async()=>{const season=Number(prompt("Renumber which season?",String(seasons[0]||1)));if(!Number.isFinite(season)||season<1)return;await renumberSeriesSeason(series,season);allItems=await getAll();refresh()};$("timelineTracks").innerHTML=seasons.map(season=>`<div class="timeline-season"><b>SEASON ${season}</b><button type="button" class="season-edit" data-season="${season}">Edit Season</button><div>${items.filter(x=>(Number(x.season)||1)===season).map(x=>`<div class="timeline-card"><button class="timeline-episode" data-series-id="${x.id}"><strong>EP ${x.episode||"—"}</strong><span>${esc(x.caption||"Untitled Caw")}</span><i class="${x.status}">${x.status}</i></button><div class="timeline-arrows"><button type="button" data-move="-1" data-id="${x.id}">↑</button><button type="button" data-move="1" data-id="${x.id}">↓</button></div></div>`).join("")}</div></div>`).join("");document.querySelectorAll("[data-series-id]").forEach(b=>b.onclick=()=>{const x=allItems.find(v=>String(v.id)===b.dataset.seriesId);if(x)openEditor(x)})}
function renderCalendar(){const list=allItems.filter(x=>x.status==="scheduled"&&x.scheduledAt).sort((a,b)=>new Date(a.scheduledAt)-new Date(b.scheduledAt));const next=list[0];$("nextScheduled").textContent=next?`${esc(next.caption||"Untitled Caw")} • ${new Date(next.scheduledAt).toLocaleString()}`:"No scheduled Caws";$("scheduleList").innerHTML=list.slice(0,6).map(x=>`<div class="schedule-item"><span>${new Date(x.scheduledAt).toLocaleDateString()}</span><b>${esc(x.caption||"Untitled Caw")}</b><small>${new Date(x.scheduledAt).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})}</small></div>`).join("")}
function updateSelection(){const n=selected.size;$("selectionCount").textContent=n+" selected";$("bulkLabel").textContent=n+" Caw"+(n===1?"":"s")+" selected";$("bulkBar").classList.toggle("show",n>0)}
function refreshSeriesFilter(){const sel=$("studioSeries"),current=sel.value,names=[...new Set(allItems.map(x=>(x.series||"").trim()).filter(Boolean))].sort();sel.innerHTML=`<option value="all">All Series</option>`+names.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join("");if(names.includes(current))sel.value=current}
function renderLibrary(){const q=$("studioSearch").value.trim().toLowerCase(),cat=$("studioCategory").value,series=$("studioSeries").value;let list=allItems.filter(x=>(currentTab==="all"||x.status===currentTab)&&(cat==="all"||(x.category||"General")==cat)&&(series==="all"||(x.series||"")===series));if(q)list=list.filter(x=>(x.caption+" "+x.creator+" "+x.handle).toLowerCase().includes(q));const sort=$("studioSort").value;if(sort==="views")list.sort((a,b)=>(b.views||0)-(a.views||0));if(sort==="likes")list.sort((a,b)=>(b.likes||0)-(a.likes||0));if(sort==="engagement")list.sort((a,b)=>(((b.likes||0)+(b.comments||0)+(b.recasts||0))/Math.max(b.views||0,1))-(((a.likes||0)+(a.comments||0)+(a.recasts||0))/Math.max(a.views||0,1)));$("studioLibrary").innerHTML=list.length?list.map(card).join(""):`<section class="card panel empty-studio"><div class="panel-title">NOTHING HERE YET</div><h3>Create your first Caw.</h3><p>Your drafts and published Caws will appear here.</p><button class="post-button" onclick="document.getElementById('createCaw').click()">＋ Create Caw</button></section>`;document.querySelectorAll("[data-select-id]").forEach(cb=>cb.onchange=()=>{const id=Number(cb.dataset.selectId);cb.checked?selected.add(id):selected.delete(id);updateSelection()});document.querySelectorAll(".studio-item button").forEach(b=>b.onclick=async()=>{const x=allItems.find(x=>String(x.id)===b.dataset.id);if(!x)return;if(b.dataset.act==="edit")openEditor(x);if(b.dataset.act==="duplicate")duplicateCaw(x.id);if(b.dataset.act==="publish")quickStatus(x.id,"published");if(b.dataset.act==="unpublish")quickStatus(x.id,"draft");if(b.dataset.act==="analytics"){showAnalytics(x);return}if(b.dataset.act==="view"){localStorage.setItem("crowspace:cawFocus",String(x.id));location.href="caws.html#caw-"+x.id}if(b.dataset.act==="delete"&&confirm("Delete this Caw?")){await remove(x.id);refresh()}})}
$("selectAllCaws").onclick=()=>{document.querySelectorAll("[data-select-id]").forEach(cb=>{selected.add(Number(cb.dataset.selectId));cb.checked=true});updateSelection()};$("clearSelection").onclick=()=>{selected.clear();renderLibrary()};async function bulkStatus(status){for(const id of [...selected]){const x=allItems.find(v=>v.id===id);if(x&&(status!=="published"||String(x.caption||"").trim()))await save({...x,status})}selected.clear();await refresh()}$("bulkPublish").onclick=()=>bulkStatus("published");$("bulkDraft").onclick=()=>bulkStatus("draft");$("bulkDelete").onclick=async()=>{if(!confirm("Delete selected Caws?"))return;for(const id of [...selected])await remove(id);selected.clear();await refresh()};
$("closeAnalytics").onclick=()=>document.getElementById("analyticsModal").classList.remove("show");document.getElementById("analyticsModal").addEventListener("click",e=>{if(e.target.id==="analyticsModal")e.currentTarget.classList.remove("show")});document.getElementById("studioSort").onchange=renderLibrary;
updateSelection();document.querySelectorAll(".studio-tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".studio-tabs button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");currentTab=b.dataset.tab;renderLibrary()});$("studioSearch").oninput=renderLibrary;$("studioCategory").onchange=renderLibrary;$("studioSeries").onchange=()=>{renderLibrary();renderSeriesTimeline()};
initDB().then(refresh);
