(async function(){
"use strict";
const feed=document.getElementById("cawFeed"),escapeHtml=window.CrowSpaceSocial?.esc||((s)=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m])));
let caws=[],active=0;
async function load(){
 const db=await window.CrowSpaceAuth.ready;
 const {data,error}=await db.from("crowspace_caws").select("id,user_id,title,caption,video_url,thumbnail_url,views,created_at").order("created_at",{ascending:false}).limit(50);
 if(error)throw error;
 const rows=data||[],ids=[...new Set(rows.map(x=>x.user_id))];let ps=[];
 if(ids.length){const r=await db.from("crowspace_profiles").select("user_id,username,display_name,avatar_url").in("user_id",ids);if(r.error)throw r.error;ps=r.data||[]}
 const map=new Map(ps.map(x=>[x.user_id,x]));caws=rows.map(x=>{const p=map.get(x.user_id)||{};return {...x,creator:p.display_name||p.username||"Crow Creator",handle:p.username?"@"+p.username:"@member",avatar_url:p.avatar_url||""}});caws=await (window.CrowSpaceCrossSurface?.rank?.(caws,"caw")||caws);
 if(!caws.length)caws=[{id:"empty",title:"CrowSpace Caws",caption:"Publish a Caw from Creator Studio to see it here.",video_url:"",thumbnail_url:"",creator:"Crow Creator",handle:"@creator"}];
 render();
}
function card(c,i){return '<article class="reel" data-index="'+i+'" data-id="'+c.id+'"><div class="reel-bg">'+(c.video_url?'<video class="reel-video" src="'+escapeHtml(c.video_url)+'" poster="'+escapeHtml(c.thumbnail_url||"")+'" playsinline loop muted preload="metadata"></video>':'<div class="caw-symbol">CAW</div><div class="caw-grid"></div>')+'</div><div class="reel-gradient"></div><div class="reel-content"><div class="creator-line"><div class="avatar reel-avatar">'+(c.avatar_url?'<img src="'+escapeHtml(c.avatar_url)+'" alt="">':escapeHtml((c.creator||"CM").slice(0,2).toUpperCase()))+'</div><div><b>'+escapeHtml(c.creator)+'</b><span>'+escapeHtml(c.handle)+'</span></div><button class="follow-btn">Follow</button></div><p class="caw-caption">'+escapeHtml(c.caption||c.title||"")+'</p><div class="reel-actions"><button class="action caw-like" data-id="'+c.id+'">♡ <b>0</b></button><button class="action caw-comments" data-id="'+c.id+'">💬 <b>0</b></button><button class="action caw-share" data-id="'+c.id+'">↗</button></div></div><div class="reel-progress"><i></i></div></article>'}
async function counts(){
 const db=await window.CrowSpaceAuth.ready;
 for(const c of caws.filter(x=>x.id!=="empty")){
  const r=await db.from("crowspace_social_interactions").select("*",{count:"exact",head:true}).eq("target_type","caw").eq("target_id",c.id).eq("interaction_type","like");const b=document.querySelector('.caw-like[data-id="'+c.id+'"] b');if(b)b.textContent=r.count||0;
  const q=await db.from("crowspace_comments").select("*",{count:"exact",head:true}).eq("caw_id",c.id);const cb=document.querySelector('.caw-comments[data-id="'+c.id+'"] b');if(cb)cb.textContent=q.count||0;
 }
}
function render(){feed.innerHTML=caws.map(card).join("");document.querySelectorAll(".caw-like").forEach(b=>b.onclick=async()=>{try{await window.CrowSpaceSocial.toggleCawLike(b.dataset.id,b);window.CrowSpaceLearning?.record?.("like",b.dataset.id,"caw",null,3)}catch(e){if(e.message!=="AUTH_REQUIRED")alert(e.message||"Unable to like Caw")}});document.querySelectorAll(".caw-comments").forEach(b=>b.onclick=()=>openComments(caws.find(x=>String(x.id)===b.dataset.id)));document.querySelectorAll(".caw-share").forEach(b=>b.onclick=()=>{navigator.clipboard?.writeText(location.href+"#caw-"+b.dataset.id);b.textContent="✓"});document.querySelectorAll(".follow-btn").forEach(b=>b.onclick=async()=>{const c=caws.find(x=>String(x.id)===b.closest(".reel").dataset.id);if(c?.user_id)try{await window.CrowSpaceSocial.toggleFollow(c.user_id,b);window.CrowSpaceLearning?.record?.("follow",c.user_id,"profile",null,5)}catch(e){}});observe();counts()}
async function openComments(c){const panel=document.getElementById("commentsPanel");panel.classList.add("show");panel.dataset.id=c.id;try{const rows=await window.CrowSpaceSocial.loadComments(c.id,"caw");document.getElementById("commentsList").innerHTML=rows.length?rows.map(x=>'<div class="comment"><div class="avatar">'+escapeHtml((x.profile.display_name||x.profile.username||"CM").slice(0,2).toUpperCase())+'</div><div><b>'+escapeHtml(x.profile.display_name||x.profile.username||"Crow Member")+'</b><p>'+escapeHtml(x.body)+'</p></div></div>').join(""):'<div class="comment">No comments yet.</div>'}catch(e){document.getElementById("commentsList").textContent="Unable to load comments."}}
document.getElementById("closeComments")?.addEventListener("click",()=>document.getElementById("commentsPanel").classList.remove("show"));
document.getElementById("commentForm")?.addEventListener("submit",async e=>{e.preventDefault();const input=document.getElementById("commentInput"),v=input.value.trim(),id=document.getElementById("commentsPanel").dataset.id;if(!v)return;try{await window.CrowSpaceSocial.addComment(id,v);window.CrowSpaceLearning?.record?.("comment",id,"caw",null,4);input.value="";await openComments(caws.find(x=>String(x.id)===id))}catch(err){if(err.message!=="AUTH_REQUIRED")alert(err.message||"Unable to comment")}});
function observe(){const io=new IntersectionObserver(es=>es.forEach(e=>{const v=e.target.querySelector("video");if(e.isIntersecting){active=+e.target.dataset.index;e.target.classList.add("active");const id=e.target.dataset.id;if(id&&id!=="empty"){window.CrowSpaceLearning?.record?.("caw_view",id,"caw",null,2);if(v&&!v.paused&&v.duration>0&&v.currentTime/v.duration>.8)window.CrowSpaceLearning?.record?.("caw_complete",id,"caw",null,2);}if(v)v.play().catch(()=>{})}else{e.target.classList.remove("active");if(v)v.pause()}}),{threshold:.65});document.querySelectorAll(".reel").forEach(x=>io.observe(x))}
document.getElementById("soundButton")?.addEventListener("click",()=>{const b=document.getElementById("soundButton");b.classList.toggle("enabled");b.textContent=b.classList.contains("enabled")?"🔊":"🔇";document.querySelectorAll("video").forEach(v=>v.muted=!b.classList.contains("enabled"));document.querySelector(".reel.active video")?.play().catch(()=>{})});
document.addEventListener("keydown",e=>{if(e.key==="ArrowDown"||e.key==="j"){e.preventDefault();document.querySelectorAll(".reel")[Math.min(active+1,caws.length-1)]?.scrollIntoView({behavior:"smooth"})}if(e.key==="ArrowUp"||e.key==="k"){e.preventDefault();document.querySelectorAll(".reel")[Math.max(active-1,0)]?.scrollIntoView({behavior:"smooth"})}});
await load().catch(e=>{console.error("[CrowSpace Caws]",e);feed.innerHTML='<div class="card" style="padding:24px">Caws are temporarily unavailable.</div>'});
})();