const caws=[
{id:1,creator:"KingCrow",handle:"@kingcrow",avatar:"KC",duration:"0:32",caption:"Building the next part of CrowSpace. One step at a time. #CrowSpace #CrowRules",likes:28,comments:8,recasts:5,src:""},
{id:2,creator:"Crow Creator",handle:"@creator",avatar:"CR",duration:"0:18",caption:"Creators belong here. What are you building? #Creators #CrowSpace",likes:19,comments:6,recasts:3,src:""},
{id:3,creator:"Jonathan Riehle",handle:"@jriehle",avatar:"JR",duration:"0:27",caption:"A new social universe is taking shape in Tacoma. #Tacoma #CrowSpace",likes:12,comments:4,recasts:2,src:""},
{id:4,creator:"Santa",handle:"@Santa",avatar:"🎅",duration:"0:21",caption:"North Pole transmission detected. See you in CrowSpace this Christmas. 🎄 #Santa #CrowSpace",likes:41,comments:11,recasts:7,src:""}
];
let shuffled=[...caws].sort(()=>Math.random()-.5), liked=new Set(), recawed=new Set(), activeIndex=0;
const feed=document.getElementById("cawFeed");
function card(c,i){return `<article class="reel" data-index="${i}" data-id="${c.id}"><div class="reel-bg"><div class="caw-symbol">CAW</div><div class="caw-grid"></div></div><div class="reel-gradient"></div><div class="reel-content"><div class="creator-line"><div class="avatar reel-avatar">${c.avatar}</div><div><b>${escapeHtml(c.creator)}</b><span>${escapeHtml(c.handle)} · ${c.duration}</span></div><button class="follow-btn">Follow</button></div><p class="caw-caption">${escapeHtml(c.caption).replace(/#(\\w+)/g,'<span>#$1</span>')}</p><div class="reel-actions"><button class="action like" data-action="like">♥ <b>${c.likes}</b></button><button class="action comments" data-action="comments">💬 <b>${c.comments}</b></button><button class="action recaw" data-action="recaw">↻ <b>${c.recasts}</b></button><button class="action share" data-action="share">↗</button></div></div><div class="reel-progress"><i></i></div></article>`}
function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function render(){feed.innerHTML=shuffled.map(card).join("");observe();document.querySelectorAll(".follow-btn").forEach(b=>b.onclick=()=>{b.textContent=b.textContent==="Follow"?"Following":"Follow"});document.querySelectorAll(".action").forEach(b=>b.onclick=handleAction)}
function handleAction(e){const b=e.currentTarget,a=b.closest(".reel"),id=+a.dataset.id,c=shuffled.find(x=>x.id===id),act=b.dataset.action;if(act==="like"){if(liked.has(id)){liked.delete(id);c.likes--}else{liked.add(id);c.likes++}b.classList.toggle("on",liked.has(id));b.querySelector("b").textContent=c.likes}else if(act==="recaw"){if(!recawed.has(id)){recawed.add(id);c.recasts++;b.classList.add("on");b.querySelector("b").textContent=c.recasts}}else if(act==="comments"){openComments(c)}else if(act==="share"){navigator.clipboard?.writeText(location.href+"#caw-"+id);b.textContent="✓"}}
function openComments(c){document.getElementById("commentsPanel").classList.add("show");document.getElementById("commentsPanel").dataset.id=c.id;document.getElementById("commentsList").innerHTML=[["KC","This is taking shape."],["CR","Keep building."],["JR","One step at a time."]].slice(0,Math.min(3,c.comments)).map(x=>`<div class="comment"><div class="avatar">${x[0]}</div><div><b>@${x[0].toLowerCase()}</b><p>${x[1]}</p></div></div>`).join("")}
document.getElementById("closeComments").onclick=()=>document.getElementById("commentsPanel").classList.remove("show");
document.getElementById("commentForm").onsubmit=e=>{e.preventDefault();const input=document.getElementById("commentInput"),v=input.value.trim();if(!v)return;const c=shuffled.find(x=>x.id===+document.getElementById("commentsPanel").dataset.id);c.comments++;document.getElementById("commentsList").insertAdjacentHTML("afterbegin",`<div class="comment"><div class="avatar">JR</div><div><b>@jriehle</b><p>${escapeHtml(v)}</p></div></div>`);input.value=""};
function observe(){const io=new IntersectionObserver(es=>es.forEach(e=>{const video=e.target.querySelector("video");if(e.isIntersecting){activeIndex=+e.target.dataset.index;e.target.classList.add("active");if(video){video.play().catch(()=>{})}}else{e.target.classList.remove("active");if(video)video.pause()}}),{threshold:.65});document.querySelectorAll(".reel").forEach(x=>io.observe(x))}
document.getElementById("soundButton").onclick=()=>{const b=document.getElementById("soundButton");b.classList.toggle("enabled");b.textContent=b.classList.contains("enabled")?"🔊":"🔇";document.querySelectorAll("video").forEach(v=>v.muted=!b.classList.contains("enabled"));const v=document.querySelector(".reel.active video");if(v)v.play().catch(()=>{})};
document.addEventListener("keydown",e=>{if(e.key==="ArrowDown"||e.key==="j"){e.preventDefault();document.querySelectorAll(".reel")[Math.min(activeIndex+1,shuffled.length-1)]?.scrollIntoView({behavior:"smooth"})}if(e.key==="ArrowUp"||e.key==="k"){e.preventDefault();document.querySelectorAll(".reel")[Math.max(activeIndex-1,0)]?.scrollIntoView({behavior:"smooth"})}});
let startY=0;feed.addEventListener("touchstart",e=>startY=e.touches[0].clientY,{passive:true});feed.addEventListener("touchend",e=>{const dy=startY-e.changedTouches[0].clientY;if(Math.abs(dy)>45){const n=dy>0?activeIndex+1:activeIndex-1;document.querySelectorAll(".reel")[Math.max(0,Math.min(n,shuffled.length-1))]?.scrollIntoView({behavior:"smooth"})}});
render();
