/* CrowSpace — Controlled Portfolio Holdouts v19
   Deliberately assigns treatment/control series and evaluates a synchronized holdout.
   Browser-only. Controlled evidence is still labeled as evidence, not proof of causality.
*/
(function(){
const EXP="crowspace-action-experiments-v1",KEY="crowspace-controlled-holdouts-v19",DAY=864e5,N=x=>Number(x)||0,L=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||"")||d}catch(e){return d}},S=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function dbs(){return typeof indexedDB!=="undefined"&&indexedDB.databases?indexedDB.databases():Promise.resolve([])}
async function readCaws(){const out=[];for(const d of await dbs()){try{const db=await new Promise((res,rej)=>{const q=indexedDB.open(d.name);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)});if(!db.objectStoreNames.contains("videos")){db.close();continue}const rows=await new Promise((res,rej)=>{const q=db.transaction("videos","readonly").objectStore("videos").getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error)});db.close();out.push(...rows)}catch(e){}}return out}
function published(x){return x.publishedAt||x.createdAt||x.timestamp||x.date}
function metric(rows){const views=rows.reduce((n,x)=>n+N(x.views),0),inter=rows.reduce((n,x)=>n+N(x.interactions||N(x.likes)+N(x.comments)+N(x.reCaws)),0);return{caws:rows.length,views,interactions:inter,avgViewsPerCaw:rows.length?views/rows.length:0,interactionRate:views?inter/views:0}}
function eligibleSeries(excluded=[]){const all=L(EXP,{}),bad=new Set(excluded);return Object.keys(all).filter(s=>!bad.has(s)&&!(all[s]||[]).some(e=>e.status==="active"&&!e.completedAt))}
async function capture(treatment,prior=[]){const all=await readCaws(),eligible=eligibleSeries([treatment,...prior]);const ranked=eligible.map(series=>{const rows=all.filter(x=>x.series===series&&N(published(x))>Date.now()-30*DAY&&N(published(x))<=Date.now());return{series,baseline:metric(rows)}}).filter(x=>x.baseline.caws>=3).sort((a,b)=>Math.abs(a.baseline.avgViewsPerCaw-(all.filter(x=>x.series===treatment).length?0:a.baseline.avgViewsPerCaw))-Math.abs(b.baseline.avgViewsPerCaw-(all.filter(x=>x.series===treatment).length?0:b.baseline.avgViewsPerCaw)))[0];if(!ranked)return null;return{treatment,control:ranked.series,treatmentBaseline:metric(all.filter(x=>x.series===treatment&&N(published(x))>Date.now()-30*DAY&&N(published(x))<=Date.now())),controlBaseline:ranked.baseline,capturedAt:Date.now(),windowDays:7,assignment:"CONTROLLED_HOLDOUT",version:19}}
async function evaluate(e){const h=e?.strategyTrial?.holdout;if(!h)return null;const all=await readCaws(),start=N(e.startsAt||h.capturedAt),end=N(e.endsAt)||Date.now(),tr=all.filter(x=>x.series===h.treatment&&N(published(x))>=start&&N(published(x))<=end),cr=all.filter(x=>x.series===h.control&&N(published(x))>=start&&N(published(x))<=end),tm=metric(tr),cm=metric(cr),tb=h.treatmentBaseline||{},cb=h.controlBaseline||{},td=N(tb.avgViewsPerCaw)?((tm.avgViewsPerCaw/tb.avgViewsPerCaw)-1)*100:0,cd=N(cb.avgViewsPerCaw)?((cm.avgViewsPerCaw/cb.avgViewsPerCaw)-1)*100:0,did=td-cd,minimum=Math.min(N(tb.caws),N(cb.caws),tm.caws,cm.caws)>=3,classification=!minimum?"INSUFFICIENT":did>=10?"CALIBRATED_POSITIVE":did<=-10?"CALIBRATED_NEGATIVE":"CONTROLLED_UNCERTAIN";return{measurementType:"CONTROLLED_HOLDOUT_ESTIMATE",evaluationVersion:19,treatmentSeries:h.treatment,controlSeries:h.control,treatment:tm,control:cm,treatmentBaseline:tb,controlBaseline:cb,treatmentDelta:+td.toFixed(2),controlDelta:+cd.toFixed(2),differenceInDifferences:+did.toFixed(2),classification,outcome:classification==="CALIBRATED_POSITIVE"?"STRONG":classification==="CALIBRATED_NEGATIVE"?"WEAK":"NEUTRAL",controlled:true,minDataMet:minimum,attribution:{strategyDelta:+did.toFixed(2)},note:"Controlled holdout evidence is stronger than a simple matched comparison, but this browser-local measurement does not by itself prove causality; assignment, interference, seasonality, and unmeasured differences can still affect the estimate."}}
function render(){const el=document.getElementById("controlledHoldout19");if(!el)return;const all=L(EXP,{}),rows=Object.values(all).flat().filter(e=>e.strategyTrial?.holdout).sort((a,b)=>N(b.completedAt)-N(a.completedAt)).slice(0,4),active=Object.values(all).flat().find(e=>e.status==="active"&&e.strategyTrial?.holdout),r=active?.strategyTrial?.result||rows[0]?.strategyTrial?.result;el.innerHTML='<span>CONTROLLED PORTFOLIO HOLDOUTS // V19</span><h3>Treatment vs. Control</h3><small>Strategy trials now reserve a deliberate control series for the same measurement window. Results remain labeled as controlled evidence, not automatic proof of causality.</small>'+(active?'<div class="holdout-status"><b>CONTROLLED</b><small>Treatment: '+String(active.series)+' · Control: '+String(active.strategyTrial.holdout.control)+' · '+String(active.strategyTrial.holdout.windowDays)+' day window</small></div>':'')+(r?'<div class="holdout-grid"><article><b>'+N(r.differenceInDifferences).toFixed(1)+'%</b><small>Difference-in-differences</small></article><article><b>'+N(r.treatmentDelta).toFixed(1)+'%</b><small>Treatment change</small></article><article><b>'+N(r.controlDelta).toFixed(1)+'%</b><small>Control change</small></article><article><b>'+String(r.classification)+'</b><small>'+N(r.treatment?.caws)+' treatment · '+N(r.control?.caws)+' control Caws</small></article></div>':'<div class="holdout-empty">No completed controlled holdout result yet.</div>')}
function run(){render();S(KEY,{updatedAt:Date.now(),available:true,version:19})}
setTimeout(run,7400);setInterval(run,5000);window.CrowSpaceControlledHoldouts={capture,evaluate,eligibleSeries,run};
})();