(function(){
"use strict";
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const $=s=>document.querySelector(s);
const avatar=u=>u||"https://api.dicebear.com/9.x/thumbs/svg?seed=crowspace&backgroundColor=0b1020,172554&backgroundType=gradientLinear";
function toast(m){const x=document.createElement("div");x.className="toast";x.textContent=m;document.body.appendChild(x);setTimeout(()=>x.remove(),2600)}
function nav(){const n=$(".navin");if(!n)return;n.innerHTML='<a class="brand" href="home.html">CROW<span>SPACE</span></a><div class="navlinks"><a href="home.html">Home</a><a href="explore.html">Explore</a><a href="caws.html">Caws</a><a href="circles.html">Circles</a><a href="notifications.html">Alerts</a><a href="messages.html">Messages</a><a href="profile.html">Profile</a><a href="account.html">Account</a><button id="logout">Logout</button></div>';$("#logout").onclick=async()=>{await CrowSpaceAuth.signOut();location.href="index.html"}}
async function auth(){return await CrowSpaceAuth.ready}
async function user(){const db=await auth();const r=await db.auth.getUser();return r.data.user}
async function profile(db,id){const r=await db.from("crowspace_profiles").select("user_id,username,display_name,avatar_url,bio").eq("user_id",id).maybeSingle();return r.data||{}}
async function guard(){const u=await user();if(!u){location.href="login.html";return null}return u}
function shell(){nav();window.CrowSpaceUI={esc,toast,auth,user,profile,avatar,guard}}
async function feed(limit=40){const db=await auth();const [a,b]=await Promise.all([db.from("crowspace_posts").select("id,user_id,body,title,media_url,created_at,like_count,comment_count").order("created_at",{ascending:false}).limit(limit),db.from("crowspace_holiday_bot_posts").select("id,bot_id,title,body,created_at").order("created_at",{ascending:false}).limit(limit)]);if(a.error)throw a.error;if(b.error)throw b.error;const rows=a.data||[],bp=b.data||[];const ids=[...new Set(rows.map(x=>x.user_id))], bids=[...new Set(bp.map(x=>x.bot_id))];const [ps,bs]=await Promise.all([ids.length?db.from("crowspace_profiles").select("user_id,username,display_name,avatar_url").in("user_id",ids):Promise.resolve({data:[]}),bids.length?db.from("crowspace_holiday_bots").select("id,slug,display_name,avatar_url,holiday_name").in("id",bids):Promise.resolve({data:[]})]);const pm=new Map((ps.data||[]).map(x=>[x.user_id,x])),bm=new Map((bs.data||[]).map(x=>[x.id,x]));return [...rows.map(p=>{const x=pm.get(p.user_id)||{};return {...p,kind:"member",name:x.display_name||x.username||"Crow Member",handle:x.username?"@"+x.username:"@member",avatar:avatar(x.avatar_url)}}),...bp.map(p=>{const x=bm.get(p.bot_id)||{};return {...p,kind:"bot",name:x.display_name||"Holiday Crow",handle:"@"+(x.slug||"holiday-crow"),avatar:avatar(x.avatar_url),bot_slug:x.slug}})].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))}
function postCard(p){return '<article class="card post"><div class="posthead"><img class="avatar" src="'+esc(p.avatar)+'"><div><b>'+ (p.kind==="bot"?'<a href="holiday-bot.html?bot='+encodeURIComponent(p.bot_slug)+'">'+esc(p.name)+'</a>':esc(p.name))+'</b><div class="muted">'+esc(p.handle)+' · '+new Date(p.created_at).toLocaleString()+'</div></div></div>'+(p.title?'<h3>'+esc(p.title)+'</h3>':'')+'<div class="postbody">'+esc(p.body)+'</div><div class="actions"><button class="btn" data-share="'+esc(p.id)+'">↗ Share</button></div></article>'}
async function renderFeed(el){try{const rows=await feed();el.innerHTML=rows.length?rows.map(postCard).join(""):'<div class="card empty">No posts yet.</div>';el.querySelectorAll("[data-share]").forEach(b=>b.onclick=()=>{navigator.clipboard?.writeText(location.href+"#post-"+b.dataset.share);toast("Post link copied")})}catch(e){console.error(e);el.innerHTML='<div class="card empty">CrowSpace feed unavailable.</div>'}}
async function page(){
 shell();const p=document.body.dataset.page,db=await auth();
 if(p==="index")return;
 if(p==="login"||p==="signup")return authPage(p,db);
 if(p==="home"){const u=await guard();if(!u)return;$("#welcome").textContent="Welcome back, "+(u.user_metadata?.display_name||u.email?.split("@")[0]||"Crow")+".";await renderFeed($("#feed"));return}
 if(p==="profile")return profilePage(db);
 if(p==="account")return accountPage(db);
 if(p==="explore")return explorePage(db);
 if(p==="caws")return cawsPage(db);
 if(p==="circles")return circlesPage(db);
 if(p==="messages")return messagesPage(db);
 if(p==="notifications")return notificationsPage(db);
 if(p==="holiday-bots")return botsPage(db);
}
async function authPage(kind,db){const form=$("#authForm"),msg=$("#msg");form.onsubmit=async e=>{e.preventDefault();msg.textContent="Connecting…";const email=$("#email").value.trim(),password=$("#password").value,display=$("#display")?.value.trim();let r;if(kind==="login")r=await db.auth.signInWithPassword({email,password});else r=await db.auth.signUp({email,password,options:{data:{display_name:display||email.split("@")[0]}}});if(r.error){msg.textContent=r.error.message;return}if(kind==="signup"&&r.data.user){await db.from("crowspace_profiles").upsert({user_id:r.data.user.id,username:display?display.toLowerCase().replace(/[^a-z0-9_]/g,"").slice(0,30):email.split("@")[0],display_name:display||email.split("@")[0]},{onConflict:"user_id"})}location.href="home.html"}}
async function profilePage(db){const u=await guard();if(!u)return;const p=await profile(db,u.id);$("#profile").innerHTML='<div class="card profilehero"><div class="banner"></div><div class="profilehead"><img class="profileavatar" src="'+esc(avatar(p.avatar_url))+'"><div class="profileidentity"><h1>'+esc(p.display_name||p.username||"Crow Member")+'</h1><div class="muted">@'+esc(p.username||"member")+'</div><span class="badge">CROWSPACE MEMBER</span></div></div></div><div class="grid" style="margin-top:16px"><section class="card pad"><h2>About</h2><p class="muted">'+esc(p.bio||"Building a story inside the CrowRules universe.")+'</p></section><section class="card pad"><h2>Activity</h2><div id="myPosts"></div></section></div>';const r=await db.from("crowspace_posts").select("body,title,created_at").eq("user_id",u.id).order("created_at",{ascending:false}).limit(10);$("#myPosts").innerHTML=(r.data||[]).map(x=>'<div class="statrow"><span>'+esc(x.title||x.body.slice(0,70))+'</span><small class="muted">'+new Date(x.created_at).toLocaleDateString()+'</small></div>').join("")||'<span class="muted">No posts yet.</span>'}
async function accountPage(db){const u=await guard();if(!u)return;const p=await profile(db,u.id);$("#account").innerHTML='<section class="hero"><div class="eyebrow">UNIVERSAL CROWRULES ACCOUNT</div><h1>YOUR ACCOUNT.</h1><p class="muted">'+esc(u.email)+'</p><div class="grid"><div class="card pad"><h2>Profile</h2><div class="field"><label>Display name</label><input id="an" value="'+esc(p.display_name||"")+'"></div><div class="field"><label>Username</label><input id="au" value="'+esc(p.username||"")+'"></div><div class="field"><label>Bio</label><textarea id="ab">'+esc(p.bio||"")+'</textarea></div><button id="save" class="btn primary">Save Profile</button><div id="msg" class="status" style="margin-top:10px"></div></div><div class="card pad"><h2>Membership</h2><div class="statrow"><span>Account</span><b>Connected</b></div><div class="statrow"><span>Supabase Auth</span><b>Active</b></div><div class="statrow"><span>CrowSpace</span><b>Universal</b></div></div></div></section>';$("#save").onclick=async()=>{const r=await db.from("crowspace_profiles").upsert({user_id:u.id,display_name:$("#an").value.trim(),username:$("#au").value.trim(),bio:$("#ab").value.trim()},{onConflict:"user_id"});$("#msg").textContent=r.error?r.error.message:"Profile saved."}}
async function explorePage(db){const r=await db.from("crowspace_profiles").select("user_id,username,display_name,avatar_url,bio").limit(30);$("#explore").innerHTML='<section class="hero"><div class="eyebrow">DISCOVER</div><h1>EXPLORE.</h1><p class="muted">Find members and the latest activity across CrowSpace.</p></section><section class="grid" style="margin-top:16px">'+(r.data||[]).map(p=>'<article class="card pad"><img class="avatar" src="'+esc(avatar(p.avatar_url))+'"><h3>'+esc(p.display_name||p.username||"Crow Member")+'</h3><div class="muted">@'+esc(p.username||"member")+'</div><p class="muted">'+esc(p.bio||"")+'</p></article>').join("")+'</section>'}
async function cawsPage(db){const r=await db.from("crowspace_caws").select("*").order("created_at",{ascending:false}).limit(50);$("#caws").innerHTML='<section class="hero"><div class="eyebrow">CROWSPACE // CAWS</div><h1>CAWS.</h1><p class="muted">The fast-moving video side of the CrowSpace community.</p></section><section class="grid" style="margin-top:16px">'+(r.data||[]).map(x=>'<article class="card pad"><h3>'+esc(x.title||"Caw")+'</h3><p class="muted">'+esc(x.description||x.caption||"")+'</p>'+(x.media_url?'<video controls playsinline style="width:100%;border-radius:12px" src="'+esc(x.media_url)+'"></video>':"")+'</article>').join("")+'</section>'}
async function circlesPage(db){const r=await db.from("crowspace_circles").select("*").order("created_at",{ascending:false}).limit(50);$("#circles").innerHTML='<section class="hero"><div class="eyebrow">COMMUNITIES</div><h1>CIRCLES.</h1><p class="muted">Topic-based communities inside CrowSpace.</p></section><section class="grid" style="margin-top:16px">'+(r.data||[]).map(x=>'<article class="card pad"><h3>'+esc(x.name||x.title||"Circle")+'</h3><p class="muted">'+esc(x.description||"")+'</p></article>').join("")+'</section>'}
async function messagesPage(db){const u=await guard();if(!u)return;const r=await db.from("crowspace_messages").select("*").or("sender_id.eq."+u.id+",recipient_id.eq."+u.id).order("created_at",{ascending:false}).limit(50);$("#messages").innerHTML='<section class="hero"><div class="eyebrow">DIRECT MESSAGES</div><h1>MESSAGES.</h1><p class="muted">Your CrowSpace conversations.</p></section><section class="list" style="margin-top:16px">'+(r.data||[]).map(x=>'<article class="card pad"><div>'+esc(x.body||x.message||"")+'</div><small class="muted">'+new Date(x.created_at).toLocaleString()+'</small></article>').join("")||'<div class="card empty">No messages yet.</div>'+'</section>'}
async function notificationsPage(db){const u=await guard();if(!u)return;const r=await db.from("crowspace_notifications").select("*").eq("user_id",u.id).order("created_at",{ascending:false}).limit(50);$("#notifications").innerHTML='<section class="hero"><div class="eyebrow">CROWSPACE</div><h1>NOTIFICATIONS.</h1></section><section class="list" style="margin-top:16px">'+(r.data||[]).map(x=>'<article class="card pad"><b>'+esc(x.title||"Notification")+'</b><p class="muted">'+esc(x.body||x.message||"")+'</p></article>').join("")||'<div class="card empty">No notifications yet.</div>'+'</section>'}
async function botsPage(db){const r=await db.from("crowspace_holiday_bots").select("slug,display_name,holiday_name,bio,avatar_url,active").eq("active",true).order("display_name");$("#bots").innerHTML='<section class="hero"><div class="eyebrow">AUTOMATED ACCOUNTS</div><h1>HOLIDAY BOTS.</h1><p class="muted">Follow the personalities that keep CrowSpace moving through the year.</p></section><section class="grid" style="margin-top:16px">'+(r.data||[]).map(x=>'<article class="card pad"><a href="holiday-bot.html?bot='+encodeURIComponent(x.slug)+'"><img class="avatar" src="'+esc(avatar(x.avatar_url))+'"></a><h3><a href="holiday-bot.html?bot='+encodeURIComponent(x.slug)+'">'+esc(x.display_name)+'</a></h3><div class="muted">'+esc(x.holiday_name)+'</div><p class="muted">'+esc(x.bio||"")+'</p><a class="btn" href="holiday-bot.html?bot='+encodeURIComponent(x.slug)+'">View Profile</a></article>').join("")+'</section>'}
document.addEventListener("DOMContentLoaded",()=>page().catch(e=>{console.error("[CrowSpace rebuild]",e);toast("CrowSpace could not load this page.")}));
})();