(function(){
"use strict";
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const $=s=>document.querySelector(s);
const avatar=u=>u||"https://api.dicebear.com/9.x/thumbs/svg?seed=crowspace&backgroundColor=0b1020,172554&backgroundType=gradientLinear";
function toast(m){const x=document.createElement("div");x.className="toast";x.textContent=m;document.body.appendChild(x);setTimeout(()=>x.remove(),2600)}
function nav(){const n=$(".navin");if(!n)return;n.innerHTML='<a class="brand" href="home.html">CROW<span>SPACE</span></a><div class="navlinks"><a href="home.html">Home</a><a href="explore.html">Explore</a><a href="caws.html">Caws</a><a href="circles.html">Circles</a><a href="notifications.html">Alerts <span class="nav-badge" data-live-badge="alerts" hidden>0</span></a><a href="messages.html">Messages <span class="nav-badge" data-live-badge="messages" hidden>0</span></a><a href="profile.html">Profile</a><a href="account.html">Account</a><button id="logout">Logout</button></div>';$("#logout").onclick=async()=>{await CrowSpaceAuth.signOut();location.href="index.html"}}
async function auth(){return await CrowSpaceAuth.ready}
async function user(){const db=await auth();const r=await db.auth.getUser();return r.data.user}
async function profile(db,id){const r=await db.from("crowspace_profiles").select("user_id,username,display_name,avatar_url,bio").eq("user_id",id).maybeSingle();return r.data||{}}
async function guard(){const u=await user();if(!u){location.href="login.html";return null}return u}
function commandPalette(){
 if($("#crow-command-palette"))return;
 const wrap=document.createElement("div");
 wrap.id="crow-command-palette";
 wrap.className="command-palette";
 wrap.innerHTML='<div class="command-backdrop" data-close-command></div><div class="command-panel"><div class="command-top"><span>COMMAND CENTER</span><button class="btn" data-close-command>ESC</button></div><input id="command-input" class="command-input" placeholder="Search CrowSpace pages…" autocomplete="off"><div id="command-results" class="command-results"></div></div>';
 document.body.appendChild(wrap);
 const pages=[["home.html","Home","Command Feed"],["explore.html","Explore","Discover members"],["caws.html","Caws","Short-form video"],["circles.html","Circles","Communities"],["notifications.html","Alerts","Notifications"],["messages.html","Messages","Direct messages"],["holiday-bots.html","Holiday Network","Automated accounts"],["profile.html","Profile","Your identity"],["account.html","Account","Universal account"]];
 const input=wrap.querySelector("#command-input"),results=wrap.querySelector("#command-results");
 const draw=q=>{const v=q.toLowerCase().trim();results.innerHTML=pages.filter(p=>!v||p.join(" ").toLowerCase().includes(v)).map(p=>'<a class="command-result" href="'+p[0]+'"><b>'+esc(p[1])+'</b><span>'+esc(p[2])+'</span><kbd>↵</kbd></a>').join("")||'<div class="muted" style="padding:18px">No destination found.</div>'};
 const close=()=>{wrap.classList.remove("open");input.value="";draw("")};
 const open=()=>{wrap.classList.add("open");draw("");setTimeout(()=>input.focus(),30)};
 input.oninput=()=>draw(input.value);
 wrap.querySelectorAll("[data-close-command]").forEach(x=>x.onclick=close);
 document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();open()}if(e.key==="Escape")close()});
 draw("");
}
function appShell(){
 const p=document.body.dataset.page;
 if(["index","login","signup"].includes(p))return;
 const main=$(".shell");if(!main||main.dataset.shellReady)return;
 main.dataset.shellReady="1";
 const dup=[...main.querySelectorAll(":scope > .kicker")];dup.slice(1).forEach(x=>x.remove());
 const children=[...main.children];
 const frame=document.createElement("div");frame.className="pageframe";
 const side=document.createElement("aside");side.className="sidebar";
 const active=p==="notifications"?"notifications":p;
 const links=[["home.html","home","HOME","Command feed"],["explore.html","explore","EXPLORE","Find members"],["caws.html","caws","CAWS","Short-form video"],["circles.html","circles","CIRCLES","Communities"],["notifications.html","notifications","ALERTS","Signals"],["messages.html","messages","MESSAGES","Direct conversations"],["holiday-bots.html","holiday-bots","HOLIDAY","Bot network"],["profile.html","profile","PROFILE","Identity"],["account.html","account","ACCOUNT","Universal account"]];
 side.innerHTML='<div class="side-label">CROWSPACE OS</div>'+links.map(x=>'<a class="side-link '+(active===x[1]?"active":"")+'" href="'+x[0]+'"><b>'+x[2]+'</b><span>'+x[3]+'</span>'+(x[1]==="notifications"?'<em class="nav-badge side-badge" data-live-badge="alerts" hidden>0</em>':"")+(x[1]==="messages"?'<em class="nav-badge side-badge" data-live-badge="messages" hidden>0</em>':"")+'</a>').join("")+'<div class="side-status"><i></i><b data-live-status>CONNECTING</b><span>Supabase Realtime</span></div>';
 const content=document.createElement("div");content.className="content";
 children.forEach(x=>content.appendChild(x));
 frame.append(side,content);main.replaceChildren(frame);
 const top=document.createElement("div");top.className="commandbar";
 top.innerHTML='<span><b>COMMAND CENTER</b> <span class="muted">/ '+esc((document.title||"CrowSpace").split("—")[0].trim().toUpperCase())+'</span></span><button class="btn" id="open-command">⌘K / CTRL K</button>';
 content.prepend(top);
 $("#open-command").onclick=()=>document.dispatchEvent(new KeyboardEvent("keydown",{key:"k",ctrlKey:true}));
}

function liveLayer(db,u){
 if(window.CrowSpaceLive?.stop)window.CrowSpaceLive.stop();
 const state={channels:[],presence:0,online:[],status:"CONNECTING"};
 const setStatus=s=>{state.status=s;document.querySelectorAll("[data-live-status]").forEach(x=>{x.textContent=s;x.className="live-status "+s.toLowerCase()})};
 const refreshFeed=()=>{const el=$("#feed");if(el)renderFeed(el,document.querySelector("[data-feed-filter].active")?.dataset.feedFilter||"all")};
 const badge=(kind)=>{document.querySelectorAll("[data-live-badge='"+kind+"']").forEach(x=>{const n=Number(x.dataset.count||0)+1;x.dataset.count=n;x.textContent=n>99?"99+":n;x.hidden=false})};
 const channel=db.channel("crowspace-live");
 channel.on("postgres_changes",{event:"INSERT",schema:"public",table:"crowspace_posts"},()=>{refreshFeed();toast("New CrowSpace post received")});
 channel.on("postgres_changes",{event:"INSERT",schema:"public",table:"crowspace_holiday_bot_posts"},()=>{refreshFeed();toast("Holiday Bot activity received")});channel.on("postgres_changes",{event:"*",schema:"public",table:"crowspace_likes"},()=>refreshFeed());channel.on("postgres_changes",{event:"*",schema:"public",table:"crowspace_comments"},()=>refreshFeed());
 channel.on("postgres_changes",{event:"INSERT",schema:"public",table:"crowspace_notifications",filter:"user_id=eq."+u.id},()=>{badge("alerts");toast("New notification")});
 channel.on("postgres_changes",{event:"INSERT",schema:"public",table:"crowspace_messages"},()=>{badge("messages");toast("New message activity")});

 const presence=db.channel("crowspace-presence",{config:{presence:{key:u.id}}});const typing=db.channel("crowspace-typing");typing.on("broadcast",{event:"typing"},p=>{const x=p.payload||{};if(x.user_id!==u.id)document.querySelectorAll("[data-typing]").forEach(e=>e.textContent=x.typing?((x.name||"Someone")+" is typing…"):"")});typing.subscribe();
 presence.on("presence",{event:"sync"},()=>{const p=presence.presenceState();const rows=[];Object.keys(p).forEach(k=>(p[k]||[]).forEach(v=>rows.push(v)));state.online=rows;state.presence=rows.length;document.querySelectorAll("[data-live-online]").forEach(x=>x.textContent=rows.length)});
 presence.on("presence",{event:"join"},()=>{state.presence=Object.keys(presence.presenceState()).length;document.querySelectorAll("[data-live-online]").forEach(x=>x.textContent=state.presence)});
 presence.on("presence",{event:"leave"},()=>{state.presence=Object.keys(presence.presenceState()).length;document.querySelectorAll("[data-live-online]").forEach(x=>x.textContent=state.presence)});
 state.channels=[channel,presence,typing];
 channel.subscribe((s)=>{if(s==="SUBSCRIBED")setStatus("LIVE");else if(s==="CHANNEL_ERROR"||s==="TIMED_OUT")setStatus("RECONNECTING")});
 presence.subscribe(async(s)=>{if(s==="SUBSCRIBED"){await presence.track({user_id:u.id,page:document.body.dataset.page,online_at:new Date().toISOString()})}});
 window.CrowSpaceLive={state,typing,stop:()=>state.channels.forEach(x=>db.removeChannel(x))};
 setStatus("CONNECTING");
}
\nfunction shell(){document.documentElement.dataset.crowspace="cinematic";nav();appShell();commandPalette();window.CrowSpaceUI={esc,toast,auth,user,profile,avatar,guard};}
async function feed(limit=40){const db=await auth();const [a,b]=await Promise.all([db.from("crowspace_posts").select("id,user_id,body,title,media_url,created_at,like_count,comment_count").order("created_at",{ascending:false}).limit(limit),db.from("crowspace_holiday_bot_posts").select("id,bot_id,title,body,created_at").order("created_at",{ascending:false}).limit(limit)]);if(a.error)throw a.error;if(b.error)throw b.error;const rows=a.data||[],bp=b.data||[];const ids=[...new Set(rows.map(x=>x.user_id))], bids=[...new Set(bp.map(x=>x.bot_id))];const [ps,bs]=await Promise.all([ids.length?db.from("crowspace_profiles").select("user_id,username,display_name,avatar_url").in("user_id",ids):Promise.resolve({data:[]}),bids.length?db.from("crowspace_holiday_bots").select("id,slug,display_name,avatar_url,holiday_name").in("id",bids):Promise.resolve({data:[]})]);const pm=new Map((ps.data||[]).map(x=>[x.user_id,x])),bm=new Map((bs.data||[]).map(x=>[x.id,x]));return [...rows.map(p=>{const x=pm.get(p.user_id)||{};return {...p,kind:"member",name:x.display_name||x.username||"Crow Member",handle:x.username?"@"+x.username:"@member",avatar:avatar(x.avatar_url)}}),...bp.map(p=>{const x=bm.get(p.bot_id)||{};return {...p,kind:"bot",name:x.display_name||"Holiday Crow",handle:"@"+(x.slug||"holiday-crow"),avatar:avatar(x.avatar_url),bot_slug:x.slug}})].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))}
function postCard(p){
 return '<article class="card post" id="post-'+esc(p.id)+'"><div class="posthead"><img class="avatar" src="'+esc(p.avatar)+'"><div><b>'+ (p.kind==="bot"?'<a href="holiday-bot.html?bot='+encodeURIComponent(p.bot_slug)+'">'+esc(p.name)+'</a>':esc(p.name))+'</b><div class="muted">'+esc(p.handle)+' · '+new Date(p.created_at).toLocaleString()+'</div></div></div>'+(p.title?'<h3>'+esc(p.title)+'</h3>':'')+'<div class="postbody">'+esc(p.body)+'</div><div class="actions"><button class="btn" data-like="'+esc(p.id)+'">♡ <span>'+esc(p.like_count||0)+'</span></button><button class="btn" data-comment="'+esc(p.id)+'">Comment <span>'+esc(p.comment_count||0)+'</span></button><button class="btn" data-share="'+esc(p.id)+'">↗ Share</button></div></article>';
}
function metric(label,value,detail){return '<div class="metric"><b>'+esc(value)+'</b><span>'+esc(label)+'</span><small>'+esc(detail)+'</small></div>'}
async function page(){
 shell();const p=document.body.dataset.page,db=await auth();
 if(p==="index")return;
 if(p==="login"||p==="signup")return authPage(p,db);\n const liveUser=await guard();if(!liveUser)return;liveLayer(db,liveUser);
 if(p==="home"){const u=await guard();if(!u)return;const d=await dashboardData(db,u);$("#welcome").textContent="Welcome back, "+(u.user_metadata?.display_name||u.email?.split("@")[0]||"Crow")+".";$("#welcome").insertAdjacentHTML("afterend",'<div id="dashmetrics" class="metric-grid"></div>');$("#dashmetrics").innerHTML=metric("Community posts",d.posts,"CrowSpace-wide")+metric("Members",d.profiles,"Profiles")+metric("Your alerts",d.alerts,"Notifications")+metric("Your messages",d.messages,"Conversation records")+metric("Caws",d.caws,"Media library")+metric("Holiday Bots",d.bots,"Active automated accounts");document.querySelectorAll("[data-feed-filter]").forEach(b=>b.onclick=async()=>{document.querySelectorAll("[data-feed-filter]").forEach(x=>x.classList.remove("active"));b.classList.add("active");await renderFeed($("#feed"),b.dataset.feedFilter)});
$("#publish").onsubmit=async e=>{e.preventDefault();const body=$("#body").value.trim();if(!body)return;const r=await db.from("crowspace_posts").insert({user_id:u.id,body,title:$("#title").value.trim()||null});if(r.error){toast(r.error.message);return}$("#title").value="";$("#body").value="";toast("Posted to CrowSpace");await renderFeed($("#feed"))};await renderFeed($("#feed"));return}
 if(p==="profile")return profilePage(db);
 if(p==="account")return accountPage(db);
 if(p==="explore")return explorePage(db);
 if(p==="caws")return cawsPage(db);
 if(p==="circles")return circlesPage(db);
 if(p==="messages")return messagesPage(db);
 if(p==="notifications")return notificationsPage(db);
 if(p==="holiday-bots")return botsPage(db); if(p==="holiday-bot")return botPage(db);
}
async function authPage(kind,db){const form=$("#authForm"),msg=$("#msg");form.onsubmit=async e=>{e.preventDefault();msg.textContent="Connecting…";const email=$("#email").value.trim(),password=$("#password").value,display=$("#display")?.value.trim();let r;if(kind==="login")r=await db.auth.signInWithPassword({email,password});else r=await db.auth.signUp({email,password,options:{data:{display_name:display||email.split("@")[0]}}});if(r.error){msg.textContent=r.error.message;return}if(kind==="signup"&&r.data.user){await db.from("crowspace_profiles").upsert({user_id:r.data.user.id,username:display?display.toLowerCase().replace(/[^a-z0-9_]/g,"").slice(0,30):email.split("@")[0],display_name:display||email.split("@")[0]},{onConflict:"user_id"})}location.href="home.html"}}
async function profilePage(db){const u=await guard();if(!u)return;const p=await profile(db,u.id);$("#profile").innerHTML='<div class="card profilehero"><div class="banner"></div><div class="profilehead"><img class="profileavatar" src="'+esc(avatar(p.avatar_url))+'"><div class="profileidentity"><h1>'+esc(p.display_name||p.username||"Crow Member")+'</h1><div class="muted">@'+esc(p.username||"member")+'</div><span class="badge">CROWSPACE MEMBER</span></div></div></div><div class="grid" style="margin-top:16px"><section class="card pad"><h2>About</h2><p class="muted">'+esc(p.bio||"Building a story inside the CrowRules universe.")+'</p></section><section class="card pad"><h2>Activity</h2><div id="myPosts"></div></section></div>';const r=await db.from("crowspace_posts").select("body,title,created_at").eq("user_id",u.id).order("created_at",{ascending:false}).limit(10);$("#myPosts").innerHTML=(r.data||[]).map(x=>'<div class="statrow"><span>'+esc(x.title||x.body.slice(0,70))+'</span><small class="muted">'+new Date(x.created_at).toLocaleDateString()+'</small></div>').join("")||'<span class="muted">No posts yet.</span>'}
async function accountPage(db){const u=await guard();if(!u)return;const p=await profile(db,u.id);$("#account").innerHTML='<section class="hero"><div class="eyebrow">UNIVERSAL CROWRULES ACCOUNT</div><h1>YOUR ACCOUNT.</h1><p class="muted">'+esc(u.email)+'</p><div class="grid"><div class="card pad"><h2>Profile</h2><div class="field"><label>Display name</label><input id="an" value="'+esc(p.display_name||"")+'"></div><div class="field"><label>Username</label><input id="au" value="'+esc(p.username||"")+'"></div><div class="field"><label>Bio</label><textarea id="ab">'+esc(p.bio||"")+'</textarea></div><button id="save" class="btn primary">Save Profile</button><div id="msg" class="status" style="margin-top:10px"></div></div><div class="card pad"><h2>Membership</h2><div class="statrow"><span>Account</span><b>Connected</b></div><div class="statrow"><span>Supabase Auth</span><b>Active</b></div><div class="statrow"><span>CrowSpace</span><b>Universal</b></div></div></div></section>';$("#save").onclick=async()=>{const r=await db.from("crowspace_profiles").upsert({user_id:u.id,display_name:$("#an").value.trim(),username:$("#au").value.trim(),bio:$("#ab").value.trim()},{onConflict:"user_id"});$("#msg").textContent=r.error?r.error.message:"Profile saved."}}
async function explorePage(db){const r=await db.from("crowspace_profiles").select("user_id,username,display_name,avatar_url,bio").limit(30);$("#explore").innerHTML='<section class="hero"><div class="eyebrow">DISCOVER</div><h1>EXPLORE.</h1><p class="muted">Find members and the latest activity across CrowSpace.</p></section><section class="grid" style="margin-top:16px">'+(r.data||[]).map(p=>'<article class="card pad"><img class="avatar" src="'+esc(avatar(p.avatar_url))+'"><h3>'+esc(p.display_name||p.username||"Crow Member")+'</h3><div class="muted">@'+esc(p.username||"member")+'</div><p class="muted">'+esc(p.bio||"")+'</p></article>').join("")+'</section>'}
async function cawsPage(db){const r=await db.from("crowspace_caws").select("*").order("created_at",{ascending:false}).limit(50);$("#caws").innerHTML='<section class="hero"><div class="eyebrow">CROWSPACE // CAWS</div><h1>CAWS.</h1><p class="muted">The fast-moving video side of the CrowSpace community.</p></section><section class="grid" style="margin-top:16px">'+(r.data||[]).map(x=>'<article class="card pad"><h3>'+esc(x.title||"Caw")+'</h3><p class="muted">'+esc(x.caption||"")+'</p>'+(x.video_url?'<video controls playsinline style="width:100%;border-radius:12px" src="'+esc(x.video_url||x.media_url)+'"></video>':"")+'</article>').join("")+'</section>'}
async function circlesPage(db){const r=await db.from("crowspace_circles").select("*").order("created_at",{ascending:false}).limit(50);$("#circles").innerHTML='<section class="hero"><div class="eyebrow">COMMUNITIES</div><h1>CIRCLES.</h1><p class="muted">Topic-based communities inside CrowSpace.</p></section><section class="grid" style="margin-top:16px">'+(r.data||[]).map(x=>'<article class="card pad"><h3>'+esc(x.name||x.title||"Circle")+'</h3><p class="muted">'+esc(x.description||"")+'</p></article>').join("")+'</section>'}
async function messagesPage(db){const u=await guard();if(!u)return;const r=await db.from("crowspace_messages").select("*").or("sender_id.eq."+u.id+",recipient_id.eq."+u.id).order("created_at",{ascending:false}).limit(50);$("#messages").innerHTML='<section class="hero"><div class="eyebrow">DIRECT MESSAGES</div><h1>MESSAGES.</h1><p class="muted">Your CrowSpace conversations.</p></section><section class="list" style="margin-top:16px">'+(r.data||[]).map(x=>'<article class="card pad"><div>'+esc(x.body||x.message||"")+'</div><small class="muted">'+new Date(x.created_at).toLocaleString()+'</small></article>').join("")||'<div class="card empty">No messages yet.</div>'+'</section>'}
async function notificationsPage(db){const u=await guard();if(!u)return;const r=await db.from("crowspace_notifications").select("*").eq("user_id",u.id).order("created_at",{ascending:false}).limit(50);$("#notifications").innerHTML='<section class="hero"><div class="eyebrow">CROWSPACE</div><h1>NOTIFICATIONS.</h1></section><section class="list" style="margin-top:16px">'+(r.data||[]).map(x=>'<article class="card pad"><b>'+esc(x.title||"Notification")+'</b><p class="muted">'+esc(x.body||x.message||"")+'</p></article>').join("")||'<div class="card empty">No notifications yet.</div>'+'</section>'}
async function botPage(db){
 const slug=new URLSearchParams(location.search).get("bot")||"christmas-bot";
 const q=await db.from("crowspace_holiday_bots").select("*").eq("slug",slug).maybeSingle();
 if(q.error||!q.data){$("#bot").innerHTML='<div class="hero"><h1>BOT NOT FOUND.</h1></div>';return}
 const bot=q.data;
 const pr=await db.from("crowspace_holiday_bot_posts").select("id,title,body,created_at,post_type").eq("bot_id",bot.id).order("created_at",{ascending:false}).limit(30);
 const fr=await db.from("crowspace_holiday_bot_follows").select("id",{count:"exact",head:true}).eq("bot_id",bot.id);
 const ur=await db.auth.getUser(); let following=false;
 if(ur.data.user){const f=await db.from("crowspace_holiday_bot_follows").select("id").eq("bot_id",bot.id).eq("user_id",ur.data.user.id).maybeSingle();following=!!f.data}
 const cards=(pr.data||[]).map(x=>'<article class="card post"><b>'+esc(x.title||"CrowSpace update")+'</b><div class="postbody">'+esc(x.body)+'</div><small class="muted">'+new Date(x.created_at).toLocaleString()+'</small></article>').join("")||'<div class="card empty">No posts yet.</div>';
 $("#bot").innerHTML='<section class="card profilehero"><div class="banner"></div><div class="profilehead"><img class="profileavatar" src="'+esc(avatar(bot.avatar_url))+'"><div class="profileidentity"><h1>'+esc(bot.display_name)+'</h1><div class="muted">@'+esc(bot.slug)+' · '+esc(bot.holiday_name)+'</div><span class="badge">HOLIDAY BOT</span></div><button id="follow" class="btn '+(following?"primary":"")+'">'+(following?"✓ Following":"Follow")+'</button></div></section><div class="grid" style="margin-top:16px"><section class="card pad"><h2>Identity</h2><p class="muted">'+esc(bot.bio||"")+'</p><div class="statrow"><span>Followers</span><b id="fc">'+(fr.count||0)+'</b></div><div class="statrow"><span>Status</span><b>'+ (bot.active?"AUTOMATED":"PAUSED")+'</b></div><h2>Personality</h2><p class="muted">'+esc(bot.personality||"")+'</p><h2>Posting Style</h2><p class="muted">'+esc(bot.voice_style||"")+'</p></section><section><h2>Recent Posts</h2><div class="list">'+cards+'</div></section></div>';
 $("#follow").onclick=async()=>{const r=await db.auth.getUser();if(!r.data.user){location.href="login.html";return}const op=following?db.from("crowspace_holiday_bot_follows").delete().eq("bot_id",bot.id).eq("user_id",r.data.user.id):db.from("crowspace_holiday_bot_follows").insert({bot_id:bot.id,user_id:r.data.user.id});const out=await op;if(out.error){toast(out.error.message);return}following=!following;$("#follow").textContent=following?"✓ Following":"Follow";$("#follow").classList.toggle("primary",following);$("#fc").textContent=Math.max(0,(fr.count||0)+(following?1:-1))};
}
async function botsPage(db){const r=await db.from("crowspace_holiday_bots").select("slug,display_name,holiday_name,bio,avatar_url,active").eq("active",true).order("display_name");$("#bots").innerHTML='<section class="hero"><div class="eyebrow">AUTOMATED ACCOUNTS</div><h1>HOLIDAY BOTS.</h1><p class="muted">Follow the personalities that keep CrowSpace moving through the year.</p></section><section class="grid" style="margin-top:16px">'+(r.data||[]).map(x=>'<article class="card pad"><a href="holiday-bot.html?bot='+encodeURIComponent(x.slug)+'"><img class="avatar" src="'+esc(avatar(x.avatar_url))+'"></a><h3><a href="holiday-bot.html?bot='+encodeURIComponent(x.slug)+'">'+esc(x.display_name)+'</a></h3><div class="muted">'+esc(x.holiday_name)+'</div><p class="muted">'+esc(x.bio||"")+'</p><a class="btn" href="holiday-bot.html?bot='+encodeURIComponent(x.slug)+'">View Profile</a></article>').join("")+'</section>'}
document.addEventListener("DOMContentLoaded",()=>page().catch(e=>{console.error("[CrowSpace rebuild]",e);toast("CrowSpace could not load this page.")}));
})();